Repository kubeflow/website, pull requests merged in 2018-09, with the labels that each got.

#192 Style lists update
  themes/kf/sass/src/styles/base_mod/_lists.sass
  themes/kf/static/css/styles.css
Labels: approved, lgtm, size/L

#203 Various updates to emphasize community resources
  config.toml
  content/docs/about/community.md
  content/docs/about/contributing.md
  content/docs/about/events.md
  content/docs/about/kubeflow.md
  themes/kf/layouts/index.html
Labels: approved, lgtm, size/L

#206 Update the docs to use 0.2.5
  content/docs/started/getting-started-gke.md
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/XS

#209 Add event submitted by Josh Bottum
  content/docs/about/events.md
Labels: approved, lgtm, size/XS

#216 Known kssonet issues added.
  content/docs/guides/troubleshooting.md
Labels: approved, lgtm, size/XS

#218 Added links to Privacy and Terms of Service pages.
  themes/kf/layouts/partials/footer.html
Labels: approved, lgtm, size/XS

#219 Added links to Privacy and Terms of Service pages. (#218)
  themes/kf/layouts/partials/footer.html
Labels: approved, lgtm, size/XS

#200 add chainer to the website.
  content/docs/guides/components/chainer.md
  themes/kf/layouts/index.html
  themes/kf/sass/src/index.html
  themes/kf/static/images/multi-framework.svg
Labels: approved, lgtm, size/XXL

#220 Add chainer guide to kubeflow.org website (merge to master)
  content/docs/guides/components/chainer.md
  themes/kf/layouts/index.html
  themes/kf/sass/src/index.html
  themes/kf/static/images/multi-framework.svg
Labels: approved, lgtm, size/XXL

#221 Updating the documentation about the history of Kubeflow and parallel projects.
  content/docs/about/kubeflow.md
Labels: approved, lgtm, size/S

#222 Adding NVIDIA TensorRT Inference Server blog post
  content/blog/nvidia_tensorrt.md
  content/blog/tensorrt_architecture.svg
  content/blog/tensorrt_inference_server.svg
  content/blog/tensorrt_metrics.svg
Labels: approved, lgtm, size/M

#223 Adds a page about the docs.
  content/docs/about/docs.md
  content/docs/images/version-dropdown.png
Labels: approved, lgtm, size/M

#225 Blog publish date on the post
  content/blog/blog_posts.md
  content/blog/nvidia_tensorrt.md
  themes/kf/layouts/blog/list.html
  themes/kf/layouts/blog/single.html
Labels: approved, lgtm, size/S

#226 changed the versioning section of README.md to reflect the change of …
  README.md
Labels: approved, lgtm, size/M

#228 Refactors the GKE getting-started guide
  config.toml
  content/docs/guides/gke/cloud-filestore.md
  content/docs/guides/gke/custom-domain.md
  content/docs/guides/gke/customizing-gke.md
  content/docs/guides/gke/private-clusters.md
  content/docs/guides/gke/troubleshooting-gke.md
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, size/XXL

#194 Add a page under component for tf-batch-prediction
  content/docs/guides/components/tfbatchpredict.md
Labels: approved, lgtm, size/L

#233 Add doc for prometheus
  content/docs/guides/monitoring.md
Labels: approved, lgtm, size/M

#238 Add more doc for tfserving
  content/docs/guides/components/tfserving.md
Labels: approved, lgtm, size/M

#239 add doc on tf serving with gpu
  content/docs/guides/components/tfserving.md
Labels: approved, lgtm, size/XS

#242 Ankush Signing Out
  OWNERS
Labels: approved, lgtm, size/XS

#244 Fix a bug in the debug command for GKE.
  content/docs/guides/gke/troubleshooting-gke.md
Labels: approved, lgtm, size/XS
