Repository kubeflow/website, pull requests merged in 2018-07, with the labels that each got.

#76 Add PyTorch docs to the website.
  content/docs/about/pytorch.md
Labels: approved, lgtm, size/L

#74 Added Kubeflow events calendar.
  content/docs/about/events.md
Labels: approved, lgtm, size/M

#84 Update getting-started.md
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/XS

#86 Update the docs for v0.2.1
  content/docs/started/getting-started-gke.md
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/L

#90 Update user_guide.md
  content/docs/about/user_guide.md
Labels: approved, lgtm, size/XS

#87 Fixing some typos and formatting on the GKE instructions page
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, size/M

#92 Bump the Kubeflow version from 0.2.1 to 0.2.2.
  content/docs/about/user_guide.md
  content/docs/started/getting-started-gke.md
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/L

#95 Fix for issue #93 (Need a community page)
  content/docs/about/community.md
  content/docs/about/events.md
Labels: approved, lgtm, size/M

#96 Add redirects to GitHub content.
  content/_redirects
Labels: approved, lgtm, size/XS

#94 Moved pytorch doc from 'About' to 'Getting Started' - issue #82
  content/docs/started/pytorch.md
Labels: approved, lgtm, size/XS

#101 Correct typo; remove underscore
  content/docs/about/user_guide.md
Labels: approved, lgtm, size/XS

#104 Design updates
  themes/kf/layouts/partials/secnav.html
  themes/kf/sass/src/scripts/scripts.js
  themes/kf/sass/src/styles/base_mod/_layout.sass
  themes/kf/sass/src/styles/modules/_navigation.sass
  themes/kf/static/css/styles.css
  themes/kf/static/js/scripts.js
Labels: approved, lgtm, size/L

#102 Adds a "Guides" section to document
  config.toml
  content/docs/about/user_guide.md
  content/docs/guides/advanced.md
  content/docs/guides/jupyter.md
  content/docs/guides/ksonnet.md
  content/docs/guides/pytorch.md
  content/docs/guides/requirements.md
  content/docs/guides/seldon.md
  content/docs/guides/tfserving.md
  content/docs/guides/tftraining.md
  content/docs/guides/troubleshooting.md
  content/docs/guides/upgrade.md
  content/docs/guides/usage-reporting.md
Labels: approved, lgtm, size/XXL

#106 Added another level in Guides section (issue #105)
  config.toml
  content/docs/guides/advanced.md
  content/docs/guides/components/jupyter.md
  content/docs/guides/components/ksonnet.md
  content/docs/guides/components/pytorch.md
  content/docs/guides/components/seldon.md
  content/docs/guides/components/tfserving.md
  content/docs/guides/components/tftraining.md
  content/docs/guides/troubleshooting.md
  content/docs/guides/upgrade.md
  content/docs/guides/usage-reporting.md
  themes/kf/layouts/partials/secnav.html
Labels: approved, lgtm, size/M

#110 Moved Katib documentation from kubeflow/kubeflow
  content/docs/guides/components/hyperparameter.md
Labels: approved, lgtm, size/M
