Repository kubeflow/website, pull requests merged in 2018-10, with the labels that each got.

#241 add job scheduling section into guides
  content/docs/guides/components/tftraining.md
  content/docs/guides/job-scheduling.md
Labels: approved, lgtm, size/L

#245 Blog change
  content/blog/nvidia_tensorrt.md
  content/blog/tensorrt_architecture.svg
Labels: approved, lgtm, size/XL

#246 Improve the docs that explain how to connect to Kubeflow UIs.
  content/docs/guides/accessing-uis.md
  content/docs/guides/components/jupyter.md
  content/docs/images/central-ui.png
  content/docs/images/jupyterlink.png
Labels: approved, lgtm, size/L

#248 Fix typo in the GCFS docs.
  content/docs/guides/gke/cloud-filestore.md
Labels: approved, lgtm, size/XS

#251 Update Minikube setup for kfctl.sh and setup-minikube.sh
  content/docs/started/ConfigInputs.png
  content/docs/started/LocalDeployment.png
  content/docs/started/getting-started-minikube.md
Labels: approved, lgtm, size/L

#253 update kube-arbitrator to kube-batch in the doc
  content/docs/guides/job-scheduling.md
Labels: approved, lgtm, size/S

#249 Update the tag to point to v0.3.0
  content/docs/started/getting-started-gke.md
  content/docs/started/getting-started.md
  themes/kf/layouts/shortcodes/kf-stable-tag.html
Labels: approved, lgtm, size/XS

#255 Fix typos
  content/docs/guides/components/ksonnet.md
  content/docs/guides/components/tfbatchpredict.md
  content/docs/guides/components/tfserving.md
  content/docs/guides/troubleshooting.md
  content/docs/guides/upgrade.md
  content/docs/guides/usage-reporting.md
  content/docs/started/getting-started-minikube.md
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/S

#257 Fix version in download.sh
  content/docs/started/getting-started-gke.md
  content/docs/started/getting-started-minikube.md
Labels: approved, lgtm, size/XS

#258 Corrected Github Repo link
  content/blog/nvidia_tensorrt.md
Labels: approved, lgtm, size/XS

#151 Creates a GCP end-to-end guide
  content/docs/guides/gke/gcp-e2e.md
  content/docs/images/gcp-e2e-ui-connect.png
  content/docs/images/gcp-e2e-ui-prediction.png
Labels: approved, lgtm, size/XXL

#256 change KUBEFLOW_SRC to KUBEFLOW_REPO
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, size/XS

#265 update doc on TF serving and Istio
  content/docs/guides/components/istio.md
  content/docs/guides/components/tfserving_new.md
Labels: approved, lgtm, size/L

#267 Modify content to make deployment using download.sh vs deploy from source a bit more clear
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/S

#271 Update stable tag to v0.3.1
  content/docs/started/getting-started-minikube.md
  themes/kf/layouts/shortcodes/kf-stable-tag.html
Labels: approved, lgtm, size/S

#263 update katib doc
  content/docs/guides/components/hyperparameter.md
Labels: approved, lgtm, size/L

#269 Add instructions to setup kubeflow using ArgoCD
  content/docs/guides/gitops-for-kubeflow.md
  content/docs/images/argo-cd-deployment-in-progess.png
  content/docs/images/argo-cd-partial-sync-ui.png
Labels: approved, lgtm, size/L

#274 0.3 blog post.
  content/blog/announcing_kubeflow_0.3.md
  content/blog/blog_posts.md
  content/blog/contributor_summit.jpg
Labels: approved, lgtm, size/L
