Repository kubeflow/website, pull requests merged in 2018-12, with the labels that each got.

#325 Fix broken list in requirements
  content/docs/guides/requirements.md
Labels: approved, lgtm, size/XS

#326 Update GKE getting started docs.
  content/docs/guides/gke/troubleshooting-gke.md
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, ok-to-test, size/S

#319 Update istio doc
  content/docs/guides/components/istio.md
Labels: approved, lgtm, size/M

#334 Update instructions for how to join GitHub org
  content/docs/about/contributing.md
Labels: approved, lgtm, size/M

#332 Cleanup serving doc
  content/docs/guides/components/tfserving.md
  content/docs/guides/components/tfserving_new.md
Labels: approved, lgtm, size/L

#329 Update KF pipeline deployment document
  content/docs/guides/pipelines/deploy-pipelines-service.md
Labels: approved, lgtm, size/L

#336 Update Kubeflow version to 0.3.4
  content/docs/guides/pipelines/deploy-pipelines-service.md
  themes/kf/layouts/shortcodes/kf-stable-tag.html
Labels: approved, lgtm, size/XS

#338 Redirects blog to medium.com and removes obsolete blog entries.
  config.toml
  content/_redirects
  content/blog/Central_UI_Screenshot.svg
  content/blog/_index.md
  content/blog/announcing_kubeflow_0.2.md
  content/blog/announcing_kubeflow_0.3.md
  content/blog/blog_posts.md
  content/blog/contributor_summit.jpg
  content/blog/kaggle-api.svg
  content/blog/kaggle_on_kubeflow.md
  content/blog/kubeflow_in_infra_premise.png
  content/blog/nb-run.svg
  content/blog/nvidia_tensorrt.md
  content/blog/spawner-ui-kaggle-nb.svg
  content/blog/tensorrt_architecture.svg
  content/blog/tensorrt_inference_server.svg
  content/blog/tensorrt_metrics.svg
  content/blog/terminal-menu.svg
  content/blog/titanic-barplot.svg
  content/blog/why_kubeflow.md
Labels: approved, lgtm, size/XXL

#343 Added a link to the getting-started guide.
  content/docs/about/kubeflow.md
Labels: approved, lgtm, size/XS

#348 Reword the pipeline deployment
  content/docs/guides/pipelines/deploy-pipelines-service.md
Labels: approved, lgtm, size/M

#352 Clarified how to add an authorized redirect URI.
  content/docs/guides/gke/gcp-e2e.md
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, size/XS

#356 correct link for viewers in pipelines-ui page
  content/docs/guides/pipelines/pipelines-ui.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#350 update typos error from Mikikube to Minikube
  content/docs/started/getting-started-minikube.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#349 fix typo error of katib doc
  content/docs/guides/components/hyperparameter.md
Labels: approved, lgtm, size/XS

#354 navigation fix (header)
  themes/kf/sass/src/styles/modules/_navigation.sass
  themes/kf/static/css/styles.css
Labels: approved, lgtm, ok-to-test, size/XS

#346 Use right S3 API Endpoint to avoid hostname can not resolve issue
  content/docs/guides/components/tfserving_new.md
Labels: approved, lgtm, ok-to-test, size/XS

#358 Update typos error in the kubeflow document
  content/docs/about/contributing.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#359 Fixed port forwarding command.
  content/docs/guides/gke/gcp-e2e.md
Labels: approved, lgtm, size/XS

#360 Add KF Pipelines section.
  themes/kf/layouts/index.html
  themes/kf/static/images/pipelines.svg
Labels: approved, lgtm, size/M

#365 Add videos & decks for recent events
  content/docs/about/events.md
Labels: approved, lgtm, size/M

#362 Update aws related documents for 0.4 release
  content/docs/guides/components/pytorch.md
  content/docs/guides/components/seldon.md
  content/docs/guides/components/tfserving_new.md
  content/docs/guides/components/tftraining.md
Labels: approved, lgtm, ok-to-test, size/L

#372 Remove duplicate information from "What is Kubeflow"
  content/docs/about/kubeflow.md
Labels: approved, lgtm, size/S

#375 Change port-forward ambassador from pod to service
  content/docs/guides/accessing-uis.md
Labels: approved, lgtm, size/XS

#368 Add "https://" to codelab link
  content/docs/about/events.md
Labels: approved, lgtm, size/S

#378 Changed the copyright statement and license to cc-by 4.0
  LICENSE
  themes/kf/layouts/partials/footer.html
Labels: approved, lgtm, size/XL

#377 Clarified use of name fields in OAuth instructions.
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, size/M

#380 Update latest KF stable release to 0.3.5
  themes/kf/layouts/shortcodes/kf-stable-tag.html
Labels: approved, lgtm, size/XS

#382 Fix indentation in Resources section
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/S
