Repository kubeflow/website, pull requests merged in 2019-08, with the labels that each got.

#1005 fix: Fix the repo
  content/docs/other-guides/job-scheduling.md
Labels: approved, lgtm, size/XS

#1004 Moved GCP Pipelines tutorial to GCP section of docs
  content/_redirects
  content/docs/gke/pipelines-tutorial.md
  content/docs/pipelines/pipelines-quickstart.md
  content/docs/pipelines/tutorials/cloud-tutorials.md
Labels: approved, lgtm, size/S

#1008 Add troubleshooting guide for notebooks
  content/docs/notebooks/setup.md
  content/docs/notebooks/troubleshoot.md
  content/docs/other-guides/troubleshooting.md
Labels: approved, lgtm, ok-to-test, size/L

#1016 add owner role requirement in GCP project setup
  content/docs/gke/deploy/project-setup.md
Labels: approved, lgtm, size/XS

#1009 Add anchor links to markdown headings.
  layouts/partials/scripts.html
Labels: approved, lgtm, size/S

#1018 Fixed link to xgboost-training-cm.py in sdk-overview
  content/docs/pipelines/sdk/sdk-overview.md
Labels: approved, lgtm, ok-to-test, size/XS

#1022 Fix anchor icon color + formatting
  layouts/partials/scripts.html
Labels: approved, lgtm, size/S

#1026 added a few clarifications to the GKE CLI installation instructions
  content/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, size/S

#1027 typo fix
  content/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, size/XS

#1028 Deployment UI requires project id, not name
  content/docs/gke/deploy/deploy-ui.md
Labels: approved, lgtm, ok-to-test, size/XS

#1015 Add references to kustomize issues
  content/docs/components/serving/istio.md
  content/docs/components/serving/pytorchserving.md
  content/docs/components/serving/seldon.md
  content/docs/components/serving/tfserving_new.md
  content/docs/components/serving/trtinferenceserver.md
  content/docs/components/training/chainer.md
  content/docs/components/training/mpi.md
  content/docs/components/training/mxnet.md
Labels: approved, lgtm, size/S

#1021 Fixed up the GCP deployment guide for CLI v0.6
  content/docs/gke/deploy/deploy-cli.md
  content/docs/gke/deploy/oauth-setup.md
Labels: approved, lgtm, size/L

#977 Fixing doc for KF installation on existing clusters
  content/docs/started/getting-started.md
  content/docs/started/k8s/_index.md
  content/docs/started/k8s/kfctl-existing-arrikto.md
  content/docs/started/k8s/kfctl-k8s-istio.md
  content/docs/started/k8s/overview.md
Labels: approved, lgtm, size/L

#1035 Added redirect and fixed links to getting-started guide for existing clusters
  content/_redirects
  content/docs/use-cases/kubeflow-on-multinode-cluster.md
Labels: approved, lgtm, size/S

#1032 Fix docs link 404 errors.
  content/docs/pipelines/tutorials/build-pipeline.md
Labels: approved, lgtm, ok-to-test, size/XS

#1031 fix mini problem in fairing doc
  content/docs/fairing/gcp/tutorials/gcp-kubeflow-notebook.md
Labels: approved, lgtm, size/XS

#1039 Fix other js features broken by heading anchor link.
  layouts/partials/hooks/body-end.html
Labels: approved, lgtm, size/XS

#971 PR for Issue 795 (outdated Pipelines SDK guide)
  content/docs/pipelines/sdk/build-component.md
Labels: approved, lgtm, ok-to-test, size/M

#1047 Update to include limitations and integrations
  content/docs/other-guides/multi-user-overview.md
Labels: approved, lgtm, size/S

#1049 Update katib Dockerfile locations link
  content/docs/reference/images.md
Labels: approved, lgtm, size/S

#1040 Instructions on setting up dynamic volume provisioner
  content/docs/started/k8s/kfctl-k8s-istio.md
Labels: approved, lgtm, size/S

#1030 Update aws docs for 0.6 release
  content/docs/aws/authentication.md
  content/docs/aws/deploy/existing-cluster.md
  content/docs/aws/deploy/install-kubeflow.md
  content/docs/aws/deploy/uninstall-kubeflow.md
Labels: approved, lgtm, size/L

#1052 xgboost url update
  content/docs/pipelines/overview/pipelines-overview.md
Labels: approved, lgtm, ok-to-test, size/XS

#1029 Updated screenshots and UI info for Kubeflow v0.6
  content/docs/components/training/tftraining.md
  content/docs/gke/pipelines-tutorial.md
  content/docs/images/add-notebook-server.png
  content/docs/images/central-ui.png
  content/docs/images/jupyterlink.png
  content/docs/images/new-notebook-server.png
  content/docs/images/notebook-servers.png
  content/docs/images/notebooks-namespace.png
  content/docs/notebooks/setup.md
  content/docs/other-guides/accessing-uis.md
  content/docs/pipelines/pipelines-quickstart.md
  layouts/shortcodes/code-webui-port-forward.html
Labels: approved, lgtm, size/L

#1025 Fix tfserving doc
  content/docs/components/serving/tfserving_new.md
Labels: approved, lgtm, size/L

#1054 Update pipeline API version
  content/docs/pipelines/reference/api/kubeflow-pipeline-api-spec.html
Labels: approved, lgtm, size/XS

#1051 Refactor getting started - streamlined hierarchy
  content/docs/reference/_index.md
  content/docs/reference/virtual-dev/_index.md
  content/docs/reference/virtual-dev/getting-started-minikf.md
  content/docs/reference/virtual-dev/getting-started-minikube.md
  content/docs/reference/virtual-dev/getting-started-multipass.md
  content/docs/started/cloud/_index.md
  content/docs/started/cloud/getting-started-aws.md
  content/docs/started/cloud/getting-started-azure.md
  content/docs/started/cloud/getting-started-gke.md
  content/docs/started/cloud/getting-started-icp.md
  content/docs/started/getting-started.md
  content/docs/started/k8s/_index.md
  content/docs/started/k8s/overview.md
  content/docs/started/workstation/_index.md
  content/docs/started/workstation/getting-started-linux.md
  content/docs/started/workstation/getting-started-macos.md
  content/docs/started/workstation/getting-started-windows.md
Labels: approved, lgtm, size/L

#1060 Fix broken links
  content/docs/pipelines/pipelines-quickstart.md
  content/docs/pipelines/sdk/output-viewer.md
Labels: approved, lgtm, size/XS

#1064 Refactored 'Other Guides' and applied redirects
  content/_redirects
  content/docs/components/training/tftraining.md
  content/docs/gke/deploy/deploy-cli.md
  content/docs/gke/deploy/deploy-ui.md
  content/docs/notebooks/troubleshoot.md
  content/docs/other-guides/_index.md
  content/docs/other-guides/accessing-uis.md
  content/docs/other-guides/kubeflow-on-multinode-cluster.md
  content/docs/other-guides/troubleshooting.md
  content/docs/other-guides/usage-reporting.md
  content/docs/other-guides/virtual-dev/_index.md
  content/docs/other-guides/virtual-dev/getting-started-minikf.md
  content/docs/other-guides/virtual-dev/getting-started-minikube.md
  content/docs/other-guides/virtual-dev/getting-started-multipass.md
  content/docs/started/workstation/getting-started-linux.md
  content/docs/started/workstation/getting-started-macos.md
  content/docs/started/workstation/getting-started-windows.md
  content/docs/upgrading/_index.md
  content/docs/upgrading/upgrade.md
  content/docs/use-cases/job-scheduling.md
Labels: approved, lgtm, size/M

#1056 Improve the kfctl_existing_arrikto doc
  content/docs/started/k8s/kfctl-existing-arrikto.md
  content/docs/started/k8s/overview.md
  content/docs/started/kfctl_existing_arrikto-architecture.svg
Labels: approved, lgtm, ok-to-test, size/L

#1058 Add metadata API reference doc
  content/docs/components/misc/metadata.md
  content/docs/reference/metadata/v1alpha1/kubeflow-metadata-api-spec.html
  content/docs/reference/overview.md
Labels: approved, lgtm, size/XXL

#1067 Fix port-forarding instructions; port-forward to istio gateway
  content/docs/other-guides/accessing-uis.md
  layouts/shortcodes/code-webui-port-forward.html
Labels: approved, lgtm, size/S

#1061 Expanded docs for the Metadata component
  content/docs/components/misc/metadata.md
  content/docs/images/metadata-artifacts-list.png
  content/docs/images/metadata-dataset.png
  content/docs/images/metadata-metrics.png
  content/docs/images/metadata-model.png
  content/docs/images/metadata-ui-option.png
Labels: approved, lgtm, size/L

#1078 Change will to may in metadata warning
  content/docs/components/misc/metadata.md
Labels: approved, lgtm, size/XS

#1072 Merge installation guidance for new and existing cluster
  content/_redirects
  content/docs/aws/deploy/existing-cluster.md
  content/docs/aws/deploy/install-kubeflow.md
  content/docs/aws/deploy/uninstall-kubeflow.md
Labels: approved, lgtm, size/L

#1073 Update Seldon docs
  content/docs/components/serving/seldon.md
Labels: approved, lgtm, size/M

#1080 Update pipeline quickstart for kf 0.6
  content/docs/pipelines/pipelines-quickstart.md
  layouts/shortcodes/pipelines-compatibility.html
Labels: approved, lgtm, size/S

#1083 Clarified port forwarding and auth for GCP
  content/docs/gke/deploy/deploy-cli.md
  content/docs/gke/deploy/deploy-ui.md
  content/docs/gke/pipelines-tutorial.md
  content/docs/gke/troubleshooting-gke.md
  content/docs/other-guides/accessing-uis.md
Labels: approved, lgtm, size/M

#1044 Update kfctl-k8s-istio.md
  content/docs/started/k8s/kfctl-k8s-istio.md
Labels: approved, lgtm, size/S

#1071 pin config links for v0.6 to v0.6-branch
  content/docs/aws/deploy/install-kubeflow.md
  content/docs/started/k8s/kfctl-existing-arrikto.md
  content/docs/started/k8s/kfctl-k8s-istio.md
Labels: approved, lgtm, size/XS

#1085 Modify the out of date guaid docs.
  content/docs/other-guides/usage-reporting.md
Labels: approved, lgtm, ok-to-test, size/M

#1086 Fixing command to retrieve the existing Dex configmap
  content/docs/started/k8s/kfctl-existing-arrikto.md
Labels: approved, lgtm, ok-to-test, size/XS

#1087 Clarified the usage reporting guide
  content/docs/other-guides/usage-reporting.md
Labels: approved, lgtm, size/M

#1055 Update kubeflow pipelines upgrade guide for kubeflow 0.6
  content/docs/pipelines/upgrade.md
Labels: approved, lgtm, size/M

#1088 markdown formatting fix.
  content/docs/other-guides/virtual-dev/getting-started-minikube.md
Labels: approved, lgtm, ok-to-test, size/XS

#1095 Change kfp sdk version to latest
  content/docs/pipelines/sdk/install-sdk.md
  layouts/shortcodes/pipelines-sdk-version.html
Labels: approved, lgtm, size/XS

#1105 Fixed launching Kubeflow dashboard in 0.6.1.
  content/docs/started/cloud/getting-started-icp.md
Labels: approved, lgtm, ok-to-test, size/XS

#1104 Update multi-user isolation overview to include Manage Contributors UI.
  content/docs/images/add-contributors.png
  content/docs/images/auto-profile1.png
  content/docs/images/auto-profile2.png
  content/docs/images/manage-contributors.png
  content/docs/images/multi-user-contributors.png
  content/docs/images/select-profile.png
  content/docs/images/view-contributors.png
  content/docs/other-guides/multi-user-overview.md
Labels: approved, lgtm, size/M

#1106 Update the v0.6.2 gcp instructions.
  content/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, size/XS

#1108 Updating issue bot configs
  .github/issue_label_bot.yaml
Labels: approved, lgtm, ok-to-test, size/XS
