Repository kubeflow/website, pull requests merged in 2019-11, with the labels that each got.

#1297 remove trailing slash for example BASE_DIR
  content/docs/started/k8s/kfctl-existing-arrikto.md
Labels: approved, lgtm, ok-to-test, size/XS

#1298 Update the example of the Profile YAML apiVersion
  content/docs/aws/deploy/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/XS

#1300 Update shortcodes path in README.md
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1301 Updated website to RC7
  layouts/shortcodes/kf-latest-version.html
Labels: approved, lgtm, size/XS

#1303 WtD fixit: Readability improvements for Kubeflow on Linux
  content/docs/started/workstation/getting-started-linux.md
Labels: approved, lgtm, ok-to-test, size/XS

#1307 Updated website to RC8
  layouts/shortcodes/kf-latest-version.html
Labels: approved, lgtm, size/XS

#1310 Removed obsolete sections from the reference index page
  content/docs/reference/_index.md
Labels: approved, lgtm, size/S

#1314 Update docs to reflect that v0.7.0 is live.
  config.toml
  layouts/shortcodes/kf-latest-version.html
Labels: approved, lgtm, size/XS

#1321 Use apps/v1 Deployments
  content/docs/components/serving/tfserving_new.md
Labels: approved, lgtm, ok-to-test, size/XS

#1319 Document compatible Kubernetes versions
  content/docs/started/k8s/overview.md
Labels: approved, lgtm, size/M

#1320 Kfserving update
  content/docs/components/serving/kfserving.md
Labels: approved, lgtm, size/S

#1322 remove ambassador reference in jupyter notebook doc
  content/docs/notebooks/setup.md
Labels: approved, lgtm, ok-to-test, size/S

#1325 Delete docs that reference deleted minikube script.
  content/docs/other-guides/virtual-dev/getting-started-minikube.md
Labels: approved, lgtm, size/M

#1306 Update kfp-latest-version.html
  layouts/shortcodes/kfp-latest-version.html
Labels: approved, lgtm, size/XS

#1327 Add reference for fairing SDK docs
  content/docs/fairing/reference/_index.md
  content/docs/fairing/reference/sdk.md
Labels: approved, lgtm, size/S

#1326 Move kfp latest version to a subfolder and add OWNERS file
  content/docs/pipelines/standalone-deployment-gcp.md
  layouts/shortcodes/kfp-latest-version.html
  layouts/shortcodes/pipelines/OWNERS
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, lgtm, size/S

#1318 update profile doc API; add instrucitons for GCP access fine grain control
  content/docs/gke/authentication.md
  content/docs/other-guides/multi-user-overview.md
Labels: approved, lgtm, size/M

#1177 Upgrade guide for KFP standalone
  content/docs/pipelines/standalone-deployment-gcp.md
  content/docs/pipelines/upgrade.md
Labels: approved, lgtm, size/M

#1304 Update logging.md
  content/docs/aws/logging.md
Labels: approved, lgtm, ok-to-test, size/XS

#1334 increase kfp latest version to 0.1.34
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, lgtm, size/XS

#1336 Update multi-user-overview.md
  content/docs/other-guides/multi-user-overview.md
Labels: approved, lgtm, ok-to-test, size/XS

#1335 Add doc fixit hosts to OWNERS for WtD AU 2019
  OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#1340 existing_arrikto: pin config to certain commit
  layouts/shortcodes/config-uri-existing-arrikto.html
Labels: approved, lgtm, size/XS

#1350 WtD fixit: Readability improvements for TensorFlow Training (TFJob)
  content/docs/components/training/tftraining.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1362 WtD fixit: Readability improvements for Contributing to Kubeflow
  content/docs/about/contributing.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1354 Update getting-started-macos.md
  content/docs/started/workstation/getting-started-macos.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1356 Change headings to sentence case.
  content/docs/started/workstation/getting-started-windows.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1388 WtD fixit: Readability improvements for removing an extra colon
  content/docs/upgrading/upgrade.md
Labels: approved, lgtm, ok-to-test, size/XS

#1376 WtD fixit: Readability improvements for Manipulate Kubernetes Resourc…
  content/docs/pipelines/sdk/manipulate-resources.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1392 WtD fixit: Readability improvements for Install Kubeflow
  content/docs/azure/deploy/install-kubeflow.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1358 WtD fixit: Readability improvements for WtD fixit: Kubeflow on Linux
  content/docs/started/workstation/getting-started-linux.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1363 WtD fixit: Readability improvements for Troubleshooting
  content/docs/other-guides/troubleshooting.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1359 WtD fixit: Readability improvements for End-to-End Pipeline Example on Azure
  content/docs/azure/azureEndtoEnd.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1377 WtD fixit: Readability improvements for: Microk8s for Kubeflow
  content/docs/other-guides/virtual-dev/getting-started-multipass.md
Labels: approved, lgtm, ok-to-test, size/S

#1364 WtD fixit: Readability improvements for Set Up Your Notebooks
  content/docs/notebooks/setup.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1394 WtD fixit: Readability improvements for <Overview of Jupyter Notebook…
  content/docs/notebooks/why-use-jupyter-notebook.md
Labels: approved, lgtm, ok-to-test, size/S

#1380 WtD fixit: Readability improvements for Enable GPU and TPU
  content/docs/pipelines/sdk/gcp/enable-gpu-and-tpu.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1383 WtD fixit: Readability improvements for Python Based Visualizations
  content/docs/pipelines/sdk/python-based-visualizations.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1384 WtD fixit: Readability improvements for IBM Cloud Private for Kubeflow
  content/docs/started/cloud/getting-started-icp.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1397 WtD fixit: Readability improvements for Authenticating Kubeflow to GCP
  content/docs/gke/authentication.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#1401 WtD fixit: Readability improvements for the title
  content/docs/about/kubeflow.md
Labels: approved, lgtm, ok-to-test, size/XS

#1368 Address review comments on PR #975
  content/docs/gke/troubleshooting-gke.md
Labels: approved, lgtm, ok-to-test, size/S

#1389 WtD fixit: Readability improvements for Community
  content/docs/about/community.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1385 Update gitops-for-kubeflow.md
  content/docs/use-cases/gitops-for-kubeflow.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1379 Update overview.md
  content/docs/started/k8s/overview.md
Labels: approved, lgtm, ok-to-test, size/XS

#1390 Remove outdated video
  content/docs/started/cloud/getting-started-gke.md
Labels: approved, lgtm, ok-to-test, size/XS

#1393 WtD fixit: Readability improvements for How to write a recursive func…
  content/docs/pipelines/sdk/dsl-recursion.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1403 Update private-clusters.md
  content/docs/gke/private-clusters.md
Labels: approved, lgtm, ok-to-test, size/M

#1399 WtD fixit: Readability improvements for KFServing
  content/docs/components/serving/kfserving.md
Labels: approved, lgtm, ok-to-test, size/M

#1369 WtD fixit: Readability improvements for Overview of Kubeflow Fairing
  content/docs/fairing/fairing-overview.md
Labels: approved, lgtm, ok-to-test, size/S

#1402 Update standalone-deployment-gcp.md
  content/docs/pipelines/standalone-deployment-gcp.md
Labels: approved, lgtm, ok-to-test, size/S

#1404 Update pipelines latest version
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, lgtm, size/XS

#1398 WtD fixit: Update standalone-deployment-gcp.md
  content/docs/pipelines/standalone-deployment-gcp.md
Labels: approved, lgtm, ok-to-test, size/M, wtd-fixit

#1378 WtD fixit: Readability improvements for Upgrading and Reinstalling
  content/docs/pipelines/upgrade.md
Labels: approved, lgtm, ok-to-test, size/XS, wtd-fixit

#1406 Changed link of "good first issue" and "help wanted"
  content/docs/about/contributing.md
Labels: approved, lgtm, ok-to-test, size/XS

#1407 Fix invalid sed statement in install docu
  content/docs/aws/deploy/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/XS

#1411 Clarified links to good first issues in contrib guide
  content/docs/about/contributing.md
Labels: approved, lgtm, size/S

#1409 generalized steps for storage class change
  content/docs/other-guides/kubeflow-on-multinode-cluster.md
Labels: approved, lgtm, ok-to-test, size/M

#1330 update iap doc
  content/docs/gke/deploy/monitor-iap-setup.md
Labels: approved, lgtm, size/L

#1414 Add a GitHub action to automatically add/remove issues from needs triage Kanban board
  .github/workflows/triage_issues.yaml
Labels: approved, lgtm, size/S

#1415 Update latest-version.html of KFP
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, lgtm, size/XS

#1418 Remove WtD AU 2019 doc fixit hosts from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1420 Update upgrade doc for upgrading from v0.6.2
  content/docs/upgrading/upgrade.md
Labels: approved, lgtm, size/S

#1405 Serving Comparison Page
  content/docs/components/serving/overview.md
Labels: approved, lgtm, size/M
