Repository kubeflow/website, pull requests merged in 2019-12, with the labels that each got.

#1430 Added links to the Metadata SDK reference docs
  content/docs/components/misc/metadata.md
  content/docs/reference/metadata/_index.md
  content/docs/reference/metadata/sdk.md
Labels: approved, lgtm, size/M

#1436 Update macos installation instructions
  content/docs/other-guides/virtual-dev/getting-started-minikube.md
Labels: approved, lgtm, ok-to-test, size/XS

#1413 add selector in Deployment spec
  content/docs/components/serving/tfserving_new.md
Labels: approved, lgtm, ok-to-test, size/XS

#1431 Updated code snippets and screenshots to match the latest XGBoost sample code
  content/docs/images/click-xgboost-sample.png
  content/docs/images/pipelines-start-xgboost-run.png
  content/docs/images/pipelines-ui.png
  content/docs/images/pipelines-xgboost-graph.png
  content/docs/pipelines/overview/pipelines-overview.md
  content/docs/pipelines/pipelines-quickstart.md
Labels: approved, lgtm, size/L

#1432 Add GPU node pool to an existing kubeflow cluster
  content/docs/gke/customizing-gke.md
Labels: approved, lgtm, ok-to-test, size/S

#1419 Added guide to additional configurations and resources for notebook servers
  content/docs/notebooks/setup.md
Labels: approved, lgtm, size/M

#1434 Changed the pipelines limitation note to mention just one issue (GCR)
  layouts/shortcodes/pipelines-compatibility.html
Labels: approved, lgtm, size/S

#1440 Fix typo in troubleshooting doc
  content/docs/notebooks/troubleshoot.md
Labels: approved, lgtm, ok-to-test, size/XS

#1441 Incompatible k8s version causes v0.7 installation fail
  content/docs/started/cloud/getting-started-icp.md
Labels: approved, lgtm, size/S

#1452 CreateContainerConfigError in Kubeflow v0.7 pod in ICP 3.2.0
  content/docs/started/cloud/getting-started-icp.md
Labels: approved, lgtm, size/XS

#1447 Update mpi-operator installation doc to use Kustomize
  content/docs/components/training/mpi.md
Labels: approved, lgtm, size/S

#1446 Expanded the quick guide to git/GitHub for novice contributors
  README.md
  quick-github-guide.md
Labels: approved, lgtm, size/L

#1457 Update the Slack invite link
  config.toml
  content/_index.html
Labels: approved, lgtm, size/XS

#1461 Add the Codelab of the Kubeflow workshop
  content/docs/examples/codelabs-tutorials.md
Labels: approved, lgtm, size/XS

#1455 Kubeflow upgrade instructions
  content/docs/upgrading/upgrade.md
Labels: approved, lgtm, size/L

#1339 Kubeflow overview
  content/docs/about/kubeflow.md
  content/docs/gke/gcp-e2e.md
  content/docs/images/kubeflow-gcp-e2e-tutorial-simplified.svg
  content/docs/images/kubeflow-gcp-e2e-tutorial.svg
  content/docs/images/kubeflow-overview-platform-diagram.svg
  content/docs/images/kubeflow-overview-workflow-diagram-1.svg
  content/docs/images/kubeflow-overview-workflow-diagram-2.svg
  content/docs/started/cloud/_index.md
  content/docs/started/getting-started.md
  content/docs/started/k8s/_index.md
  content/docs/started/kubeflow-overview.md
  content/docs/started/workstation/_index.md
Labels: approved, lgtm, size/L

#1458 Update kf-deployment-ui-version.html
  layouts/shortcodes/kf-deployment-ui-version.html
Labels: approved, lgtm, ok-to-test, size/XS

#1460 Add guide for installing MiniKF on GCP
  content/docs/images/minikf-deploy.png
  content/docs/images/minikf-info.png
  content/docs/images/minikf-kubeflow.png
  content/docs/images/minikf-launch.png
  content/docs/images/minikf-snapshot-store-login.png
  content/docs/images/minikf-snapshot-store.png
  content/docs/images/minikf-ssh.png
  content/docs/images/minikf-up.png
  content/docs/started/getting-started.md
  content/docs/started/workstation/minikf-gcp.md
Labels: approved, lgtm, size/L

#1454 Clarifications to the serving overview
  content/docs/components/serving/overview.md
Labels: approved, lgtm, size/L

#1468 Add link to Azure, Kafka, S3, pvc to kfserving example website
  content/docs/components/serving/kfserving.md
Labels: approved, lgtm, size/XS

#1462 existing-arrikto: Update config to v0.7.1
  layouts/shortcodes/config-uri-existing-arrikto.html
Labels: approved, lgtm, size/XS

#1471 Fix link to Kubeflow community in Serving overview site
  content/docs/components/serving/overview.md
Labels: approved, lgtm, size/XS

#1473 Moved guides from use-cases to other-guides section
  content/_redirects
  content/docs/other-guides/gitops-for-kubeflow.md
  content/docs/other-guides/job-scheduling.md
  content/docs/use-cases/_index.md
Labels: approved, lgtm, size/S

#1466 Update config file versions to 0.7.1
  layouts/shortcodes/config-file-aws-cognito.html
  layouts/shortcodes/config-file-aws-standard.html
  layouts/shortcodes/config-file-gcp-basic-auth.html
  layouts/shortcodes/config-file-gcp-iap.html
  layouts/shortcodes/config-file-k8s-istio.html
  layouts/shortcodes/config-uri-aws-cognito.html
  layouts/shortcodes/config-uri-aws-standard.html
  layouts/shortcodes/config-uri-existing-arrikto.html
  layouts/shortcodes/config-uri-gcp-basic-auth.html
  layouts/shortcodes/config-uri-gcp-iap.html
  layouts/shortcodes/config-uri-k8s-istio.html
  layouts/shortcodes/kf-latest-version.html
Labels: approved, lgtm, size/S

#1475 update latest kfp version
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, lgtm, size/XS

#1467 Added a matrix of deployment platforms and config files
  content/docs/started/getting-started.md
  layouts/shortcodes/config-file-existing-arrikto.html
Labels: approved, lgtm, size/M

#1144 Add Fairing on Azure docs
  content/docs/azure/deploy/install-kubeflow.md
  content/docs/fairing/azure/_index.md
  content/docs/fairing/tutorials/other-tutorials.md
  content/docs/images/azure-notebook-new-terminal.png
Labels: approved, lgtm, ok-to-test, size/L

#1472 Explained the various installation options for Kubeflow Pipelines
  content/_redirects
  content/docs/pipelines/installation/_index.md
  content/docs/pipelines/installation/overview.md
  content/docs/pipelines/installation/standalone-deployment.md
Labels: approved, lgtm, size/L

#1463 Adding minimum CPU instructions to common customizations section
  content/docs/gke/customizing-gke.md
Labels: approved, lgtm, ok-to-test, size/S

#1483 Removes extra lines from version-number files
  layouts/shortcodes/config-file-gcp-basic-auth.html
  layouts/shortcodes/config-file-gcp-iap.html
  layouts/shortcodes/config-uri-aws-cognito.html
  layouts/shortcodes/config-uri-aws-standard.html
  layouts/shortcodes/config-uri-existing-arrikto.html
  layouts/shortcodes/config-uri-gcp-basic-auth.html
  layouts/shortcodes/config-uri-gcp-iap.html
  layouts/shortcodes/kf-latest-version.html
  layouts/shortcodes/kustomize-min-version.html
  layouts/shortcodes/tf-serving-version.html
Labels: approved, lgtm, size/S

#1478 Tech writer review for Azure Fairing docs.
  content/docs/fairing/azure/_index.md
Labels: approved, lgtm, size/L

#1484 Add missing `gcloud auth login` step to "Deploy using CLI" doc
  content/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, size/XS

#1490 update kustomize deploy common
  content/docs/components/training/mpi.md
Labels: approved, lgtm, ok-to-test, size/XS

#1488 Fix typo in kubeflow-on-multinode-cluster doc
  content/docs/other-guides/kubeflow-on-multinode-cluster.md
Labels: approved, lgtm, ok-to-test, size/XS

#1489 Introducing workload identity setup for pipelines standalone
  content/docs/gke/authentication-pipelines.md
  content/docs/gke/authentication.md
  content/docs/gke/cloud-filestore.md
  content/docs/gke/custom-domain.md
  content/docs/gke/customizing-gke.md
  content/docs/gke/deploy/_index.md
  content/docs/gke/gcp-e2e.md
  content/docs/gke/monitoring.md
  content/docs/gke/pipelines-tutorial.md
  content/docs/gke/private-clusters.md
  content/docs/gke/troubleshooting-gke.md
  content/docs/pipelines/installation/standalone-deployment.md
Labels: approved, lgtm, size/L

#1491 Fixed the indentation for authentication.md file
  content/docs/gke/authentication.md
Labels: approved, lgtm, ok-to-test, size/XS

#1479 Add ONNX sample to website
  content/docs/components/serving/overview.md
Labels: approved, lgtm, size/XS
