Repository kubeflow/website, pull requests merged in 2019-06, with the labels that each got.

#718 Adds Fairing guides to install and configure
  content/docs/fairing/_index.md
  content/docs/fairing/configure-fairing.md
  content/docs/fairing/fairing-overview.md
  content/docs/fairing/gcp-ai-platform-notebook.md
  content/docs/fairing/gcp/_index.md
  content/docs/fairing/gcp/configure-gcp.md
  content/docs/fairing/gcp/tutorials/_index.md
  content/docs/fairing/gcp/tutorials/gcp-kubeflow-notebook.md
  content/docs/fairing/gcp/tutorials/gcp-local-notebook.md
  content/docs/fairing/install-fairing.md
  content/docs/fairing/tutorials/_index.md
  content/docs/fairing/tutorials/other-tutorials.md
Labels: approved, lgtm

#748 KUBEFLOW-3267 Link from the getting-started guide to the IBM Cloud Pr…
  content/docs/started/getting-started.md
Labels: approved, lgtm, ok-to-test

#741 Update Scheduler name
  content/docs/other-guides/job-scheduling.md
Labels: approved, lgtm, ok-to-test

#765 Adds joeliedtke as a website approver
  OWNERS
Labels: approved, lgtm

#766 typo fix
  content/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, ok-to-test

#770 Fixed link to Pipelines SDK reference
  content/docs/pipelines/reference/_index.md
  content/docs/pipelines/reference/sdk.md
Labels: approved, lgtm

#774 Fixed assumption that KFAPP variable includes path
  content/docs/gke/cloud-filestore.md
Labels: lgtm

#773 Added instruction to install kubectl
  content/docs/other-guides/accessing-uis.md
  content/docs/pipelines/pipelines-quickstart.md
Labels: approved, lgtm

#772 Improves link and formatting of Pipelines API reference docs
  content/docs/pipelines/reference/api.md
  content/docs/pipelines/reference/api/kubeflow-pipeline-api-spec.html
Labels: approved, lgtm

#775 Fixed info about container exit codes
  content/docs/components/tftraining.md
Labels: approved, lgtm

#777 Fixed path in gitattributes file
  .gitattributes
Labels: approved, lgtm

#778 Added next steps to the on prem getting-started guide
  content/docs/started/getting-started-k8s.md
Labels: approved, lgtm

#784 Update TF/PyTorch example references to v1
  content/docs/components/pytorch.md
  content/docs/components/tftraining.md
Labels: approved, lgtm, size/S

#779 Refactored the 'about Kubeflow' page to provide more info and links
  content/docs/about/kubeflow.md
Labels: approved, lgtm

#786 Removed yebrahim from OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#788 update doc for using universal redirect
  content/docs/gke/deploy/oauth-setup.md
  content/docs/images/oauth-credential.png
Labels: approved, lgtm, size/S

#791 Update the MiniKF guide
  content/docs/started/getting-started-minikf.md
Labels: approved, lgtm, ok-to-test, size/XS

#798 Use stable kf version in aws deployment
  content/docs/aws/deploy/install-kubeflow.md
Labels: approved, lgtm, size/XS

#789 Create getting-started-azure.md
  content/docs/started/getting-started-azure.md
Labels: approved, lgtm, ok-to-test, size/XS

#800 Update getting-started.md
  content/docs/started/getting-started.md
Labels: approved, lgtm, ok-to-test, size/XS

#801 Update getting-started-aws.md
  content/docs/started/getting-started-aws.md
Labels: approved, lgtm, ok-to-test, size/XS

#796 Expanded information about Let's Encrypt certificates
  content/docs/gke/deploy/monitor-iap-setup.md
  content/docs/gke/troubleshooting-gke.md
  content/docs/other-guides/accessing-uis.md
Labels: approved, lgtm, size/M

#805 update tfjob, pytorchjob ref scripts, style tables
  content/docs/reference/pytorchjob/v1/pytorch.md
  content/docs/reference/pytorchjob/v1beta2/pytorch.md
  content/docs/reference/tfjob/v1/common.md
  content/docs/reference/tfjob/v1/tensorflow.md
  content/docs/reference/tfjob/v1beta2/common.md
  content/docs/reference/tfjob/v1beta2/tensorflow.md
  gen-api-reference/gen-pytorchjob-api.sh
  gen-api-reference/gen-tfjob-api.sh
Labels: approved, lgtm, ok-to-test, size/L

#807 Added doc URL to 'Create issue' option
  layouts/partials/page-meta-links.html
Labels: approved, lgtm, size/S

#813 Typo in Documentation on GCP/Deploying Kubeflow/Deploy using CLI
  content/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, ok-to-test, size/XS

#811 Adds an introduction to the Pipelines SDK
  content/_redirects
  content/docs/images/pipelines-sdk-lightweight.svg
  content/docs/images/pipelines-sdk-outside-app.svg
  content/docs/images/pipelines-sdk-reusable.svg
  content/docs/images/pipelines-sdk-within-app.svg
  content/docs/pipelines/sdk/dsl-overview.md
  content/docs/pipelines/sdk/parameters.md
  content/docs/pipelines/sdk/sdk-overview.md
Labels: approved, lgtm, size/XL

#821 Removed initialization of Azure CLI, updated formatting issues for KF's Azure installation
  content/docs/azure/deploy/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/M

#820 Refactored the Pipelines navigation.
  content/_redirects
  content/docs/pipelines/metrics/_index.md
  content/docs/pipelines/overview/_index.md
  content/docs/pipelines/overview/concepts/_index.md
  content/docs/pipelines/overview/concepts/component.md
  content/docs/pipelines/overview/concepts/experiment.md
  content/docs/pipelines/overview/concepts/graph.md
  content/docs/pipelines/overview/concepts/output-artifact.md
  content/docs/pipelines/overview/concepts/pipeline.md
  content/docs/pipelines/overview/concepts/run-trigger.md
  content/docs/pipelines/overview/concepts/run.md
  content/docs/pipelines/overview/concepts/step.md
  content/docs/pipelines/overview/pipelines-overview.md
  content/docs/pipelines/pipelines-quickstart.md
  content/docs/pipelines/reference/_index.md
  content/docs/pipelines/sdk/_index.md
  content/docs/pipelines/sdk/best-practices.md
  content/docs/pipelines/sdk/build-component.md
  content/docs/pipelines/sdk/component-development.md
  content/docs/pipelines/sdk/dsl-recursion.md
  content/docs/pipelines/sdk/gcp/_index.md
  content/docs/pipelines/sdk/gcp/enable-gpu-and-tpu.md
  content/docs/pipelines/sdk/gcp/preemptible.md
  content/docs/pipelines/sdk/install-sdk.md
  content/docs/pipelines/sdk/lightweight-python-components.md
  content/docs/pipelines/sdk/output-viewer.md
  content/docs/pipelines/sdk/parameters.md
  content/docs/pipelines/sdk/pipelines-metrics.md
  content/docs/pipelines/sdk/reusable-components.md
  content/docs/pipelines/sdk/sdk-overview.md
  content/docs/pipelines/sdk/static-type-checking.md
  content/docs/pipelines/tutorials/_index.md
  content/docs/pipelines/upgrade.md
Labels: approved, lgtm, size/M

#828 fix: conda environment selection
  content/docs/pipelines/tutorials/pipelines-tutorial.md
Labels: approved, lgtm, ok-to-test, size/XS

#831 Change 'source activate' to 'conda activate'
  content/docs/pipelines/sdk/install-sdk.md
Labels: approved, lgtm, ok-to-test, size/XS

#827 Linked to the new Pipelines SDK intro from various pages
  content/docs/notebooks/setup.md
  content/docs/pipelines/overview/pipelines-overview.md
  content/docs/pipelines/pipelines-quickstart.md
  content/docs/pipelines/sdk/install-sdk.md
  content/docs/pipelines/tutorials/build-pipeline.md
  content/docs/pipelines/tutorials/pipelines-tutorial.md
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/M

#833 platform-existing: update docs for deploying on existing k8s cluster
  content/docs/started/getting-started-k8s.md
Labels: approved, lgtm, size/L

#837 KFP SDK Overview: Add mentions to more DSL entities
  content/docs/pipelines/sdk/sdk-overview.md
Labels: approved, lgtm, size/S

#839 fix typo & ol in icp getting started guide
  content/docs/started/getting-started-icp.md
Labels: approved, lgtm, ok-to-test, size/XS

#829 Added an overview of Pipelines interfaces
  content/docs/pipelines/overview/interfaces.md
Labels: approved, lgtm, size/M

#848 Revert "platform-existing: update docs for deploying on existing k8s cluster"
  content/docs/started/getting-started-k8s.md
Labels: approved, lgtm, size/L

#846 Add note about GPU based AKS cluster
  content/docs/azure/deploy/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/XS
