Repository kubeflow/website, pull requests merged in 2019-07, with the labels that each got.

#861 existing cluster: existing_arrikto: update docs on options for installing on existing K8s clusters
  content/docs/started/getting-started-k8s.md
Labels: approved, lgtm, size/L

#872 Update pipelines-quickstart.md
  content/docs/pipelines/pipelines-quickstart.md
Labels: approved, lgtm, size/XS

#874 Update job-scheduling.md
  content/docs/other-guides/job-scheduling.md
Labels: approved, lgtm, ok-to-test, size/XS

#884 Updating kubeflow kustomize requirements
  content/docs/started/requirements.md
  layouts/shortcodes/kustomize-min-version.html
Labels: approved, lgtm, size/XS

#885 Adds pipeline-sdk-version shortcode and uses it for SDK install process
  content/docs/pipelines/sdk/install-sdk.md
  layouts/shortcodes/pipelines-sdk-version.html
Labels: approved, lgtm, size/XS

#883 update doc for iap
  content/docs/gke/deploy/monitor-iap-setup.md
Labels: approved, lgtm, size/M

#887 update kfctl doc for kustomize
  content/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, size/S

#895 Updated non-working URL
  content/docs/components/pytorchserving.md
Labels: approved, lgtm, ok-to-test, size/XS

#908 Add the driftofwords as a reviewer
  OWNERS
Labels: approved, lgtm, needs-ok-to-test, size/XS

#893 add links to install tools, getting started
  content/_redirects
  content/docs/reference/downloads.md
  content/docs/started/getting-started.md
Labels: approved, lgtm, ok-to-test, size/M

#906 Katib v1alpha2 documentation update
  content/docs/components/hyperparameter.md
Labels: approved, lgtm, size/L

#902 Added a new tutorial to Examples section
  content/docs/examples/resources.md
Labels: approved, lgtm, size/XS

#854 update troubleshooting guide to reflect size of pending PVCs
  content/docs/other-guides/troubleshooting.md
Labels: approved, lgtm, ok-to-test, size/M

#911 #864: Remove ksonnet from AWS Azure deployment pages
  content/docs/aws/deploy/install-kubeflow.md
  content/docs/azure/deploy/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/M

#897 Kubeflow multinode cluster installation #896
  content/docs/started/getting-started-k8s.md
  content/docs/use-cases/kubeflow-on-multinode-cluster.md
Labels: approved, lgtm, ok-to-test, size/L

#907 Add video to GKE getting started
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, size/S

#925 Table of source locations for Docker images
  content/docs/reference/images.md
Labels: approved, lgtm, ok-to-test, size/S

#922 Break up the examples page into 4 pages
  content/docs/examples/_index.md
  content/docs/examples/blog-posts.md
  content/docs/examples/codelabs-tutorials.md
  content/docs/examples/kubeflow-samples.md
  content/docs/examples/resources.md
  content/docs/examples/videos.md
Labels: approved, lgtm, size/L

#919 Update customizing-gke.md
  content/docs/gke/customizing-gke.md
Labels: approved, lgtm, size/M

#926 Adds markdown visualization example and image
  content/docs/images/markdown-output.png
  content/docs/pipelines/sdk/output-viewer.md
Labels: approved, lgtm, size/S

#913 #867: Remove ksonnet page and add kustomize page
  content/docs/components/ksonnet.md
  content/docs/components/kustomize.md
Labels: approved, lgtm, ok-to-test, size/L

#909 Add metadata component doc for KF v0.6
  content/docs/components/metadata.md
  content/docs/other-guides/accessing-uis.md
Labels: approved, lgtm, size/M

#914 Added new topic - Using Jupyter notebooks in kubeflow
  content/docs/notebooks/submit-kubernetes.md
  content/docs/notebooks/why-use-jupyter-notebook.md
Labels: approved, lgtm, ok-to-test, size/S

#923 Merging Requirements and Getting Started page
  content/_redirects
  content/docs/started/getting-started.md
  content/docs/started/requirements.md
Labels: approved, lgtm, ok-to-test, size/M

#920 Improve organization of Kubeflow components
  content/_redirects
  content/docs/components/hyperparameter-tuning/_index.md
  content/docs/components/hyperparameter-tuning/hyperparameter.md
  content/docs/components/misc/_index.md
  content/docs/components/misc/kustomize.md
  content/docs/components/misc/metadata.md
  content/docs/components/misc/modeldb.md
  content/docs/components/misc/nuclio.md
  content/docs/components/pipelines/_index.md
  content/docs/components/pipelines/pipelines.md
  content/docs/components/serving/_index.md
  content/docs/components/serving/istio-dashboard.png
  content/docs/components/serving/istio.md
  content/docs/components/serving/pytorchserving.md
  content/docs/components/serving/seldon.md
  content/docs/components/serving/tfbatchpredict.md
  content/docs/components/serving/tfserving_new.md
  content/docs/components/serving/trtinferenceserver.md
  content/docs/components/training/_index.md
  content/docs/components/training/chainer.md
  content/docs/components/training/mpi.md
  content/docs/components/training/mxnet.md
  content/docs/components/training/pytorch.md
  content/docs/components/training/tftraining.md
Labels: approved, lgtm, ok-to-test, size/M

#933 Updated Kubeflow stable and latest versions
  layouts/shortcodes/kf-latest-version.html
  layouts/shortcodes/kf-stable-tag.html
Labels: approved, doc-sprint, lgtm, size/XS

#936 fix bash brace expansion in troubleshooting guide
  content/docs/other-guides/troubleshooting.md
Labels: approved, lgtm, ok-to-test, size/XS

#928 Remove ksonnet references from "Other Guides"
  content/docs/other-guides/advanced.md
  content/docs/other-guides/troubleshooting.md
  content/docs/other-guides/upgrade.md
  content/docs/other-guides/usage-reporting.md
Labels: approved, doc-sprint, lgtm, size/L

#934 Updating documentation of deploy-cli
  content/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, ok-to-test, size/XS

#941 [doc-sprint] Linked to simple notebook pipeline example
  content/docs/notebooks/setup.md
Labels: approved, lgtm, ok-to-test, size/XS

#939 Update instructions for TFJob and PytorchJob
  content/docs/components/training/pytorch.md
  content/docs/components/training/tftraining.md
Labels: approved, lgtm, size/L

#938 Remove ksonnet references from miscellaneous GKE docs
  content/docs/gke/custom-domain.md
  content/docs/gke/deploy/monitor-iap-setup.md
  content/docs/gke/private-clusters.md
Labels: approved, lgtm, size/M

#942 Update oauth setup instructions and delete modeldb instructions
  content/docs/components/misc/modeldb.md
  content/docs/gke/deploy/oauth-setup.md
  content/docs/images/new-oauth.png
  content/docs/images/oauth-edit.png
Labels: approved, lgtm, size/L

#944 AWS_REGION to REGION
  content/docs/aws/deploy/existing-cluster.md
Labels: approved, lgtm, ok-to-test, size/XS

#916 GCP Auth guide
  content/docs/gke/authentication.md
Labels: approved, doc-sprint, lgtm, ok-to-test, size/L

#898 kubeflow on kubernetes: existing_arrikto: add instructions for connecting with LDAP/AD
  content/docs/started/getting-started-k8s.md
Labels: approved, doc-sprint, lgtm, size/L

#954 Updated stable and latest versions to v0.6.0
  layouts/shortcodes/kf-latest-version.html
  layouts/shortcodes/kf-stable-tag.html
Labels: approved, lgtm, size/XS

#955 fix typos in overview
  content/_index.html
Labels: approved, lgtm, ok-to-test, size/XS

#947 add statement about assumerole
  content/docs/aws/deploy/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/XS

#961 fix: add missing "-f" for kubectl apply
  content/docs/components/training/tftraining.md
Labels: approved, lgtm, ok-to-test, size/XS

#921 Updates to KFP End-to-end tutorial (Issue #860)
  content/docs/pipelines/tutorials/pipelines-tutorial.md
Labels: approved, doc-sprint, lgtm, ok-to-test, size/M

#903 Initial docs for multi-user isolation
  content/docs/images/notebook-access-error.png
  content/docs/images/notebooks-in-profile.png
  content/docs/images/select-profile.png
  content/docs/other-guides/multi-user-overview.md
Labels: approved, doc-sprint, lgtm, size/L

#967 Fix a minor typo
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/XS

#957 Add namespace credentials setup steps
  content/docs/gke/authentication.md
Labels: approved, lgtm, ok-to-test, size/M

#970 add steps for onboard users
  content/docs/other-guides/multi-user-overview.md
Labels: approved, lgtm, size/S

#965 Fixed spelling mistake to reflect actual naming
  content/docs/use-cases/kubeflow-on-multinode-cluster.md
Labels: approved, lgtm, ok-to-test, size/XS

#972 Update kfp reinstall instructions for kubeflow 0.6
  content/docs/pipelines/upgrade.md
Labels: approved, lgtm, size/M

#979 Added version number to top menu bar
  README.md
  config.toml
Labels: approved, lgtm, size/M

#980 Updated website to v0.6.1
  layouts/shortcodes/kf-latest-version.html
Labels: approved, lgtm, size/XS

#984 Updated Kubernetes version and clarified version requirements
  content/docs/started/getting-started.md
  layouts/shortcodes/kubernetes-min-version.html
Labels: approved, lgtm, size/M

#985 fix a few typos
  content/docs/pipelines/sdk/sdk-overview.md
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, ok-to-test, size/XS

#981 Clarified versions available in deployment UI and CLI
  content/docs/gke/deploy/deploy-ui.md
  content/docs/pipelines/tutorials/pipelines-tutorial.md
  content/docs/started/getting-started-minikube.md
  content/docs/use-cases/gitops-for-kubeflow.md
  layouts/shortcodes/kf-deployment-ui-version.html
  layouts/shortcodes/kf-latest-version.html
  layouts/shortcodes/kf-stable-tag.html
Labels: approved, lgtm, size/M

#988 Update metadata.md
  content/docs/components/misc/metadata.md
Labels: approved, lgtm, size/XS

#999 Update customizing-gke.md
  content/docs/gke/customizing-gke.md
Labels: approved, lgtm, size/XS

#987 Update customizing-gke.md
  content/docs/gke/customizing-gke.md
Labels: approved, lgtm, size/XS

#1003 Fixed links to tutorials and codelabs
  content/docs/examples/codelabs-tutorials.md
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/M

#1001 Added link from notebooks setup to multi-user isolation doc
  content/docs/notebooks/setup.md
Labels: approved, lgtm, size/XS

#1007 minor fix
  content/docs/pipelines/sdk/gcp/preemptible.md
Labels: approved, lgtm, size/XS
