Repository kubeflow/website, pull requests merged in 2019-01, with the labels that each got.

#387 Added a note that the GKE e2e guide needs upgrading.
  content/docs/guides/gke/gcp-e2e.md
Labels: approved, lgtm, size/XS

#386 Clarifies GKE getting-started guide.
  content/docs/images/kubeflow-deployment.png
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, size/L

#392 Updated page front matter for Docsy theme.
  content/docs/guides/pipelines/pipelines-metrics.md
Labels: approved, lgtm, size/XS

#390 Update getting started guide by adding zone.
  content/docs/started/getting-started.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#364 Docs for using ModelDB
  content/docs/guides/components/modeldb.md
Labels: approved, lgtm, size/L

#398 Updated instructions for Microk8s getting started
  content/docs/started/getting-started-multipass.md
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/L

#395 Added styling to the screenshots that needed it
  content/docs/about/docs.md
  content/docs/guides/components/istio.md
  content/docs/guides/gitops-for-kubeflow.md
  content/docs/guides/gke/gcp-e2e.md
  content/docs/guides/pipelines/pipelines-metrics.md
  content/docs/guides/pipelines/pipelines-overview.md
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, size/M

#400 Update MPI Operator guide
  content/docs/guides/components/mpi.md
Labels: approved, lgtm, ok-to-test, size/M

#401 Added Docsy theme info to the docs README.
  README.md
Labels: approved, lgtm, size/L

#396 Created a quickstart guide for pipelines.
  content/docs/guides/pipelines/pipelines-quickstart.md
  content/docs/images/central-ui.png
  content/docs/images/click-pipeline-sample.png
  content/docs/images/click-xgboost-sample.png
  content/docs/images/pipelines-basic-run.png
  content/docs/images/pipelines-experiments-dashboard.png
  content/docs/images/pipelines-start-experiment.png
  content/docs/images/pipelines-start-run.png
  content/docs/images/pipelines-start-xgboost-run.png
  content/docs/images/pipelines-ui.png
  content/docs/images/pipelines-xgboost-graph.png
Labels: approved, lgtm, size/L

#405 Add pipelines team to OWNERS.
  OWNERS
Labels: approved, lgtm, size/S

#404 Corrected file name
  content/docs/guides/pipelines/output-viewer.md
Labels: approved, lgtm, size/XS

#403 Corrections to "Use an Output Viewer"
  content/docs/guides/pipelines/output-viewer.md
Labels: approved, lgtm, ok-to-test, size/S

#408 Suggest KubeFlow to use ksonnet 0.13.1 as minimal version
  layouts/shortcodes/ksonnet-min-version.html
Labels: approved, lgtm, ok-to-test, size/XS

#411 Fix a couple of typos in CONTRIBUTING.md
  content/docs/about/contributing.md
Labels: approved, lgtm, ok-to-test, size/XS

#414 update doc to reflect current apiVersion of tfjobs.kubeflow.org CRD
  content/docs/guides/components/tftraining.md
Labels: approved, lgtm, size/S

#413 Add note about beta version in Kubeflow 0.4.0 for Pytorch operator
  content/docs/guides/components/pytorch.md
Labels: approved, lgtm, size/XS

#417 Display Kubeflow logo on mobile
  assets/scss/_nav.scss
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.content
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.json
  resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content
Labels: approved, lgtm, ok-to-test, size/M

#419 Improved the pipelines overview and the overall getting-started experience.
  content/_redirects
  content/docs/guides/pipelines/build-pipeline.md
  content/docs/guides/pipelines/deploy-pipelines-service.md
  content/docs/guides/pipelines/pipelines-concepts.md
  content/docs/guides/pipelines/pipelines-overview.md
  content/docs/guides/pipelines/pipelines-quickstart.md
  content/docs/guides/pipelines/pipelines-samples.md
  content/docs/images/job.png
  content/docs/images/run.png
  layouts/shortcodes/pipelines-compatibility.html
Labels: approved, lgtm, size/L

#426 update Kubeflow Pipelines SDK version
  content/docs/guides/pipelines/pipelines-samples.md
Labels: approved, lgtm, ok-to-test, size/XS

#406 Refactoring the left-hand navigation panel.
  README.md
  content/_redirects
  content/docs/components/_index.md
  content/docs/components/chainer.md
  content/docs/components/hyperparameter.md
  content/docs/components/istio-dashboard.png
  content/docs/components/istio.md
  content/docs/components/jupyter.md
  content/docs/components/ksonnet.md
  content/docs/components/modeldb.md
  content/docs/components/mpi.md
  content/docs/components/mxnet.md
  content/docs/components/pipelines.md
  content/docs/components/pytorch.md
  content/docs/components/pytorchserving.md
  content/docs/components/seldon.md
  content/docs/components/tfbatchpredict.md
  content/docs/components/tfserving_new.md
  content/docs/components/tftraining.md
  content/docs/components/trtinferenceserver.md
  content/docs/gke/_index.md
  content/docs/gke/cloud-filestore.md
  content/docs/gke/custom-domain.md
  content/docs/gke/customizing-gke.md
  content/docs/gke/gcp-e2e.md
  content/docs/gke/private-clusters.md
  content/docs/gke/troubleshooting-gke.md
  content/docs/guides/_index.md
  content/docs/guides/components/components.md
  content/docs/other-guides/_index.md
  content/docs/other-guides/accessing-uis.md
  content/docs/other-guides/advanced.md
  content/docs/other-guides/job-scheduling.md
  content/docs/other-guides/monitoring.md
  content/docs/other-guides/troubleshooting.md
  content/docs/other-guides/upgrade.md
  content/docs/other-guides/usage-reporting.md
  content/docs/pipelines/_index.md
  content/docs/pipelines/build-component.md
  content/docs/pipelines/build-pipeline.md
  content/docs/pipelines/lightweight-python-components.md
  content/docs/pipelines/output-viewer.md
  content/docs/pipelines/pipelines-concepts.md
  content/docs/pipelines/pipelines-metrics.md
  content/docs/pipelines/pipelines-overview.md
  content/docs/pipelines/pipelines-quickstart.md
  content/docs/pipelines/pipelines-samples.md
  content/docs/pipelines/pipelines-ui.md
  content/docs/started/getting-started-gke.md
  content/docs/started/getting-started-minikube.md
  content/docs/started/getting-started-multipass.md
  content/docs/started/getting-started.md
  content/docs/started/requirements.md
  content/docs/use-cases/_index.md
  content/docs/use-cases/gitops-for-kubeflow.md
  layouts/docs/list.html
Labels: approved, lgtm, size/L

#427 Change Katib documentation
  content/docs/components/hyperparameter.md
Labels: approved, lgtm, size/L

#429 update date
  layouts/partials/footer.html
Labels: approved, lgtm, ok-to-test, size/XS

#431 clarify that KFAPP should not be a path
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/XS

#423 Updated troubleshooting for getting started (#317)
  content/docs/other-guides/troubleshooting.md
Labels: approved, lgtm, ok-to-test, size/M

#439 Corrected some syntax and formatting.
  content/docs/components/hyperparameter.md
Labels: approved, lgtm, size/L

#433 Removed duplicate pipelines-samples.md
  content/_redirects
  content/docs/pipelines/build-pipeline.md
  content/docs/pipelines/pipelines-samples.md
Labels: approved, lgtm, ok-to-test, size/L

#440 Added optional instructions on how to change the service type
  content/docs/components/tfserving_new.md
Labels: approved, lgtm, ok-to-test, size/XS

#441 Updated the Docsy theme.
  resources/_gen/assets/js/js/main.js_d11fe7b62c27961c87ecd0f2490357b9.content
  resources/_gen/assets/js/js/main.js_d11fe7b62c27961c87ecd0f2490357b9.json
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.content
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.json
  resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content
  themes/docsy/README.md
  themes/docsy/assets/js/base.js
  themes/docsy/assets/scss/_code.scss
  themes/docsy/assets/scss/blocks/_cover.scss
  themes/docsy/layouts/_default/content.html
  themes/docsy/layouts/partials/feedback.html
  themes/docsy/layouts/partials/footer.html
  themes/docsy/layouts/partials/navbar.html
  themes/docsy/layouts/shortcodes/blocks/cover.html
  themes/docsy/layouts/shortcodes/blocks/feature.html
  themes/docsy/layouts/shortcodes/readfile.md
Labels: approved, lgtm, size/L

#442 Updated document for pipeline.
  content/docs/pipelines/pipelines-concepts.md
  content/docs/pipelines/pipelines-metrics.md
  content/docs/pipelines/pipelines-ui.md
Labels: approved, lgtm, size/S

#445 Added instructions for deleting KF deployment from Deployment Manager
  content/docs/images/delete-deployment.png
  content/docs/images/deployments.png
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm, size/S

#447 Renamed logo files and restored Docsy cover image feature.
  content/_index.html
  content/jupyter.svg
  content/tensorflow.svg
  themes/docsy/layouts/shortcodes/blocks/cover.html
Labels: approved, lgtm

#451 Add links for Data Day TX
  content/docs/about/events.md
Labels: approved, lgtm

#449 Added a resources file where the community can link to external workshops, blog posts, etc
  assets/scss/_variables_project.scss
  content/docs/examples/resources.md
  content/docs/other-guides/_index.md
  layouts/shortcodes/blocks/content-item.html
  layouts/shortcodes/blocks/content-section.html
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.content
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.json
  resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content
Labels: approved, lgtm

#453 Update tftraining.md
  content/docs/components/tftraining.md
Labels: approved, lgtm, ok-to-test
