Repository kubeflow/website, pull requests merged in 2019-05, with the labels that each got.

#678 Fix typo in existing cluster deployment doc
  content/docs/aws/deploy/existing-cluster.md
Labels: approved, lgtm, ok-to-test

#676 Tech writer refactor of GCP deployment docs
  content/docs/gke/deploy/_index.md
  content/docs/gke/deploy/delete-cli.md
  content/docs/gke/deploy/delete-ui.md
  content/docs/gke/deploy/deploy-cli.md
  content/docs/gke/deploy/deploy-ui.md
  content/docs/gke/deploy/next-steps.md
  content/docs/gke/deploy/oauth-setup.md
  content/docs/gke/deploy/project-setup.md
  content/docs/gke/deploy/reasons.md
  content/docs/started/getting-started-gke.md
Labels: approved, lgtm

#668 Adds instructions for the XGBoost notebook on AI Platform notebooks
  content/docs/fairing/fairing-overview.md
  content/docs/fairing/gcp-ai-platform-notebook.md
  content/docs/images/fairing/ai-platform-notebook-pytorch.png
Labels: approved, lgtm

#672 Getting-started guide: Linked to AWS docs and did a tech writer review
  content/docs/started/getting-started.md
Labels: approved, lgtm

#682 Update the private cluster instructions
  content/docs/gke/private-clusters.md
Labels: approved, lgtm

#684 add get start kubeflow with icp
  content/docs/started/getting-started-icp.md
Labels: approved, lgtm

#689 Update hyperparameter.md
  content/docs/components/hyperparameter.md
Labels: approved, lgtm, ok-to-test

#691 Fix typo in Getting Started on IBM Cloud Private
  content/docs/started/getting-started-icp.md
Labels: approved, lgtm, ok-to-test

#687 Getting started guide does not refer ks
  content/docs/started/getting-started-k8s.md
Labels: approved, lgtm, ok-to-test

#686 Adding nuclio component doc
  content/docs/components/nuclio.md
  resources/_gen/assets/js/js/search.js_b4bb3e7b21b43e920b7c367ff787d383.content
Labels: approved, lgtm, needs-ok-to-test

#688 Update kubeflow sdk version
  content/docs/pipelines/sdk/install-sdk.md
  layouts/shortcodes/pipelines-sdk-version.html
Labels: approved, lgtm, ok-to-test

#697 Clarified IAP monitoring and auth services
  content/docs/gke/deploy/deploy-cli.md
  content/docs/gke/deploy/monitor-iap-setup.md
Labels: approved, lgtm

#699 Added Pipelines preemptible VMs and GPUs
  content/docs/pipelines/preemptible.md
Labels: approved, lgtm

#698 Highligt how to install k8s cluster.
  content/docs/started/getting-started-k8s.md
Labels: approved, lgtm

#702 Update cloud filestore instructions for 0.5
  content/docs/gke/cloud-filestore.md
Labels: approved, lgtm

#701 Added v0.5 branch to dropdown
  README.md
  config.toml
Labels: approved, lgtm

#700 update gcp-e2e page since ksonnet is removed
  content/docs/gke/gcp-e2e.md
Labels: approved, lgtm

#696 Adds a style guide for the Kubeflow docs
  README.md
  content/docs/about/docs.md
  content/docs/about/style-guide.md
Labels: approved, lgtm

#711 Automated cherry pick of #702: Update cloud filestore instructions for 0.5 Cherry pick of #702 on v0.5-branch. #702: Update cloud filestore instructions for 0.5
  content/docs/gke/cloud-filestore.md
Labels: approved, lgtm

#705 Expands introduction to Kubeflow Pipelines quickstart
  content/docs/pipelines/pipelines-quickstart.md
Labels: approved, lgtm

#710 Update to how to create users
  content/docs/gke/customizing-gke.md
Labels: approved, lgtm, ok-to-test

#713 Replaced 'k8s' with full brand name where relevant
  content/docs/components/tfbatchpredict.md
  content/docs/components/tftraining.md
  content/docs/gke/troubleshooting-gke.md
  content/docs/other-guides/troubleshooting.md
Labels: approved, lgtm

#709 Fixed indentation that broke numbering on CLI deployment page.
  content/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, needs-ok-to-test

#715 Updated language in pytorch-operator to fix broken link in issue 635
  content/docs/components/pytorch.md
Labels: approved, lgtm, ok-to-test

#721 Fix for issue #704
  content/docs/pipelines/pipelines-overview.md
Labels: approved, lgtm

#719 Add notes for eksctl incompatible version issue
  content/docs/aws/deploy/install-kubeflow.md
  content/docs/aws/troubleshooting-aws.md
Labels: approved, lgtm

#717 nuclio-edits
  content/_index.html
  content/docs/components/nuclio.md
Labels: approved, lgtm, ok-to-test

#728 Added the doc sprint to the events page
  content/docs/about/events.md
Labels: approved, lgtm

#712 Added auth and other details to the UI deployment guide
  content/docs/gke/deploy/deploy-ui.md
  content/docs/images/kubeflow-deployment.png
Labels: approved, lgtm

#731 Added instructions to start port forwarding before trying to access Web UIs
  content/docs/other-guides/accessing-uis.md
  content/docs/started/getting-started-minikube.md
  layouts/shortcodes/code-webui-port-forward.html
Labels: approved, lgtm, ok-to-test

#733 Added code style within tables
  resources/_gen/assets/scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content
  themes/docsy/assets/scss/_code.scss
Labels: approved, lgtm

#722 Highlights how write out metrics and results for visualization by the Kubeflow Pipelines UI
  content/docs/images/metric.png
  content/docs/images/taxi-tip-analysis-step-output-webapp-popped-out.png
  content/docs/images/taxi-tip-confusion-matrix-step-output.png
  content/docs/images/taxi-tip-prediction-step-output-table.png
  content/docs/images/taxi-tip-roc-step-output.png
  content/docs/images/taxi-tip-run-output.png
  content/docs/images/taxi-tip-run-scores.png
  content/docs/images/taxi-tip-training-step-output-tensorboard.png
  content/docs/pipelines/metrics/output-viewer.md
  content/docs/pipelines/metrics/pipelines-metrics.md
  content/docs/pipelines/sdk/component-development.md
Labels: approved, lgtm

#735 Fix an issue in gcp-e2e.md.
  content/docs/gke/gcp-e2e.md
Labels: approved, lgtm, ok-to-test

#736 Added generated SCSS files to complete styling change for code in tables
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.content
  resources/_gen/assets/scss/scss/main.scss_5398e26fd581c6d99b97101474eff48e.json
Labels: approved, lgtm

#739 Update the MiniKF guide
  content/docs/started/getting-started-minikf.md
Labels: approved, lgtm, ok-to-test

#740 Added the link to the SDK reference docs
  content/docs/pipelines/reference/_index.md
  content/docs/pipelines/sdk/install-sdk.md
Labels: approved, lgtm

#742 Add document for KFP API
  content/docs/pipelines/reference/api.md
  content/docs/pipelines/reference/api/kubeflow-pipeline-api-spec.html
Labels: approved, lgtm

#744 update kfp api doc
  content/docs/pipelines/reference/api/kubeflow-pipeline-api-spec.html
Labels: approved, lgtm
