Repository kubeflow/website, pull requests merged in 2020-06, with the labels that each got.

#1974 Add instructions for how to deal with failed not visible certificate errors
  content/en/docs/gke/troubleshooting-gke.md
Labels: approved, lgtm, size/M

#1975 Auto-generate api reference doc
  content/en/docs/pipelines/reference/api/kubeflow-pipeline-api-spec.html
Labels: approved, lgtm, size/XXL

#1933 State compatibility with Kubernetes 1.16
  content/en/docs/started/k8s/overview.md
Labels: approved, lgtm, ok-to-test, size/M

#1977 Update _index.md
  content/en/docs/pipelines/overview/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#1983 Update doc to run Katib experiment without the goal
  content/en/docs/components/hyperparameter-tuning/experiment.md
Labels: approved, lgtm, size/S

#1907 Update katib-config document to describe suggestion service images
  content/en/docs/components/hyperparameter-tuning/experiment.md
  content/en/docs/components/hyperparameter-tuning/katib-config.md
Labels: approved, lgtm, size/S

#1982 Rename Katib NAS RL algorithm to ENAS
  content/en/docs/components/hyperparameter-tuning/experiment.md
  content/en/docs/components/hyperparameter-tuning/overview.md
Labels: approved, lgtm, size/L

#1995 Katib resume policy information
  content/en/docs/components/hyperparameter-tuning/experiment.md
  content/en/docs/components/hyperparameter-tuning/hyperparameter.md
Labels: approved, lgtm, size/S

#1991 Katib documentation for DARTS algorithm
  content/en/docs/components/hyperparameter-tuning/experiment.md
Labels: approved, lgtm, size/L

#1992 Add a small example of listing pipeline with a filter
  content/en/docs/pipelines/tutorials/sdk-examples.md
Labels: approved, lgtm, size/M

#1950 Change pipelines metric name regex limitation for kubeflow/pipelines#3741
  content/en/docs/pipelines/sdk/pipelines-metrics.md
Labels: approved, lgtm, size/XS

#1999 Update do Microk8s.enable Kubeflow docs
  content/en/docs/started/workstation/getting-started-multipass.md
Labels: approved, lgtm, ok-to-test, size/M

#2004 Adds configuration for Netlify deployments to branches
  netlify.toml
Labels: approved, lgtm, size/XS

#2007 Updates netlify config for branch deployments. (#2004)
  netlify.toml
Labels: approved, lgtm, size/XS

#1998 Update KFServing docs for 0.3
  content/en/docs/components/serving/kfserving.md
Labels: approved, lgtm, size/M

#2002 prune the current ownership file
  OWNERS
Labels: approved, lgtm, size/XS

#2009 Add Feast documentation to components
  content/en/docs/components/feature-store/OWNERS
  content/en/docs/components/feature-store/_index.md
  content/en/docs/components/feature-store/getting-started.md
  content/en/docs/components/feature-store/overview.md
  content/en/docs/reference/version-policy.md
Labels: approved, lgtm, size/L

#2012 docs: Update kfp sdk version
  content/en/docs/reference/version-policy.md
Labels: approved, lgtm, size/XS

#2013 Correct typo
  content/en/docs/pipelines/sdk/parameters.md
Labels: approved, lgtm, ok-to-test, size/XS

#2008 update to the PR Owners responsibility
  content/en/docs/about/contributing.md
Labels: approved, lgtm, size/XS

#2017 Adds note and example annotation for tfjob
  content/en/docs/components/training/tftraining.md
Labels: approved, lgtm, size/S

#2010 Fix broken links in README.md
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#2018 Add OWNERS file in AWS content folder
  content/en/docs/aws/OWNERS
  content/en/docs/images/aws/OWNERS
Labels: approved, lgtm, size/S

#2020 owners file for ibm
  content/en/docs/ibm/OWNER.ms
Labels: approved, lgtm, size/XS

#2023 Docs for blueprints
  content/en/docs/gke/deploy/delete-cli.md
  content/en/docs/gke/deploy/delete-ui.md
  content/en/docs/gke/deploy/deploy-cli.md
  content/en/docs/gke/deploy/deploy-ui.md
  content/en/docs/gke/deploy/management-setup.md
Labels: approved, lgtm, size/XL
