Repository kubeflow/website, pull requests merged in 2020-03, with the labels that each got.

#1765 Clarified that GCP basic auth is not supported and removed most references
  content/docs/gke/cloud-filestore.md
  content/docs/gke/customizing-gke.md
  content/docs/gke/deploy/deploy-cli.md
  content/docs/gke/deploy/deploy-ui.md
  content/docs/gke/deploy/reasons.md
  content/docs/gke/private-clusters.md
  content/docs/upgrading/upgrade.md
Labels: approved, lgtm, size/M

#1689 format lists and cleanup, KFP standalone
  content/docs/pipelines/installation/standalone-deployment.md
Labels: approved, doc-sprint, lgtm, ok-to-test, size/L

#1763 Fixed broken links in other-guides directory
  content/docs/other-guides/job-scheduling.md
  content/docs/other-guides/troubleshooting.md
Labels: approved, lgtm, size/XS

#1767 Fix typo in Seldon Serving Gateway Spec
  content/docs/components/serving/seldon.md
Labels: approved, lgtm, size/XS

#1760 update openshift installation doc
  content/docs/openshift/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/S

#1771 correct file path for apply
  content/docs/openshift/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/XS

#1748 Fixed broken links in gke-monitoring
  content/docs/gke/monitoring.md
Labels: approved, lgtm, size/L

#1768 Fixed broken links in pipeline sdk-overview
  content/docs/pipelines/sdk/sdk-overview.md
Labels: approved, lgtm, size/XS

#1664 Adding new section on managed certificates failure
  content/docs/gke/troubleshooting-gke.md
Labels: approved, doc-sprint, lgtm, ok-to-test, size/M

#1762 Updated notebook setup guide for Kubeflow 1.0.0 UI
  content/docs/notebooks/setup.md
Labels: approved, lgtm, size/M

#1781 Update instruction on deleting cert-manager
  content/docs/gke/private-clusters.md
Labels: approved, lgtm, size/XS

#1777 Add Seldon to stable components and fix Seldon name
  content/docs/components/serving/seldon.md
  content/docs/reference/version-policy.md
Labels: approved, lgtm, size/S

#1783 updated docs for "Authorization code grant"
  content/docs/aws/authentication.md
Labels: approved, lgtm, ok-to-test, size/XS

#1784 Updated version for GCP deployment UI
  layouts/shortcodes/kf-deployment-ui-version.html
Labels: approved, lgtm, size/XS

#1786 Update the MiniKF-on-GCP guide
  content/docs/images/minikf-deploy.png
  content/docs/images/minikf-launch.png
  content/docs/started/workstation/minikf-gcp.md
Labels: approved, lgtm, size/S

#1753 Add block storage instructions to IBM Cloud
  content/docs/ibm/install-kubeflow.md
Labels: approved, lgtm, size/M

#1770 Add end-to-end example for IBM Cloud
  content/docs/ibm/iks-e2e.md
  content/docs/images/ibm-e2e-kubeflow.png
Labels: approved, lgtm, ok-to-test, size/M

#1766 [KFP] Introduce inline visualization
  content/docs/pipelines/sdk/output-viewer.md
Labels: approved, lgtm, size/M

#1774 Cleaned up the samples and codelabs/tutorials pages
  content/docs/examples/codelabs-tutorials.md
  content/docs/examples/kubeflow-samples.md
Labels: approved, lgtm, size/M

#1787 Update IBM cloud link in Configuration quick reference
  content/docs/started/getting-started.md
Labels: approved, lgtm, size/XS

#1792 Use dedicated service principals on Azure
  content/docs/fairing/azure/_index.md
Labels: approved, lgtm, ok-to-test, size/M

#1779 document API Server flags for istio_dex config
  content/docs/started/k8s/kfctl-istio-dex.md
Labels: approved, lgtm, size/S

#1795 Updating broken link in IBM documentation
  content/docs/ibm/existing-cluster.md
Labels: approved, lgtm, ok-to-test, size/XS

#1797 Updated kfctl and config versions to v1.0.1
  layouts/shortcodes/config-file-anthos.html
  layouts/shortcodes/config-file-aws-cognito.html
  layouts/shortcodes/config-file-aws-standard.html
  layouts/shortcodes/config-file-gcp-basic-auth.html
  layouts/shortcodes/config-file-gcp-iap.html
  layouts/shortcodes/config-file-ibm.html
  layouts/shortcodes/config-file-istio-dex.html
  layouts/shortcodes/config-file-k8s-istio.html
  layouts/shortcodes/config-uri-anthos.html
  layouts/shortcodes/config-uri-aws-cognito.html
  layouts/shortcodes/config-uri-aws-standard.html
  layouts/shortcodes/config-uri-gcp-basic-auth.html
  layouts/shortcodes/config-uri-gcp-iap.html
  layouts/shortcodes/config-uri-ibm.html
  layouts/shortcodes/config-uri-istio-dex.html
  layouts/shortcodes/config-uri-k8s-istio.html
  layouts/shortcodes/kf-latest-version.html
Labels: approved, lgtm, size/M

#1791 add standaline install link, other cleanup
  content/docs/pipelines/overview/pipelines-overview.md
Labels: approved, lgtm, ok-to-test, size/M

#1802 Update invitation link to Kubeflow Slack channel
  content/docs/about/community.md
Labels: approved, lgtm, ok-to-test, size/XS

#1798 for azure end to end tutorial to work
  content/docs/azure/deploy/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/XS

#1801 Omartin2010 patch 2
  content/docs/azure/azureEndtoEnd.md
  content/docs/azure/images/finishedRunning.PNG
Labels: approved, lgtm, ok-to-test, size/S

#1804 Update AWS documentation for v1.0.1
  content/docs/aws/customizing-aws.md
  content/docs/aws/deploy/install-kubeflow.md
  content/docs/aws/iam-for-sa.md
  content/docs/images/aws/cognito-alb-domain.png
Labels: approved, lgtm, size/M

#1780 Provide tutorial for OIDC Authentication with AWS ALB on Kubeflow
  content/docs/aws/authentication-oidc.md
  content/docs/images/aws/alb-listener-rule-auth.png
  content/docs/images/aws/alb-listener-rule.png
  content/docs/images/aws/alb-login.png
  content/docs/images/aws/auth0-app-client-id-secret.png
  content/docs/images/aws/auth0-callback-url.png
  content/docs/images/aws/auth0-github-setup.png
  content/docs/images/aws/auth0-login.png
  content/docs/images/aws/auth0-welcome-page.png
  content/docs/images/aws/github-oauth-app-client-id-secret.png
  content/docs/images/aws/github-oauth-app-register-details.png
  content/docs/images/aws/github-oauth-app-register.png
Labels: approved, lgtm, ok-to-test, size/L

#1807 Update the Slack invitation link
  config.toml
  content/_index.html
  content/docs/other-guides/virtual-dev/getting-started-minikf.md
  content/docs/started/k8s/kfctl-istio-dex.md
Labels: approved, kind/bug, lgtm, size/S

#1799 Fix YAML dict syntax (use ":" instead of "=")
  content/docs/pipelines/sdk/component-development.md
Labels: approved, lgtm, ok-to-test, size/XS

#1806 Added a GSoC page
  content/docs/about/community.md
  content/docs/about/events.md
  content/docs/about/gsoc.md
Labels: approved, lgtm, size/L

#1810 fixed a typo in getting `Kubeflow Pipelines API Reference`
  content/docs/pipelines/tutorials/api-pipelines.md
Labels: approved, lgtm, ok-to-test, size/XS

#1812 Added GSoC logo, links, info about template
  content/docs/about/gsoc.md
  content/docs/images/gsoc-icon-192.png
Labels: approved, lgtm, size/S

#1813 Added namespace updates too examples
  content/docs/components/hyperparameter-tuning/hyperparameter.md
Labels: approved, lgtm, ok-to-test, size/M

#1816 Fix tf.Event link in hyperparameter-tunning
  content/docs/components/hyperparameter-tuning/experiment.md
Labels: approved, lgtm, size/XS

#1817 added enable Cloud Build API
  content/docs/gke/deploy/project-setup.md
Labels: approved, lgtm, ok-to-test, size/XS

#1818 Fixed broken links in serving component
  content/docs/components/serving/overview.md
  content/docs/components/serving/seldon.md
Labels: approved, lgtm, size/XS

#1776 Add a simple example to show how to use upload local files when creating pipeline versions
  content/docs/images/sdk-examples-snapshot-1.png
  content/docs/pipelines/sdk/sdk-overview.md
  content/docs/pipelines/tutorials/sdk-examples.md
Labels: approved, lgtm, size/M

#1815 fixed domain url spelling
  content/docs/aws/custom-domain.md
Labels: approved, lgtm, ok-to-test, size/XS

#1822 Remove onnx link for seldon in overview page
  content/docs/components/serving/overview.md
Labels: approved, lgtm, size/XS

#1824 Refactored the registration flow guide
  content/docs/components/central-dash/overview.md
  content/docs/components/central-dash/registration-flow.md
  content/docs/components/multi-tenancy/design.md
  content/docs/components/multi-tenancy/getting-started.md
  content/docs/components/multi-tenancy/overview.md
  content/docs/images/registration-flow.gif
Labels: approved, lgtm, size/L

#1829 Correct image name in docker inspect
  content/docs/pipelines/sdk/component-development.md
Labels: approved, lgtm, size/XS

#1820 TW updates to sdk-examples, and reorder KFP Samples and Tutorials
  content/docs/pipelines/tutorials/api-pipelines.md
  content/docs/pipelines/tutorials/build-pipeline.md
  content/docs/pipelines/tutorials/cloud-tutorials.md
  content/docs/pipelines/tutorials/sdk-examples.md
Labels: approved, lgtm, size/M

#1830 Simple typo fix for SDK example
  content/docs/pipelines/sdk/component-development.md
Labels: approved, lgtm, ok-to-test, size/XS

#1834 Adding StorageClass documentation to istio-dex installation
  content/docs/started/k8s/kfctl-istio-dex.md
Labels: approved, lgtm, size/L

#1823 Add Seldon Worked Example
  content/docs/components/serving/overview.md
  content/docs/components/serving/seldon.md
Labels: lgtm, size/L

#1835 Slack Channel name fixed
  content/docs/about/community.md
Labels: approved, lgtm, ok-to-test, size/XS

#1837 added microk8s links too next steps
  content/docs/other-guides/virtual-dev/getting-started-multipass.md
Labels: approved, lgtm, ok-to-test, size/XS

#1836 correct the DNS entries to have a valid root domain
  content/docs/aws/aws-e2e.md
Labels: approved, lgtm, ok-to-test, size/XS

#1838 Add more instructions and screenshots to setup authentication in AWS
  content/docs/aws/authentication-oidc.md
  content/docs/aws/authentication.md
  content/docs/aws/aws-e2e.md
  content/docs/images/aws/cognito-custom-domain-callback.png
  content/docs/images/aws/cognito-custom-domain.png
  content/docs/images/aws/cognito-domain-error.jpg
  content/docs/images/aws/cognito-domain.png
  content/docs/images/aws/cognito-invalid-subdomain.png
  content/docs/images/aws/godaddy-ns-for-subdomain.png
  content/docs/images/aws/route53-a-record-auth.png
  content/docs/images/aws/route53-a-record-platform.png
  content/docs/images/aws/route53-a-record.png
  content/docs/images/aws/route53-hosted-zone.png
  content/docs/images/aws/route53-record-sets.png
Labels: approved, lgtm, size/L

#1842 Updating cluster config for IBM Cloud
  content/docs/ibm/install-kubeflow.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1841 Update kfctl-istio-dex.md
  content/docs/started/k8s/kfctl-istio-dex.md
Labels: approved, lgtm, ok-to-test, size/XS

#1843 Add link to MPI Operator blog post
  content/docs/components/training/mpi.md
Labels: approved, lgtm, size/XS

#1844 Add @terrytangyuan to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1839 Add documentation for the Katib config and Katib components env variables
  content/docs/components/hyperparameter-tuning/env-variables.md
  content/docs/components/hyperparameter-tuning/experiment.md
  content/docs/components/hyperparameter-tuning/hyperparameter.md
  content/docs/components/hyperparameter-tuning/katib-config.md
  content/docs/components/hyperparameter-tuning/overview.md
Labels: approved, lgtm, size/L

#1846 Update TensorRT Inference Server naming to Triton
  content/_index.html
  content/_redirects
  content/docs/components/serving/kfserving.md
  content/docs/components/serving/overview.md
  content/docs/components/serving/tritoninferenceserver.md
  content/docs/components/serving/trtinferenceserver.md
  content/serving.svg
Labels: approved, lgtm, ok-to-test, size/M

#1845 Thinned out the website OWNERS file
  OWNERS
Labels: approved, lgtm, size/M

#1848 Fix service account name in IRSA for AWS
  content/docs/aws/iam-for-sa.md
Labels: approved, lgtm, size/S

#1743 Minikube tutorial
  content/docs/started/workstation/minikube-linux.md
Labels: approved, lgtm, size/L

#1850 Added gcloud commands for cluster access
  content/docs/components/multi-tenancy/getting-started.md
Labels: approved, lgtm, size/M

#1851 Added hints and tips section to minikube tutorial
  content/docs/started/workstation/minikube-linux.md
Labels: approved, lgtm, size/S
