Repository kubeflow/website, pull requests merged in 2020-09, with the labels that each got.

#2170 doc(gcp): fix broken format in management cluster setup
  content/en/docs/gke/deploy/management-setup.md
Labels: approved, lgtm, size/XS

#2176 Add Ark-kun and numerology to Pipelines docs owners
  content/en/docs/pipelines/OWNERS
Labels: approved, lgtm, size/XS

#2175 doc(kfp): update multi-user isolation doc title and supported platforms
  content/en/docs/pipelines/multi-user.md
Labels: approved, lgtm, size/XS

#2157 correct spelling error
  content/en/docs/aws/deploy/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/XS

#2168 KFP - Reusable components - Added information regarding outputting directories
  content/en/docs/pipelines/sdk/component-development.md
Labels: approved, lgtm, size/XS

#2148 Add RFMVasconcelos to reviewers - see #2104
  OWNERS
Labels: approved, lgtm, size/XS

#2179 Kubeflow Getting Started: add approvers and reviewers to OWNERS
  content/en/docs/started/OWNERS
Labels: approved, lgtm, size/XS

#2019 Refine Microk8s and Multipass docs
  content/en/docs/started/workstation/getting-started-multipass.md
Labels: approved, lgtm, ok-to-test, size/M

#2183 Fix TLS certificate usage in IBM cloud Kubernetes
  content/en/docs/ibm/deploy/authentication.md
Labels: approved, lgtm, size/S

#2184 localcluster-deployment.md - KFP platform-agnostic-pns env hasn't been released
  content/en/docs/pipelines/installation/localcluster-deployment.md
Labels: approved, lgtm, size/XS

#2174 Clean up 'out of date' banner for few more KFP pages
  content/en/docs/pipelines/sdk/gcp.md
  content/en/docs/pipelines/sdk/install-sdk.md
  content/en/docs/pipelines/sdk/parameters.md
  content/en/docs/pipelines/sdk/static-type-checking.md
Labels: approved, lgtm, size/L

#2189 Add @alfsuse to the OWNERS file
  content/en/docs/pipelines/OWNERS
Labels: approved, lgtm, size/XS

#2167 Update Pipeline SDK overview page
  content/en/docs/pipelines/sdk/sdk-overview.md
Labels: approved, lgtm, size/M

#2193 doc(kfp): Bump KFP to 1.0.1
  content/en/docs/pipelines/installation/localcluster-deployment.md
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, lgtm, size/XS

#2191 Adding to Kubeflow support providers
  content/en/docs/other-guides/support.md
Labels: approved, lgtm, size/S

#2194 Add a new OWNERS file for KF Kubernetes Getting Started
  content/en/docs/started/k8s/OWNERS
Labels: approved, lgtm, size/XS

#2186 Update Kubernetes v1.16 compatibility status in the Overview of Kubeflow deployment on a k8s cluster guide
  content/en/docs/started/k8s/overview.md
Labels: approved, lgtm, size/XS

#2192 Kubeflow docs: create an OWNERS file for other guides
  content/en/docs/other-guides/OWNERS
Labels: approved, lgtm, size/XS

#2169 Adding in instructions for how to install Kustomize 3.2.1 on a Linux box
  content/en/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, ok-to-test, size/S

#2203 Quick fixes to Microk8s page
  content/en/docs/started/workstation/getting-started-multipass.md
Labels: approved, lgtm, size/XS

#2190 Update the docs for private GKE.
  content/en/docs/gke/anthos.md
  content/en/docs/gke/private-clusters.md
Labels: approved, lgtm, size/L

#2163 Parameterize default storageclass for ibm cloud
  content/en/docs/ibm/deploy/install-kubeflow.md
Labels: approved, lgtm, size/M

#2204 Update KFP latest version and stability level
  content/en/docs/reference/version-policy.md
Labels: approved, lgtm, size/S

#2197 Update Linux getting-started guide
  content/en/docs/started/workstation/getting-started-linux.md
Labels: approved, lgtm, ok-to-test, size/M

#2215 Create OWNERS for Kubeflow Getting Started Workstation
  content/en/docs/started/workstation/OWNERS
Labels: approved, lgtm, size/XS

#2214 Correct metadata inaccuracy in the output viewer docs
  content/en/docs/pipelines/sdk/output-viewer.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#2185 Updated management cluster instructions
  content/en/docs/gke/deploy/management-setup.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#2217 Create OWNERS file for sdk section
  content/en/docs/pipelines/sdk/OWNERS.md
Labels: approved, lgtm, size/XS

#2153 Link to more info about the MANAGED_PROJECT
  content/en/docs/gke/deploy/management-setup.md
Labels: approved, lgtm, ok-to-test, size/XS

#2213 Correct requirement inaccuracy in the metrics documentation
  content/en/docs/pipelines/sdk/pipelines-metrics.md
Labels: approved, lgtm, ok-to-test, size/S
