Repository kubeflow/website, pull requests merged in 2020-12, with the labels that each got.

#2383 Install kubectl using gcloud components
  content/en/docs/gke/deploy/management-setup.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2386 Remove -f argument from gcloud beta anthos apply
  content/en/docs/gke/deploy/management-setup.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2376 docs(kfp): add local option to KFP installation overview
  content/en/docs/pipelines/installation/overview.md
Labels: approved, cla: yes, lgtm, size/XS

#2390 fix(doc): update docs that still refer to KFP latest SDK reference. Fixes kubelow/pipelines#4685
  content/en/docs/gke/pipelines/authentication-pipelines.md
  content/en/docs/ibm/using-icr.md
  content/en/docs/pipelines/multi-user.md
  content/en/docs/pipelines/reference/sdk.md
  content/en/docs/pipelines/sdk/enviroment_variables.md
  content/en/docs/pipelines/sdk/install-sdk.md
  content/en/docs/pipelines/sdk/manipulate-resources.md
  content/en/docs/pipelines/sdk/parameters.md
  content/en/docs/pipelines/sdk/python-function-components.ipynb
  content/en/docs/pipelines/sdk/python-function-components.md
  content/en/docs/pipelines/sdk/sdk-overview.md
Labels: approved, cla: yes, lgtm, size/L

#2389 [AWS] Fix Cognito Pipeline-Notebook Authentication
  content/en/docs/aws/pipeline.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2372 docs(gcp): Kubeflow cluster upgrade instructions and revamp of env vars
  content/en/docs/gke/customizing-gke.md
  content/en/docs/gke/deploy/delete-cli.md
  content/en/docs/gke/deploy/deploy-cli.md
  content/en/docs/gke/deploy/deploy-ui.md
  content/en/docs/gke/deploy/management-setup.md
  content/en/docs/gke/deploy/upgrade.md
  content/en/docs/gke/pipelines/upgrade.md
Labels: approved, cla: yes, lgtm, size/XL

#2391 Update AWS documentation to v1.2
  layouts/shortcodes/config-file-aws-cognito.html
  layouts/shortcodes/config-file-aws-standard.html
  layouts/shortcodes/config-uri-aws-cognito.html
  layouts/shortcodes/config-uri-aws-standard.html
  layouts/shortcodes/kfctl-aws.html
Labels: approved, cla: yes, lgtm, size/S

#2286 Add delete notebooks section to troubleshoot
  content/en/docs/notebooks/troubleshoot.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2392 Update layouts folder OWNERS file
  content/en/docs/aws/authentication-oidc.md
  content/en/docs/aws/authentication.md
  content/en/docs/aws/aws-e2e.md
  content/en/docs/aws/customizing-aws.md
  content/en/docs/aws/deploy/install-kubeflow.md
  content/en/docs/aws/iam-for-sa.md
  content/en/docs/aws/pipeline.md
  layouts/shortcodes/aws/OWNERS
  layouts/shortcodes/aws/config-file-aws-cognito.html
  layouts/shortcodes/aws/config-file-aws-standard.html
  layouts/shortcodes/aws/config-uri-aws-cognito.html
  layouts/shortcodes/aws/config-uri-aws-standard.html
  layouts/shortcodes/aws/kfctl-aws.html
Labels: approved, cla: yes, lgtm, size/M

#2318 Pipelines - Adds documentation on passing data between components
  content/en/docs/pipelines/sdk/python-function-components.ipynb
  content/en/docs/pipelines/sdk/python-function-components.md
Labels: approved, cla: yes, lgtm, size/XL

#2358 Update contributing.md
  content/en/docs/about/contributing.md
Labels: approved, cla: yes, lgtm, size/XS

#2362 Component development doc fixes
  content/en/docs/pipelines/sdk/component-development.md
Labels: approved, lgtm, ok-to-test, size/M

#2404 add tommy as an approver for website docs for IBM
  content/en/docs/ibm/deploy/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2352 [IBM] Add some common troubleshooting on the IBM deployement for non-k8s users
  content/en/docs/ibm/deploy/install-kubeflow.md
Labels: approved, cla: yes, lgtm, size/M

#2394 Fixed Documentation regarding installation of kfctl on windows using WSL
  content/en/docs/aws/deploy/install-kubeflow.md
  content/en/docs/azure/deploy/install-kubeflow.md
  content/en/docs/ibm/deploy/install-kubeflow.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#1988 Mention the need for zones with NVIDIA Tesla K80 Accelerators for the default GCP configuration
  content/en/docs/gke/deploy/deploy-cli.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2414 docs(kfp): fix namespaced deploy instructions for KFP standalone
  content/en/docs/pipelines/installation/standalone-deployment.md
Labels: approved, cla: yes, lgtm, size/XS

#2407 Update latest version for KFP
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, cla: yes, lgtm, size/XS

#2411 [IBM] Fix formatting in HTTPS doc
  content/en/docs/ibm/deploy/authentication.md
Labels: approved, cla: yes, lgtm, size/M

#2405 [AWS] Update AWS Notebook Image to v1.2.0
  content/en/docs/aws/notebook-server.md
Labels: approved, cla: yes, lgtm, size/XS

#2396 docs(gcp): unify terminology for CNRM as Config Connector
  content/en/docs/gke/deploy/delete-cli.md
  content/en/docs/gke/deploy/deploy-cli.md
  content/en/docs/gke/deploy/reasons.md
  content/en/docs/gke/private-clusters.md
Labels: approved, cla: yes, lgtm, size/M

#2413 Update Azure Deployment Docs for KF 1.2
  content/en/docs/azure/authentication-oidc.md
  content/en/docs/azure/deploy/install-kubeflow.md
  layouts/shortcodes/azure/config-uri-azure-oidc.html
  layouts/shortcodes/azure/config-uri-azure.html
Labels: approved, cla: yes, lgtm, size/S

#2412 Add OWNERS for Getting Started Section
  content/en/docs/started/cloud/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2416 doc(kfp): Bump KFP version to 1.2.0
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, cla: yes, lgtm, size/XS

#2418 Update project-setup.md solve installation issues
  content/en/docs/gke/deploy/project-setup.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2425 Redirect blog to the new location instead of Medium
  content/en/_redirects
Labels: approved, cla: yes, lgtm, size/XS

#2421 Update management-setup.md in Management cluster setup
  content/en/docs/gke/deploy/management-setup.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
