Repository kubeflow/website, pull requests merged in 2020-01, with the labels that each got.

#1496 Typo fix in 'customizing_gke.md'
  content/docs/gke/customizing-gke.md
Labels: approved, lgtm, ok-to-test, size/XS

#1470 Updated AWS Troubleshooting guide to add tag for public subnets
  content/docs/aws/troubleshooting-aws.md
Labels: approved, lgtm, ok-to-test, size/XS

#1494 Created GCP Pipelines section and moved GCP-specific pipelines upgrade instructions
  content/_redirects
  content/docs/gke/pipelines/_index.md
  content/docs/gke/pipelines/authentication-pipelines.md
  content/docs/gke/pipelines/pipelines-tutorial.md
  content/docs/gke/pipelines/upgrade.md
  content/docs/pipelines/installation/standalone-deployment.md
  content/docs/pipelines/upgrade.md
Labels: approved, lgtm, size/L

#1497 Add yaml info in KFServing install #1464
  content/docs/components/serving/kfserving.md
Labels: approved, lgtm, size/XS

#1480 Expanded and clarified the Katib docs
  content/docs/components/hyperparameter-tuning/experiment.md
  content/docs/components/hyperparameter-tuning/hyperparameter.md
  content/docs/components/hyperparameter-tuning/overview.md
  content/docs/images/katib-deploy-form.png
  content/docs/images/katib-deploy-yaml.png
  content/docs/images/katib-experiments.png
  content/docs/images/katib-home.png
  content/docs/images/katib-menu.png
  content/docs/images/katib-neural-architecture-search-ui.png
  content/docs/images/katib-random-example-graph.png
  content/docs/images/katib-random-example-trials.png
Labels: approved, lgtm, size/XL

#1498 Moved GCP-specific pipelines SDK docs to GCP pipelines section
  content/_redirects
  content/docs/gke/pipelines/enable-gpu-and-tpu.md
  content/docs/gke/pipelines/preemptible.md
  content/docs/pipelines/sdk/gcp.md
Labels: approved, lgtm, size/S

#1499 update kfp release version
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, lgtm, size/XS

#1506 Update katib metrics colllector doc
  content/docs/components/hyperparameter-tuning/experiment.md
Labels: approved, lgtm, size/S

#1509 Fix code snippets for python-based-visualizations docs
  content/docs/pipelines/sdk/python-based-visualizations.md
Labels: approved, lgtm, size/M

#1512 Upped Kubeflow version to v0.7.1
  layouts/shortcodes/kf-latest-version.html
Labels: approved, lgtm, size/XS

#1514 Sync up with katib component rename
  content/docs/other-guides/troubleshooting.md
  content/docs/reference/images.md
Labels: approved, lgtm, size/XS

#1516 Remove chainer docs
  content/docs/components/training/chainer.md
Labels: approved, lgtm, ok-to-test, size/L

#1515 Update Metadata installation from Manifest
  content/docs/components/misc/metadata.md
Labels: approved, lgtm, size/XS

#1519 Update Microk8s install to specify K8s version
  content/docs/started/workstation/getting-started-linux.md
Labels: approved, lgtm, ok-to-test, size/XS

#1525 Fixed typo
  content/docs/pipelines/installation/_index.md
Labels: approved, lgtm, ok-to-test, size/XS

#1526 update formatting of code blocks
  content/docs/pipelines/sdk/python-based-visualizations.md
Labels: approved, lgtm, ok-to-test, size/M

#1517 Update tfbatchpredict.md
  content/docs/components/serving/tfbatchpredict.md
Labels: approved, lgtm, ok-to-test, size/L

#1524 Removed the Gitops guide
  content/_redirects
  content/docs/other-guides/gitops-for-kubeflow.md
Labels: approved, lgtm, size/L

#1523 Deleted the page about Istio for TF Serving
  content/_index.html
  content/_redirects
  content/docs/components/serving/istio.md
  content/docs/components/serving/overview.md
Labels: approved, lgtm, size/L

#1424 Updated the Pipelines API reference docs
  content/docs/pipelines/reference/api/kubeflow-pipeline-api-spec.html
Labels: approved, lgtm, ok-to-test, size/XXL

#1522 Clarified and expanded the Slack info
  content/docs/about/community.md
Labels: approved, lgtm, size/M

#1527 Added the 2020 doc sprint to the events page
  content/docs/about/events.md
Labels: approved, lgtm, size/S

#1531 Added Katib API reference to the website docs
  content/docs/reference/katib/_index.md
  content/docs/reference/katib/v1alpha3/_index.md
  content/docs/reference/katib/v1alpha3/katib.md
Labels: approved, lgtm, size/XL

#1529 update mxjob docs
  content/docs/components/training/mxnet.md
Labels: approved, lgtm, ok-to-test, size/S

#1518 Update run.md
  content/docs/pipelines/overview/concepts/run.md
Labels: approved, lgtm, ok-to-test, size/XS

#1535 Added logic to create a banner on archived doc sets
  config.toml
  layouts/docs/baseof.html
  layouts/partials/version-banner.html
Labels: approved, lgtm, size/M

#1547 Added alpha banner to GKE private cluster page
  content/docs/gke/private-clusters.md
Labels: approved, lgtm, size/S

#1538 [CentralDashboard] Docs added for central-dashboard
  content/docs/components/central-dash/_index.md
  content/docs/components/central-dash/overview.md
  content/docs/components/central-dash/registration-flow.md
  content/docs/images/registration-flow.gif
Labels: approved, area/centraldashboard, area/docs, area/front-end, lgtm, priority/p1, size/M

#1550 Kubeflow v0.6 docs: Added logic to create a banner on archived doc sets (#1535)
  config.toml
  layouts/docs/baseof.html
  layouts/partials/version-banner.html
Labels: approved, lgtm, size/M

#1545 [Pipelines] Update deployment guide for KFP 0.2.0
  content/docs/pipelines/installation/standalone-deployment.md
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, lgtm, size/S

#1556 Kubeflow v0.5 docs: Added logic to create a banner on archived doc sets (#1535)
  config.toml
  layouts/docs/baseof.html
  layouts/partials/version-banner.html
Labels: approved, lgtm

#1557 v0.5 branch: Added explicit styling for version banner
  layouts/partials/version-banner.html
Labels: approved, lgtm

#1558 Kubeflow v0.4 docs: Added logic to create a banner on archived doc sets (#1535)
  config.toml
  layouts/docs/baseof.html
  layouts/partials/version-banner.html
Labels: approved, lgtm

#1559 Kubeflow v0.3 docs: Added logic to create a banner on archived doc sets (#1535)
  config.toml
  themes/kf/layouts/docs/single.html
  themes/kf/layouts/partials/version-banner.html
Labels: approved, lgtm, size/M

#1560 Kubeflow v0.2 docs: Added logic to create a banner on archived doc sets (#1535)
  config.toml
  themes/kf/layouts/docs/single.html
  themes/kf/layouts/partials/version-banner.html
Labels: approved, lgtm, size/M

#1561 Created v0.7 branch of docs and set archived_version param to true
  config.toml
Labels: approved, lgtm, size/XS

#1562 Added v0.7 to version menu on main site
  config.toml
Labels: approved, lgtm, size/XS

#1555 Deleted the PyTorch Serving page
  content/_index.html
  content/_redirects
  content/docs/components/serving/overview.md
  content/docs/components/serving/pytorchserving.md
Labels: approved, lgtm, size/M

#1565 typo fix
  content/docs/pipelines/sdk/python-based-visualizations.md
Labels: approved, lgtm, size/XS

#1544 Update sdk-overview.md
  content/docs/pipelines/sdk/sdk-overview.md
Labels: approved, lgtm, ok-to-test, size/S

#1469 Update getting-started-multipass.md
  content/docs/other-guides/virtual-dev/getting-started-multipass.md
Labels: approved, lgtm, ok-to-test, size/L

#1552 Update install-sdk.md
  content/docs/pipelines/sdk/install-sdk.md
Labels: approved, lgtm, ok-to-test, size/S

#1569 Merged content of accessing-uis page with new central dash page
  content/_redirects
  content/docs/components/central-dash/_index.md
  content/docs/components/central-dash/overview.md
  content/docs/components/hyperparameter-tuning/hyperparameter.md
  content/docs/components/misc/metadata.md
  content/docs/images/central-ui.png
  content/docs/notebooks/setup.md
  content/docs/other-guides/accessing-uis.md
  content/docs/started/kubeflow-overview.md
Labels: approved, lgtm, size/L

#1572 Update getting-started-linux
  content/docs/started/workstation/getting-started-linux.md
Labels: approved, lgtm, ok-to-test, size/XS

#1520 Added a support page for Kubeflow v1.0.0
  content/docs/other-guides/support.md
  content/docs/other-guides/troubleshooting.md
Labels: approved, lgtm, size/L
