Repository kubeflow/website, pull requests merged in 2020-05, with the labels that each got.

#1937 Fix URL for tutorial to deploy Kubeflow
  content/en/docs/components/training/tftraining.md
Labels: approved, lgtm, ok-to-test, size/XS

#1938 Fixed broken url in training/mpi page
  content/en/docs/components/training/mpi.md
Labels: approved, lgtm, size/XS

#1935 Update website approvers
  OWNERS
Labels: approved, lgtm, size/XS

#1939 Fix hyperlinks
  content/en/docs/components/training/tftraining.md
Labels: approved, lgtm, ok-to-test, size/XS

#1934 Update Amazon RDS installation docs
  content/en/docs/aws/rds.md
  content/en/docs/aws/rds.yaml
  content/en/docs/aws/troubleshooting-aws.md
  content/en/docs/images/aws/cloudformation-launch-stack.png
  content/en/docs/images/aws/cloudformation-rds-output.png
  content/en/docs/images/aws/external-mysql-rds.png
Labels: approved, lgtm, ok-to-test, size/L

#1942 release KFP 0.5.1
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, lgtm, size/XS

#1943 Seldon k8s version requirements
  content/en/docs/components/serving/seldon.md
Labels: approved, lgtm, size/XS

#1944 Fix outdated path to MPI Operator's installation yaml
  content/en/docs/components/training/mpi.md
Labels: approved, lgtm, size/XS

#1928 add a pointer to our example script of creating runs using pipeline
  content/en/docs/pipelines/tutorials/sdk-examples.md
Labels: approved, lgtm, size/XS

#1951 Update IBM Cloud deployment instructions
  content/en/docs/ibm/existing-cluster.md
  content/en/docs/ibm/install-kubeflow.md
Labels: approved, lgtm, ok-to-test, size/M

#1957 Update AWS E2E Example Docs to use Hugo Shortcodes
  content/en/docs/aws/aws-e2e.md
Labels: approved, lgtm, ok-to-test, size/XS

#1961 update bash command to use exported namespace
  layouts/shortcodes/code-webui-port-forward.html
Labels: approved, lgtm, ok-to-test, size/XS

#1963 fix code-webui-port-forward.html
  layouts/shortcodes/code-webui-port-forward.html
Labels: approved, lgtm, ok-to-test, size/XS

#1965 Update install-kubeflow.md
  content/en/docs/azure/deploy/install-kubeflow.md
Labels: size/S

#1967 Update python-based-visualizations.md
  content/en/docs/pipelines/sdk/python-based-visualizations.md
Labels: approved, lgtm, ok-to-test, size/S

#1964 Update output-viewer.md
  content/en/docs/pipelines/sdk/output-viewer.md
Labels: approved, lgtm, ok-to-test, size/XS

#1971 Make KFP install command zsh compatible
  content/en/docs/pipelines/installation/standalone-deployment.md
Labels: approved, lgtm, size/S

#1970 OWNERS for pipelines folder
  content/en/docs/pipelines/OWNERS
Labels: approved, lgtm, size/XS
