Repository kubeflow/website, pull requests merged in 2020-11, with the labels that each got.

#2328 Add reference to authenticate Python SDK with Dex
  content/en/docs/aws/pipeline.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2311 Update GCP doc - setting a custom domain
  content/en/docs/gke/custom-domain.md
Labels: approved, lgtm, ok-to-test, size/M

#2319 Add Notebook WG leads to OWNERS
  content/en/docs/notebooks/OWNERS
Labels: approved, lgtm, size/XS

#2334 typo - using your own domain section
  content/en/docs/gke/custom-domain.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2323 Update Azure OIDC guidance to verify statefulset and also lint the yaml to be the same as the autherservice
  content/en/docs/azure/authentication-oidc.md
Labels: approved, lgtm, ok-to-test, size/M

#2327 Uses AppID for multi-user installation on IKS
  content/en/docs/ibm/deploy/authentication.md
  content/en/docs/ibm/deploy/install-kubeflow.md
Labels: approved, lgtm, size/L

#2339 Fixing Fairing broken links
  content/en/docs/gke/deploy/project-setup.md
  content/en/docs/notebooks/setup.md
  content/en/docs/reference/version-policy.md
  content/en/docs/started/kubeflow-overview.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2332 New trial template design for Katib
  content/en/docs/components/hyperparameter-tuning/env-variables.md
  content/en/docs/components/hyperparameter-tuning/experiment.md
  content/en/docs/components/hyperparameter-tuning/hyperparameter.md
  content/en/docs/components/hyperparameter-tuning/katib-config.md
  content/en/docs/components/hyperparameter-tuning/overview.md
  content/en/docs/components/hyperparameter-tuning/trial-template.md
Labels: approved, lgtm, size/L

#2341 Document the Kubeflow Pipelines SDK for Tekton
  content/en/docs/pipelines/sdk/install-sdk.md
  content/en/docs/pipelines/sdk/pipelines-with-tekton.md
  content/en/docs/pipelines/sdk/sdk-overview.md
Labels: approved, lgtm, size/M

#2343 Update the IBM Kubeflow deployment with the new release
  content/en/docs/ibm/deploy/install-kubeflow.md
  content/en/docs/images/ibm/appid-redirect-settings.png
Labels: approved, lgtm, size/L

#2304 Adding docs for Azure MySQL
  content/en/docs/azure/azureMySQL.md
Labels: approved, lgtm, ok-to-test, size/L

#2345 Update blueprint to package
  content/en/docs/gke/pipelines/upgrade.md
Labels: approved, lgtm, ok-to-test, size/XS

#2342 update kfserving website for 0.4.1 release
  content/en/docs/components/serving/kfserving.md
Labels: approved, lgtm, size/XS

#2347 Update IBM docs with better KFP instructions
  content/en/docs/ibm/deploy/install-kubeflow.md
  content/en/docs/ibm/iks-e2e.md
  content/en/docs/ibm/pipelines.md
Labels: approved, lgtm, size/L

#2350 rearrange IKS deployment instructions for Kubeflow
  content/en/docs/ibm/OWNERS
  content/en/docs/ibm/create-cluster.md
  content/en/docs/ibm/deploy/_index.md
  content/en/docs/ibm/existing-cluster.md
  content/en/docs/ibm/iks-e2e.md
  content/en/docs/ibm/kfp-tekton.png
  content/en/docs/ibm/pipelines.md
  content/en/docs/ibm/using-icr.md
Labels: approved, lgtm, size/M

#2351 need to go a level up for diagram
  content/en/docs/ibm/pipelines.md
Labels: approved, lgtm, size/XS

#2346 Update Broken links in KFServing documentation
  content/en/docs/components/serving/kfserving.md
Labels: approved, lgtm, ok-to-test, size/S

#2315 Disable ephemeral storage in Katib Config
  content/en/docs/components/katib/katib-config.md
Labels: approved, lgtm, size/M

#2316 Add Katib metric strategies info
  content/en/docs/components/katib/experiment.md
Labels: approved, lgtm, size/M

#2320 Update Istio sidecar annotation information for the Katib experiments
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/hyperparameter.md
Labels: approved, lgtm, size/M

#2321 Default values for Katib Trials count
  content/en/docs/components/katib/experiment.md
Labels: approved, lgtm, size/S

#2336 Add Katib early stopping documentation
  content/en/docs/components/katib/early-stopping.md
  content/en/docs/components/katib/env-variables.md
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/katib-config.md
  content/en/docs/components/katib/overview.md
  content/en/docs/components/katib/trial-template.md
  content/en/docs/images/katib/katib-early-stopping-parameter.png
  content/en/docs/images/katib/katib-early-stopping-trial-info.png
  content/en/docs/images/katib/katib-early-stopping-trials.png
Labels: approved, lgtm, size/L

#2348 Update codelabs-tutorials.md
  content/en/docs/examples/codelabs-tutorials.md
Labels: approved, lgtm, size/XS

#2324 Add resume policy instructions for Katib experiments
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/katib-config.md
  content/en/docs/components/katib/resume-experiment.md
  content/en/docs/components/katib/trial-template.md
Labels: approved, lgtm, size/L

#2354 Move images under Katib directory
  content/en/docs/components/katib/early-stopping.md
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/images/deploy-parameters.png
  content/en/docs/components/katib/images/deploy-yaml.png
  content/en/docs/components/katib/images/early-stopping-parameter.png
  content/en/docs/components/katib/images/early-stopping-trial-info.png
  content/en/docs/components/katib/images/early-stopping-trials.png
  content/en/docs/components/katib/images/experiment-list.png
  content/en/docs/components/katib/images/home-page.png
  content/en/docs/components/katib/images/menu.png
  content/en/docs/components/katib/images/nas-parameters.png
  content/en/docs/components/katib/images/random-example-graph.png
  content/en/docs/components/katib/images/random-example-trial-info.png
  content/en/docs/components/katib/images/random-example-trials.png
  content/en/docs/components/katib/overview.md
Labels: approved, lgtm, size/M

#2355 Update links to Feast documentation
  content/en/docs/components/feature-store/getting-started.md
Labels: approved, lgtm, size/S

#2356 Add the dynamic volume provisioner requirement to the K8s cluster KF doc overview; minor linting
  content/en/docs/started/k8s/overview.md
Labels: approved, lgtm, size/S

#2357 Add AWS Compatibility Matrix between EKS and Kubeflow versions
  content/en/docs/aws/deploy/install-kubeflow.md
Labels: approved, lgtm, size/M

#2147 Add kubeflow-behind-proxy.md - see issue #2137
  content/en/docs/other-guides/kubeflow-behind-proxy.md
Labels: approved, lgtm, size/M

#2173 Refer to the section where the deployment steps are described
  content/en/docs/gke/deploy/deploy-cli.md
Labels: approved, lgtm, ok-to-test, size/XS

#2360 Cherrypick of "Adding docs for Azure MySQL (#2304)"
  content/en/docs/azure/azureMySQL.md
Labels: approved, lgtm, ok-to-test, size/L

#2361 Adding berndverst as Azure Docs approver
  content/en/docs/azure/OWNERS
Labels: approved, lgtm, size/XS

#2338 Adding index page for Azure Machine Learning Component
  content/en/docs/azure/machinelearningcomponent.md
Labels: approved, lgtm, ok-to-test, size/M

#2171 KFP - Updated the documentation regarding metrics
  content/en/docs/pipelines/sdk/pipelines-metrics.md
Labels: approved, lgtm, size/L

#2364 Fix typo
  content/en/docs/started/workstation/getting-started-multipass.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2365 Update website versioning for v1.2
  config.toml
  layouts/shortcodes/kf-latest-version.html
Labels: approved, cla: yes, lgtm, size/S

#2370 docs(gcp): management cluster install/upgrade instruction for KF 1.2
  content/en/docs/gke/deploy/delete-cli.md
  content/en/docs/gke/deploy/management-setup.md
  content/en/docs/gke/deploy/monitor-iap-setup.md
  content/en/docs/gke/deploy/upgrade.md
Labels: approved, cla: yes, lgtm, size/L

#2363 cherrypick of "KFP - Updated the documentation regarding metrics #2171"
  content/en/docs/pipelines/sdk/pipelines-metrics.md
Labels: approved, cla: yes, lgtm, size/L

#2374 docs(kfp): update KFP status to stable
  content/en/docs/pipelines/overview/pipelines-overview.md
  content/en/docs/pipelines/pipelines-quickstart.md
  content/en/docs/pipelines/sdk/sdk-overview.md
Labels: approved, cla: yes, lgtm, size/XS

#2375 docs(kfp): update 1.2.0 corresponding KFP version
  content/en/docs/pipelines/installation/overview.md
Labels: approved, cla: yes, lgtm, size/XS

#2368 Add documentation for installing MiniKF on AWS
  content/en/docs/images/minikf-aws/OWNERS
  content/en/docs/images/minikf-aws/minikf-aws-accept-terms.png
  content/en/docs/images/minikf-aws/minikf-aws-configuration-details.png
  content/en/docs/images/minikf-aws/minikf-aws-configuration.png
  content/en/docs/images/minikf-aws/minikf-aws-connect.png
  content/en/docs/images/minikf-aws/minikf-aws-continue-configuration.png
  content/en/docs/images/minikf-aws/minikf-aws-ec2-connect.png
  content/en/docs/images/minikf-aws/minikf-aws-ec2-console.png
  content/en/docs/images/minikf-aws/minikf-aws-instance-type.png
  content/en/docs/images/minikf-aws/minikf-aws-page.png
  content/en/docs/images/minikf-aws/minikf-aws-progress.png
  content/en/docs/images/minikf-aws/minikf-aws-provisioning-completed.png
  content/en/docs/images/minikf-aws/minikf-aws-security-group.png
  content/en/docs/images/minikf-aws/minikf-aws-security-settings-key-pair.png
  content/en/docs/images/minikf-aws/minikf-aws-security-settings-subnet.png
  content/en/docs/images/minikf-aws/minikf-aws-security-settings-vpc.png
  content/en/docs/images/minikf-aws/minikf-aws-successful-deployment.png
  content/en/docs/images/minikf-aws/minikf-aws-view-progress.png
  content/en/docs/started/getting-started.md
  content/en/docs/started/workstation/minikf-aws.md
Labels: approved, cla: yes, lgtm, size/L

#2373 Adding a Note in contributing.md file for new members.
  content/en/docs/about/contributing.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2377 Fix few broken links
  content/en/docs/aws/customizing-aws.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S
