Repository kubeflow/website, pull requests merged in 2021-03, with the labels that each got.

#2524 Azure: Update single-user deployment
  content/en/docs/azure/deploy/install-kubeflow.md
Labels: approved, cla: yes, lgtm, size/M

#2448 Updates the wording of the yq v3 instructions
  content/en/docs/gke/deploy/deploy-cli.md
  content/en/docs/gke/deploy/management-setup.md
Labels: approved, cla: yes, lgtm, size/S

#2526 Small update to pipelines redirects
  content/en/_redirects
Labels: approved, cla: yes, lgtm, size/XS

#2525 Remove outdated banners, move GCP instructions to GKE folder
  content/en/_redirects
  content/en/docs/components/notebooks/custom-notebook.md
  content/en/docs/components/notebooks/setup.md
  content/en/docs/components/notebooks/submit-kubernetes.md
  content/en/docs/components/notebooks/troubleshoot.md
  content/en/docs/components/notebooks/why-use-jupyter-notebook.md
  content/en/docs/gke/submit-docker-image.md
Labels: approved, cla: yes, lgtm, size/S

#2527 docs(gke): Delete submit-docker-image.md
  content/en/docs/gke/submit-docker-image.md
Labels: approved, cla: yes, lgtm, size/M

#2528 Remove unnecessary redirect
  content/en/_redirects
Labels: approved, cla: yes, lgtm, size/XS

#2518 Update IBM storage config
  content/en/docs/ibm/create-cluster.md
  content/en/docs/ibm/deploy/install-kubeflow-on-iks.md
Labels: approved, cla: yes, lgtm, size/M

#2534 Updated Join Slack link with a fresh link
  content/en/docs/about/community.md
Labels: approved, cla: yes, lgtm, size/XS

#2531 Add waitAllProcesses flag to Katib config
  content/en/docs/components/katib/katib-config.md
Labels: approved, cla: yes, lgtm, size/XS

#2532 Modify Katib links for cert-generator and pytorch-mnist image
  content/en/docs/reference/images.md
Labels: approved, cla: yes, lgtm, size/XS

#2540 Modify links for the Katib manifests
  content/en/docs/components/katib/env-variables.md
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/katib-config.md
  content/en/docs/components/katib/trial-template.md
Labels: approved, cla: yes, lgtm, size/M

#2512 fix(docs): updated the quickstart for kubeflow pipelines. Fixes 4617 in (kubeflow/pipelines)
  content/en/docs/components/pipelines/pipelines-quickstart.md
  content/en/docs/images/click-pipeline-sample.png
  content/en/docs/images/click-xgboost-sample.png
  content/en/docs/images/pipelines-basic-run.png
  content/en/docs/images/pipelines-experiments-dashboard.png
  content/en/docs/images/pipelines-start-experiment.png
  content/en/docs/images/pipelines-start-run.png
  content/en/docs/images/pipelines-start-xgboost-run.png
  content/en/docs/images/pipelines-ui.png
  content/en/docs/images/pipelines-xgboost-graph.png
Labels: approved, cla: yes, lgtm, size/L

#2521 Update redirects to include job scheduling change
  content/en/_redirects
Labels: approved, cla: yes, lgtm, size/XS

#2533 Add Katib config PV reclaim policy
  content/en/docs/components/katib/katib-config.md
Labels: approved, cla: yes, lgtm, size/XS

#2538 Move KFServing to under Components, out of `Tools for serving`
  content/en/_redirects
  content/en/docs/components/kfserving/OWNERS
  content/en/docs/components/kfserving/_index.md
  content/en/docs/components/kfserving/kfserving.md
  content/en/docs/components/kfserving/kfserving.png
Labels: approved, cla: yes, lgtm, size/S

#2543 Add Tommy to the IBM doc approvers
  content/en/docs/ibm/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2492 Create "Distributions" with kfctl + Kubeflow Operator
  content/en/_redirects
  content/en/docs/azure/deploy/install-kubeflow.md
  content/en/docs/components/central-dash/overview.md
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/overview.md
  content/en/docs/components/multi-tenancy/design.md
  content/en/docs/distributions/OWNERS
  content/en/docs/distributions/_index.md
  content/en/docs/distributions/kfctl/OWNERS
  content/en/docs/distributions/kfctl/_index.md
  content/en/docs/distributions/kfctl/deployment.md
  content/en/docs/distributions/kfctl/kustomize.md
  content/en/docs/distributions/kfctl/minikube.md
  content/en/docs/distributions/kfctl/multi-user.md
  content/en/docs/distributions/operator/OWNERS
  content/en/docs/distributions/operator/_index.md
  content/en/docs/distributions/operator/install-kubeflow.md
  content/en/docs/distributions/operator/install-operator.md
  content/en/docs/distributions/operator/introduction.md
  content/en/docs/distributions/operator/troubleshooting.md
  content/en/docs/distributions/operator/uninstall-kubeflow.md
  content/en/docs/distributions/operator/uninstall-operator.md
  content/en/docs/gke/customizing-gke.md
  content/en/docs/ibm/deploy/install-kubeflow-on-iks.md
  content/en/docs/other-guides/usage-reporting.md
  content/en/docs/reference/version-policy.md
  content/en/docs/started/getting-started.md
  content/en/docs/started/k8s/kfctl-existing-arrikto.md
  content/en/docs/started/k8s/overview.md
  content/en/docs/started/workstation/getting-started-linux.md
  content/en/docs/started/workstation/getting-started-macos.md
  content/en/docs/started/workstation/getting-started-windows.md
Labels: approved, cla: yes, lgtm, size/L

#2530 doc: Add instructions to access cluster with IBM Cloud vpc-gen2.
  content/en/docs/ibm/create-cluster-vpc.md
  content/en/docs/ibm/create-cluster.md
  content/en/docs/ibm/deploy/install-kubeflow-on-iks.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2539 Add RFMVasconcelos to OWNERS/approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2552 Deletes old redirects - pages do not exist anymore
  content/en/_redirects
Labels: approved, cla: yes, lgtm, size/XS

#2551 Move `AWS` platform under /distributions
  content/en/_redirects
  content/en/docs/distributions/aws/OWNERS
  content/en/docs/distributions/aws/_index.md
  content/en/docs/distributions/aws/authentication-oidc.md
  content/en/docs/distributions/aws/authentication.md
  content/en/docs/distributions/aws/aws-e2e.md
  content/en/docs/distributions/aws/custom-domain.md
  content/en/docs/distributions/aws/customizing-aws.md
  content/en/docs/distributions/aws/deploy/_index.md
  content/en/docs/distributions/aws/deploy/install-kubeflow.md
  content/en/docs/distributions/aws/deploy/uninstall-kubeflow.md
  content/en/docs/distributions/aws/features.md
  content/en/docs/distributions/aws/files/rds.yaml
  content/en/docs/distributions/aws/iam-for-sa.md
  content/en/docs/distributions/aws/logging.md
  content/en/docs/distributions/aws/notebook-server.md
  content/en/docs/distributions/aws/pipeline.md
  content/en/docs/distributions/aws/private-access.md
  content/en/docs/distributions/aws/rds.md
  content/en/docs/distributions/aws/storage.md
  content/en/docs/distributions/aws/troubleshooting-aws.md
Labels: approved, cla: yes, lgtm, size/XS

#2557 update broken link
  content/en/docs/components/pipelines/sdk/pipelines-with-tekton.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2558 UPDATE fix broken links to tensoflorw serving
  content/en/docs/gke/gcp-e2e.md
  content/en/docs/ibm/iks-e2e.md
  content/en/serving.svg
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2547 Move `Google` platform under /distributions
  content/en/_redirects
  content/en/docs/distributions/gke/OWNERS
  content/en/docs/distributions/gke/_index.md
  content/en/docs/distributions/gke/anthos.md
  content/en/docs/distributions/gke/authentication.md
  content/en/docs/distributions/gke/cloud-filestore.md
  content/en/docs/distributions/gke/custom-domain.md
  content/en/docs/distributions/gke/customizing-gke.md
  content/en/docs/distributions/gke/deploy/_index.md
  content/en/docs/distributions/gke/deploy/delete-cli.md
  content/en/docs/distributions/gke/deploy/deploy-cli.md
  content/en/docs/distributions/gke/deploy/deploy-ui.md
  content/en/docs/distributions/gke/deploy/management-setup.md
  content/en/docs/distributions/gke/deploy/monitor-iap-setup.md
  content/en/docs/distributions/gke/deploy/oauth-setup.md
  content/en/docs/distributions/gke/deploy/project-setup.md
  content/en/docs/distributions/gke/deploy/reasons.md
  content/en/docs/distributions/gke/deploy/upgrade.md
  content/en/docs/distributions/gke/gcp-e2e.md
  content/en/docs/distributions/gke/monitoring.md
  content/en/docs/distributions/gke/pipelines/_index.md
  content/en/docs/distributions/gke/pipelines/authentication-pipelines.md
  content/en/docs/distributions/gke/pipelines/authentication-sdk.md
  content/en/docs/distributions/gke/pipelines/enable-gpu-and-tpu.md
  content/en/docs/distributions/gke/pipelines/preemptible.md
  content/en/docs/distributions/gke/pipelines/upgrade.md
  content/en/docs/distributions/gke/private-clusters.md
  content/en/docs/distributions/gke/troubleshooting-gke.md
Labels: approved, cla: yes, lgtm, size/S

#2548 Move `Azure` platform under /distributions
  content/en/_redirects
  content/en/docs/distributions/azure/OWNERS
  content/en/docs/distributions/azure/_index.md
  content/en/docs/distributions/azure/authentication-oidc.md
  content/en/docs/distributions/azure/authentication.md
  content/en/docs/distributions/azure/azureEndtoEnd.md
  content/en/docs/distributions/azure/azureMySQL.md
  content/en/docs/distributions/azure/deploy/_index.md
  content/en/docs/distributions/azure/deploy/existing-cluster.md
  content/en/docs/distributions/azure/deploy/install-kubeflow.md
  content/en/docs/distributions/azure/deploy/uninstall-kubeflow.md
  content/en/docs/distributions/azure/images/appReg.PNG
  content/en/docs/distributions/azure/images/clientID2.PNG
  content/en/docs/distributions/azure/images/createContainerReg.PNG
  content/en/docs/distributions/azure/images/creatingWS.PNG
  content/en/docs/distributions/azure/images/finalOutput.PNG
  content/en/docs/distributions/azure/images/finishedRunning.PNG
  content/en/docs/distributions/azure/images/password.PNG
  content/en/docs/distributions/azure/images/pipelinedash.PNG
  content/en/docs/distributions/azure/images/pipelinesInput.png
  content/en/docs/distributions/azure/images/pipelinesUpload.PNG
  content/en/docs/distributions/azure/images/roleAssign.PNG
  content/en/docs/distributions/azure/machinelearningcomponent.md
  content/en/docs/distributions/azure/troubleshooting-azure.md
Labels: approved, cla: yes, lgtm, size/XS

#2544 KFP - Update Python function-based component doc with param naming rules
  content/en/docs/components/pipelines/sdk/python-function-components.ipynb
  content/en/docs/components/pipelines/sdk/python-function-components.md
Labels: approved, cla: yes, lgtm, size/L

#2550 Move `Openshift` platform under /distributions
  content/en/_redirects
  content/en/docs/distributions/openshift/OWNERS
  content/en/docs/distributions/openshift/_index.md
  content/en/docs/distributions/openshift/install-kubeflow.md
  content/en/docs/distributions/openshift/uninstall-kubeflow.md
Labels: approved, cla: yes, lgtm, size/XS

#2549 Move `IBM` platform under /distributions
  content/en/_redirects
  content/en/docs/distributions/ibm/OWNERS
  content/en/docs/distributions/ibm/_index.md
  content/en/docs/distributions/ibm/create-cluster-vpc.md
  content/en/docs/distributions/ibm/create-cluster.md
  content/en/docs/distributions/ibm/deploy/OWNERS
  content/en/docs/distributions/ibm/deploy/_index.md
  content/en/docs/distributions/ibm/deploy/authentication.md
  content/en/docs/distributions/ibm/deploy/deployment-process.md
  content/en/docs/distributions/ibm/deploy/install-kubeflow-on-IBM-openshift.md
  content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
  content/en/docs/distributions/ibm/deploy/uninstall-kubeflow.md
  content/en/docs/distributions/ibm/iks-e2e.md
  content/en/docs/distributions/ibm/kfp-tekton.png
  content/en/docs/distributions/ibm/pipelines.md
  content/en/docs/distributions/ibm/using-icr.md
Labels: approved, cla: yes, lgtm, size/XS

#2560 [IBM] Update openshift kubeflow installation
  content/en/docs/distributions/ibm/deploy/install-kubeflow-on-IBM-openshift.md
Labels: approved, cla: yes, lgtm, size/S

#2562 Make kfctl first distribution
  content/en/docs/distributions/kfctl/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#2569 Move getting started on K8s page to under kfctl distribution
  content/en/_redirects
  content/en/docs/distributions/kfctl/overview.md
  content/en/docs/started/k8s/OWNERS
  content/en/docs/started/k8s/_index.md
Labels: approved, cla: yes, lgtm, size/S

#2574 Update GCP distribution OWNERS
  content/en/docs/distributions/gke/OWNERS
Labels: approved, cla: yes, size/XS

#2575 Update KFP shortcodes OWNERS
  layouts/shortcodes/pipelines/OWNERS
Labels: approved, cla: yes, size/XS

#2577 Move MicroK8s to distributions
  content/en/docs/distributions/microk8s/OWNERS
  content/en/docs/distributions/microk8s/_index.md
  content/en/docs/distributions/microk8s/kubeflow-on-microk8s.md
Labels: approved, cla: yes, lgtm, size/S

#2579 Add redirect for MicroK8s move - missed on #2577
  content/en/_redirects
Labels: approved, cla: yes, lgtm, size/XS

#2578 Add Charmed Kubeflow Operators to list of available Kubeflow distributions
  content/en/docs/distributions/aws/_index.md
  content/en/docs/distributions/azure/_index.md
  content/en/docs/distributions/charmed/OWNERS
  content/en/docs/distributions/charmed/_index.md
  content/en/docs/distributions/charmed/install-kubeflow.md
  content/en/docs/distributions/gke/_index.md
  content/en/docs/distributions/ibm/_index.md
Labels: approved, cla: yes, lgtm, size/L

#2581 Fix broken link
  content/en/docs/distributions/charmed/install-kubeflow.md
Labels: approved, cla: yes, lgtm, size/XS

#2571 IBM Cloud docs: update pipelines SDK setup for single-user
  content/en/docs/distributions/ibm/pipelines.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
