Repository kubeflow/website, pull requests merged in 2021-11, with the labels that each got.

#3052 pipelines: Upgrade version to 1.7.1
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved, cla: yes

#3048 System requirements from 12GB to 32GB
  content/en/docs/distributions/minikf/minikf-vagrant.md
Labels: size/XS, lgtm, approved, cla: yes

#3046 update versioning img
  content/en/docs/about/docs.md
  content/en/docs/images/version-dropdown.jpg
  content/en/docs/images/version-dropdown.png
Labels: size/XS, lgtm, approved, cla: yes

#3006 improve navigation bar
  config.toml
  layouts/partials/head.html
  layouts/partials/navbar.html
  layouts/partials/sidebar-tree.html
Labels: lgtm, approved, size/L, cla: yes

#3014 remove `Reference` section
  content/en/_redirects
  content/en/docs/components/katib/api-reference/_index.md
  content/en/docs/components/katib/api-reference/grpc-v1alpha3.md
  content/en/docs/components/katib/api-reference/grpc-v1beta1.md
  content/en/docs/components/katib/overview.md
  content/en/docs/components/notebooks/api-reference/_index.md
  content/en/docs/components/notebooks/api-reference/notebook-v1.md
  content/en/docs/reference/OWNERS
  content/en/docs/reference/_index.md
  content/en/docs/reference/images.md
  content/en/docs/reference/katib/_index.md
  content/en/docs/reference/katib/v1alpha3/_index.md
  content/en/docs/reference/katib/v1beta1/_index.md
  content/en/docs/reference/mpijob/_index.md
  content/en/docs/reference/mpijob/v1alpha2/_index.md
  content/en/docs/reference/mpijob/v1alpha2/mpi.md
  content/en/docs/reference/notebook/_index.md
  content/en/docs/reference/overview.md
  content/en/docs/reference/pytorchjob/_index.md
  content/en/docs/reference/pytorchjob/v1/_index.md
  content/en/docs/reference/pytorchjob/v1/pytorch.md
  content/en/docs/reference/pytorchjob/v1beta2/_index.md
  content/en/docs/reference/pytorchjob/v1beta2/pytorch.md
  content/en/docs/reference/tfjob/_index.md
  content/en/docs/reference/tfjob/v1/_index.md
  content/en/docs/reference/tfjob/v1/common.md
  content/en/docs/reference/tfjob/v1/tensorflow.md
  content/en/docs/reference/tfjob/v1beta2/_index.md
  content/en/docs/reference/tfjob/v1beta2/common.md
  content/en/docs/reference/tfjob/v1beta2/tensorflow.md
  content/en/docs/reference/version-policy.md
  content/en/docs/started/kubeflow-overview.md
  content/en/docs/started/support.md
  gen-api-reference/README.md
  gen-api-reference/gen-pytorchjob-api.sh
  gen-api-reference/gen-tfjob-api.sh
  gen-api-reference/kubeflow-config.json
  layouts/shortcodes/alpha-status.html
  layouts/shortcodes/beta-status.html
  layouts/shortcodes/stable-status.html
Labels: size/XXL, lgtm, approved, cla: yes

#3049 Add docs to describe how to install HA katib-controller
  content/en/docs/components/katib/hyperparameter.md
Labels: lgtm, approved, size/M, cla: yes

#2713 (gke) Updated GPU/TPU and preemptible outdated document
  content/en/docs/distributions/gke/customizing-gke.md
  content/en/docs/distributions/gke/pipelines/enable-gpu-and-tpu.md
  content/en/docs/distributions/gke/pipelines/preemptible.md
Labels: lgtm, approved, size/L, cla: yes

#3038 fix broken pipelines overview link
  content/en/docs/components/pipelines/overview/concepts/output-artifact.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#3037 kfp: Update Service account explanation in mult-user access
  content/en/docs/components/pipelines/sdk/connect-api.md
Labels: size/XS, lgtm, approved, cla: yes

#2992 fix kfctl version
  content/en/docs/distributions/azure/authentication-oidc.md
  content/en/docs/distributions/azure/deploy/install-kubeflow.md
Labels: lgtm, approved, size/S, cla: yes

#3029 Fix misworded and out of order link
  content/en/docs/components/multi-tenancy/overview.md
Labels: size/XS, lgtm, approved, ok-to-test, cla: yes

#3041 fix: update argo-workflow links
  content/en/docs/components/pipelines/overview/pipelines-overview.md
  content/en/docs/components/pipelines/sdk/manipulate-resources.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#3057 pipelines: update image to use for standalone
  content/en/docs/components/pipelines/installation/standalone-deployment.md
Labels: size/XS, lgtm, approved, cla: yes

#3058 update hugo version
  README.md
  netlify.toml
Labels: lgtm, approved, size/S, cla: yes

#2989 add shannonbradshaw to approvers
  OWNERS
Labels: size/XS, lgtm, approved, cla: yes

#3061 update bootstrap version links
  content/en/docs/about/style-guide.md
Labels: size/XS, lgtm, approved, cla: yes

#3069 examples: Put on warning for out-of-date examples
  content/en/docs/started/kubeflow-examples.md
Labels: size/XS, lgtm, approved, cla: yes

#3063 refactor `Components / Kubeflow Pipelines` section
  content/en/_redirects
  content/en/docs/components/pipelines/concepts/_index.md
  content/en/docs/components/pipelines/concepts/component.md
  content/en/docs/components/pipelines/concepts/experiment.md
  content/en/docs/components/pipelines/concepts/graph.md
  content/en/docs/components/pipelines/concepts/output-artifact.md
  content/en/docs/components/pipelines/concepts/pipeline.md
  content/en/docs/components/pipelines/concepts/run-trigger.md
  content/en/docs/components/pipelines/concepts/run.md
  content/en/docs/components/pipelines/concepts/step.md
  content/en/docs/components/pipelines/installation/_index.md
  content/en/docs/components/pipelines/installation/choose-executor.md
  content/en/docs/components/pipelines/installation/compatibility-matrix.md
  content/en/docs/components/pipelines/installation/localcluster-deployment.md
  content/en/docs/components/pipelines/installation/overview.md
  content/en/docs/components/pipelines/installation/standalone-deployment.md
  content/en/docs/components/pipelines/installation/upgrade.md
  content/en/docs/components/pipelines/introduction.md
  content/en/docs/components/pipelines/overview/_index.md
  content/en/docs/components/pipelines/overview/caching-v2.md
  content/en/docs/components/pipelines/overview/caching.md
  content/en/docs/components/pipelines/overview/concepts/_index.md
  content/en/docs/components/pipelines/overview/interfaces.md
  content/en/docs/components/pipelines/overview/multi-user.md
  content/en/docs/components/pipelines/overview/pipeline-root.md
  content/en/docs/components/pipelines/overview/quickstart.md
  content/en/docs/components/pipelines/reference/_index.md
  content/en/docs/components/pipelines/sdk-v2/_index.md
  content/en/docs/components/pipelines/sdk-v2/build-pipeline.ipynb
  content/en/docs/components/pipelines/sdk-v2/build-pipeline.md
  content/en/docs/components/pipelines/sdk-v2/component-development.md
  content/en/docs/components/pipelines/sdk-v2/python-function-components.ipynb
  content/en/docs/components/pipelines/sdk-v2/python-function-components.md
  content/en/docs/components/pipelines/sdk-v2/v2-compatibility.md
  content/en/docs/components/pipelines/sdk-v2/v2-component-io.md
  content/en/docs/components/pipelines/sdk/_index.md
  content/en/docs/components/pipelines/sdk/build-pipeline.ipynb
  content/en/docs/components/pipelines/sdk/build-pipeline.md
  content/en/docs/components/pipelines/sdk/install-sdk.md
  content/en/docs/components/pipelines/sdk/output-viewer.md
  content/en/docs/components/pipelines/sdk/v2/_index.md
  content/en/docs/components/pipelines/troubleshooting.md
  content/en/docs/components/pipelines/tutorials/_index.md
  content/en/docs/components/pipelines/tutorials/build-pipeline.md
  content/en/docs/distributions/gke/authentication.md
  content/en/docs/distributions/gke/pipelines/authentication-pipelines.md
  content/en/docs/distributions/gke/pipelines/authentication-sdk.md
  content/en/docs/external-add-ons/feature-store/getting-started.md
  content/en/docs/started/kubeflow-overview.md
Labels: lgtm, approved, size/L, cla: yes

#3081 [pipelines] Update pipeline overview link in everywhere in website
  assets/icons/pipelines.svg
  content/en/_index.html
  content/en/pipelines.svg
Labels: size/XS, lgtm, approved, cla: yes

#3007 restructure `About` section
  config.toml
  content/en/_index.html
  content/en/_redirects
  content/en/docs/about/_index.md
  content/en/docs/about/community.md
  content/en/docs/about/contributing.md
  content/en/docs/about/docs.md
  content/en/docs/about/events.md
  content/en/docs/about/gsoc.md
  content/en/docs/about/style-guide.md
  content/en/docs/about/use-cases.md
  content/en/docs/components/pipelines/tutorials/cloud-tutorials.md
  content/en/docs/distributions/minikf/minikf-vagrant.md
  content/en/docs/external-add-ons/fairing/fairing-overview.md
  content/en/docs/external-add-ons/serving/overview.md
  content/en/docs/started/_index.md
  content/en/docs/started/architecture.md
  content/en/docs/started/installing-kubeflow.md
  content/en/docs/started/introduction.md
  content/en/docs/started/kubeflow-examples.md
  content/en/docs/started/support.md
Labels: size/XXL, lgtm, approved, cla: yes

#3080 Remove outdated API Reference for Katib
  content/en/_redirects
  content/en/docs/components/katib/api-reference/_index.md
  content/en/docs/components/katib/api-reference/grpc-v1alpha3.md
  content/en/docs/components/katib/api-reference/grpc-v1beta1.md
  content/en/docs/components/katib/overview.md
Labels: size/XXL, lgtm, approved, cla: yes

#3082 (pipelines): Explain Metadata dependency and deprecation of kubeflow/metadata
  content/en/docs/components/pipelines/concepts/metadata.md
  models.txt
Labels: lgtm, approved, size/L, cla: yes
