Repository kubeflow/website, pull requests merged in 2021-09, with the labels that each got.

#2903 update Argo Executors link
  content/en/docs/components/pipelines/installation/localcluster-deployment.md
Labels: size/XS, lgtm, approved, cla: yes

#2777 #2658 replace ServiceRoleBinding with AuthorizationPolicy
  content/en/docs/components/multi-tenancy/getting-started.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#2917 Update training operators doc
  content/en/docs/components/training/pytorch.md
  content/en/docs/components/training/tftraining.md
Labels: lgtm, approved, size/L, cla: yes

#2918 Update docs for MXNet Jobs
  content/en/docs/components/training/mxnet.md
Labels: lgtm, approved, size/S, cla: yes

#2919 Add XGboost doc for training
  content/en/docs/components/training/xgboost.md
Labels: lgtm, approved, size/L, cla: yes

#2914 fix hash link
  content/en/docs/about/style-guide.md
Labels: size/XS, lgtm, approved, cla: yes

#2922 Update MPI operator docs
  content/en/docs/components/training/mpi.md
Labels: lgtm, approved, size/M, cla: yes

#2920 Fix docs for Training Operators 1.3
  content/en/docs/components/training/mpi.md
  content/en/docs/components/training/mxnet.md
  content/en/docs/components/training/pytorch.md
  content/en/docs/components/training/tftraining.md
Labels: lgtm, approved, size/XL, cla: yes

#2925 Add versions to MicroK8s install
  content/en/docs/distributions/microk8s/kubeflow-on-microk8s.md
Labels: size/XS, lgtm, approved, cla: yes

#2926 Update OWNERS for MicroK8s
  content/en/docs/distributions/microk8s/OWNERS
Labels: size/XS, lgtm, approved, cla: yes

#2927 Updated Owners list in nutanix
  content/en/docs/distributions/nutanix/OWNERS
Labels: size/XS, lgtm, approved, cla: yes

#2930 nit: add hyperlinks for pip packages
  content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
Labels: size/XS, lgtm, approved, cla: yes

#2931 Update feast documentation and links
  content/en/docs/external-add-ons/feature-store/getting-started.md
Labels: lgtm, approved, size/M, cla: yes

#2929 Update nutanix distribution docs
  content/en/docs/distributions/nutanix/install-kubeflow.md
Labels: lgtm, approved, needs-ok-to-test, size/L, cla: yes

#2932 Update overview.md
  content/en/docs/components/multi-tenancy/overview.md
Labels: lgtm, approved, size/M, cla: yes

#2934 Update getting-started.md
  content/en/docs/components/multi-tenancy/getting-started.md
Labels: lgtm, approved, size/S, cla: yes

#2909 added pipeline root doc for kubeflow pipelines
  content/en/docs/components/pipelines/pipeline-root.md
  content/en/docs/images/pipelines/v2/pipelines-ui-pipelineroot.png
Labels: lgtm, approved, size/M, cla: yes

#2939 pipelines: Add image for KFPv2 caches on UI. Partial #5977
  content/en/docs/components/pipelines/caching-v2.md
  content/en/docs/images/pipelines/v2/cacheicon.png
Labels: size/XS, lgtm, approved, cla: yes

#2949 Typo fix for IBM docs
  content/en/docs/distributions/ibm/create-cluster.md
Labels: size/XS, lgtm, approved, cla: yes

#2946 Update IKS to kfp v1.4
  content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
Labels: lgtm, approved, size/S, cla: yes

#2953 pipelines: KFP Version for Kubeflow 1.3 table update. Partial #2937
  content/en/docs/components/pipelines/installation/overview.md
Labels: size/XS, lgtm, approved, cla: yes

#2954 pipelines: Documentation for HTML and Markdown in v2 compatible mode
  content/en/docs/components/pipelines/sdk/output-viewer.md
  content/en/docs/images/pipelines/v2/markdown-visualization.png
Labels: lgtm, approved, size/M, cla: yes

#2938 fix page source link
  content/en/docs/about/style-guide.md
Labels: size/XS, lgtm, approved, cla: yes

#2942 Fixing the link for kfdef
  content/en/docs/distributions/openshift/install-kubeflow.md
Labels: size/XS, lgtm, approved, cla: yes

#2965 Update docs for XGBoost
  content/en/docs/components/training/xgboost.md
Labels: lgtm, approved, needs-ok-to-test, size/S, cla: yes

#2966 fix typo in the MXNET training operator page
  content/en/docs/components/training/mxnet.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#2962 Katib: Add components guide
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/overview.md
  content/en/docs/reference/images.md
Labels: lgtm, approved, size/M, cla: yes

#2971 Fix small typo in Katib overview.md
  content/en/docs/components/katib/overview.md
Labels: size/XS, lgtm, approved, cla: yes

#2912 Update output-artifact.md w/ Working Link
  content/en/docs/components/pipelines/overview/concepts/output-artifact.md
Labels: size/XS, lgtm, approved, ok-to-test, cla: yes

#2952 Add yhwang as the IBM doc reviewer
  content/en/docs/distributions/ibm/OWNERS
  content/en/docs/distributions/ibm/deploy/OWNERS
Labels: size/XS, lgtm, approved, cla: yes

#2975 Add more Googler root OWNERS
  OWNERS
Labels: size/XS, lgtm, approved, cla: yes

#2973 update hugo to last version
  README.md
  netlify.toml
Labels: lgtm, approved, size/S, cla: yes

#2979 Refine some details for IKS deployment
  content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
Labels: lgtm, approved, size/M, cla: yes
