Repository kubeflow/website, pull requests merged in 2021-08, with the labels that each got.

#2850 Fix typo
  content/en/docs/distributions/gke/customizing-gke.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2849 update index blue section
  content/en/_index.html
Labels: approved, cla: yes, lgtm, size/XS

#2830 Add MLRun Serving: Index + External Add-Ons
  content/en/_index.html
  content/en/docs/external-add-ons/serving/mlrun.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#2851 Add Support for Argo and XGBoostJob in Katib
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/overview.md
  content/en/docs/components/katib/trial-template.md
Labels: lgtm, approved, size/M, cla: yes

#2846 Remove the Tutorials, Samples, and Shared Resources section
  content/en/_redirects
  content/en/docs/examples/_index.md
  content/en/docs/examples/blog-posts.md
  content/en/docs/examples/codelabs-tutorials.md
  content/en/docs/examples/shared-resources.md
  content/en/docs/examples/videos.md
  content/en/docs/started/kubeflow-examples.md
Labels: lgtm, approved, size/L, cla: yes

#2853 GoogleCloud: Update for Kubeflow 1.3.1 on Google Cloud
  content/en/docs/distributions/gke/anthos.md
  content/en/docs/distributions/gke/custom-domain.md
  content/en/docs/distributions/gke/deploy/deploy-cli.md
  content/en/docs/distributions/gke/deploy/management-setup.md
  content/en/docs/distributions/gke/deploy/oauth-setup.md
  content/en/docs/distributions/gke/deploy/overview.md
  content/en/docs/distributions/gke/deploy/project-setup.md
  content/en/docs/distributions/gke/deploy/upgrade.md
Labels: lgtm, approved, size/M, cla: yes

#2858 (pipelines) Update KFP version requirement for v2-compatible
  content/en/docs/components/pipelines/sdk/v2/v2-compatibility.md
Labels: size/XS, lgtm, approved, cla: yes

#2854 fix: compatibility with hugo v0.87.0
  content/en/docs/components/central-dash/_index.md
  content/en/docs/reference/version-policy.md
Labels: size/XS, lgtm, approved, cla: yes

#2847 added Kubeflow Pipeline v2 caching doc
  content/en/docs/components/pipelines/caching-v2.md
  content/en/docs/components/pipelines/caching.md
Labels: lgtm, approved, size/M, cla: yes

#2857 docs(kfp): choose a workflow executor. Part of kubeflow/pipelines#5718
  content/en/docs/components/pipelines/installation/choose-executor.md
  content/en/docs/components/pipelines/installation/standalone-deployment.md
Labels: lgtm, approved, size/L, cla: yes

#2867 docs(pipelines): KFP V2 visualization doc. Partial: kubeflow/pipelines#5666
  content/en/docs/components/pipelines/sdk/output-viewer.md
  content/en/docs/components/pipelines/sdk/v2/component-development.md
  content/en/docs/images/pipelines/v2/confusion-matrix.png
  content/en/docs/images/pipelines/v2/roc-curve.png
  content/en/docs/images/pipelines/v2/scalar-metrics.png
Labels: lgtm, approved, size/L, cla: yes

#2861 add 404 page
  assets/scss/_styles_project.scss
  layouts/404.html
  resources/_gen/assets/scss/scss/main.scss_4853eb546e7a6c0898ed71feae7357c0.content
  resources/_gen/assets/scss/scss/main.scss_4853eb546e7a6c0898ed71feae7357c0.json
Labels: lgtm, approved, size/M, cla: yes

#2871 Modify Katib Trial templates label
  content/en/docs/components/katib/trial-template.md
Labels: size/XS, lgtm, approved, cla: yes

#2872 Fixing bug in mlrun serving
  content/en/docs/external-add-ons/serving/mlrun.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#2880 Add Support for Optuna in Katib
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/katib-config.md
Labels: lgtm, approved, size/M, cla: yes

#2876 Update component-development.md to showcase v2 compatible data passing.
  content/en/docs/components/pipelines/sdk/component-development.md
Labels: lgtm, approved, size/M, cla: yes

#2865 Adding Docs for Kubeflow on Nutanix Karbon
  content/en/docs/distributions/nutanix/OWNERS
  content/en/docs/distributions/nutanix/_index.md
  content/en/docs/distributions/nutanix/install-kubeflow.md
  content/en/docs/distributions/nutanix/nutanix-storage.md
  content/en/docs/distributions/nutanix/uninstall-kubeflow.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/L, cla: yes

#2882 Add Katib Algorithm Settings for TPE and Multivariate TPE
  content/en/docs/components/katib/experiment.md
Labels: lgtm, approved, size/M, cla: yes

#2884 Fix typos in docs
  content/en/docs/components/central-dash/customizing-menu.md
  content/en/docs/components/kfserving/webapp.md
  content/en/docs/components/multi-tenancy/getting-started.md
  content/en/docs/components/pipelines/installation/standalone-deployment.md
  content/en/docs/components/pipelines/sdk/python-based-visualizations.md
  content/en/docs/distributions/azure/azureMySQL.md
  content/en/docs/distributions/gke/customizing-gke.md
  content/en/docs/distributions/gke/deploy/deploy-cli.md
  content/en/docs/distributions/gke/deploy/management-setup.md
  content/en/docs/distributions/gke/deploy/upgrade.md
  content/en/docs/distributions/gke/pipelines/authentication-pipelines.md
  content/en/docs/distributions/operator/introduction.md
Labels: lgtm, approved, needs-ok-to-test, size/M, cla: yes

#2885 fixed typo in contributing.md
  content/en/docs/about/contributing.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#2886 fix broken links in docs
  content/en/docs/components/multi-tenancy/design.md
  content/en/docs/components/pipelines/sdk/build-pipeline.md
  content/en/docs/distributions/aws/customizing-aws/rds.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#2887 Update installation instructions for IKS
  content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
Labels: lgtm, approved, size/L, cla: yes

#2883 hugo update
  README.md
  netlify.toml
Labels: lgtm, approved, size/S, cla: yes

#2870 Add specific version of Kustomize that works
  content/en/docs/distributions/gke/deploy/deploy-cli.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#2891 link display fix
  content/en/docs/distributions/openshift/install-kubeflow.md
Labels: size/XS, lgtm, approved, cla: yes

#2890 Fix broken kustomization.yaml link
  content/en/docs/components/pipelines/installation/standalone-deployment.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#2904 docs(kfp): update wording for feedback
  content/en/docs/components/pipelines/installation/upgrade.md
Labels: size/XS, lgtm, approved, cla: yes

#2906 Update kubeflow.md
  content/en/docs/about/kubeflow.md
Labels: size/XS, lgtm, approved, cla: yes
