Repository kubeflow/website, pull requests merged in 2021-04, with the labels that each got.

#2582 Kubeflow on GCP v1.2.1 doc update
  content/en/docs/gke/deploy/deploy-cli.md
  content/en/docs/gke/deploy/management-setup.md
  content/en/docs/gke/deploy/upgrade.md
Labels: approved, cla: yes, lgtm, size/S

#2583 update broken links / tweak names
  content/en/docs/reference/images.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2576 Move MiniKF to distributions
  content/en/_redirects
  content/en/docs/distributions/minikf/_index.md
  content/en/docs/distributions/minikf/getting-started-minikf.md
  content/en/docs/distributions/minikf/minikf-aws.md
  content/en/docs/distributions/minikf/minikf-gcp.md
Labels: approved, cla: yes, lgtm, size/S

#2584 Clean up "Frameworks for training" + rename to "Training Operators"
  content/en/docs/components/training/_index.md
  content/en/docs/components/training/chainer.md
  content/en/docs/components/training/pytorch.md
  content/en/docs/components/training/tftraining.md
Labels: approved, cla: yes, lgtm, size/M

#2580 Fix broken link
  content/en/docs/components/pipelines/overview/pipelines-overview.md
Labels: approved, cla: yes, lgtm, size/XS

#2585 Remove "outdated" banners from MPI + MXnet operators
  content/en/docs/components/training/mpi.md
  content/en/docs/components/training/mxnet.md
Labels: approved, cla: yes, lgtm, size/XS

#2586 docs: Update MPI and MXNet operator pages
  content/en/docs/components/training/mpi.md
  content/en/docs/components/training/mxnet.md
Labels: approved, cla: yes, lgtm, size/L

#2572 Pin the version of kustomize, v4 is not supported.
  content/en/docs/distributions/gke/deploy/deploy-cli.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2591 Update gke/anthos.md
  content/en/docs/distributions/gke/anthos.md
Labels: approved, cla: yes, lgtm, size/XS

#2603 fix broken link
  content/en/docs/distributions/kfctl/kustomize.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2621 fix broken link
  content/en/docs/reference/version-policy.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2593 fix footer
  assets/scss/_variables_project.scss
  layouts/partials/footer.html
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#2624 fix broken link
  content/en/docs/reference/notebook/v1/_index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2614 Fix broken url link
  content/en/docs/components/pipelines/overview/concepts/run.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2627 docs(kfp): bump version to 1.5.0
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, cla: yes, lgtm, size/XS

#2598 Update the "MiniKF on laptop/desktop" guide
  content/en/docs/distributions/minikf/minikf-vagrant.md
Labels: approved, cla: yes, lgtm, size/XS

#2595 Update KFServing docs for Kubeflow 1.3
  content/en/docs/components/kfserving/kfserving.md
  content/en/docs/components/serving/overview.md
Labels: approved, cla: yes, lgtm, size/M

#2630 Components v external add ons
  content/en/_index.html
  content/en/_redirects
  content/en/docs/components/notebooks/setup.md
  content/en/docs/distributions/gke/deploy/project-setup.md
  content/en/docs/external-add-ons/_index.md
  content/en/docs/external-add-ons/fairing/_index.md
  content/en/docs/external-add-ons/fairing/azure/_index.md
  content/en/docs/external-add-ons/fairing/configure-fairing.md
  content/en/docs/external-add-ons/fairing/fairing-overview.md
  content/en/docs/external-add-ons/fairing/gcp/_index.md
  content/en/docs/external-add-ons/fairing/gcp/configure-gcp.md
  content/en/docs/external-add-ons/fairing/gcp/tutorials/_index.md
  content/en/docs/external-add-ons/fairing/gcp/tutorials/gcp-kubeflow-notebook.md
  content/en/docs/external-add-ons/fairing/gcp/tutorials/gcp-local-notebook.md
  content/en/docs/external-add-ons/fairing/install-fairing.md
  content/en/docs/external-add-ons/fairing/reference/_index.md
  content/en/docs/external-add-ons/fairing/reference/sdk.md
  content/en/docs/external-add-ons/fairing/tutorials/_index.md
  content/en/docs/external-add-ons/fairing/tutorials/other-tutorials.md
  content/en/docs/external-add-ons/feature-store/OWNERS
  content/en/docs/external-add-ons/feature-store/_index.md
  content/en/docs/external-add-ons/feature-store/getting-started.md
  content/en/docs/external-add-ons/feature-store/overview.md
  content/en/docs/external-add-ons/istio/OWNERS
  content/en/docs/external-add-ons/istio/_index.md
  content/en/docs/external-add-ons/istio/istio-in-kubeflow.md
  content/en/docs/external-add-ons/kale/_index.md
  content/en/docs/external-add-ons/serving/OWNERS
  content/en/docs/external-add-ons/serving/_index.md
  content/en/docs/external-add-ons/serving/bentoml.md
  content/en/docs/external-add-ons/serving/istio-dashboard.png
  content/en/docs/external-add-ons/serving/overview.md
  content/en/docs/external-add-ons/serving/seldon.md
  content/en/docs/external-add-ons/serving/tfbatchpredict.md
  content/en/docs/external-add-ons/serving/tfserving_new.md
  content/en/docs/external-add-ons/serving/tritoninferenceserver.md
  content/en/docs/reference/version-policy.md
  content/en/docs/started/kubeflow-overview.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#2604 Remove deprecated kfctl pages
  content/en/docs/components/central-dash/overview.md
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/overview.md
  content/en/docs/components/multi-tenancy/design.md
  content/en/docs/distributions/kfctl/OWNERS
  content/en/docs/distributions/kfctl/_index.md
  content/en/docs/distributions/kfctl/deployment.md
  content/en/docs/distributions/kfctl/kustomize.md
  content/en/docs/distributions/kfctl/minikube.md
  content/en/docs/distributions/kfctl/multi-user.md
  content/en/docs/distributions/kfctl/overview.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XXL

#2611 refactor "Installing Kubeflow" page
  content/en/docs/started/getting-started.md
  content/en/docs/started/installing-kubeflow.md
Labels: approved, cla: yes, lgtm, size/L

#2605 remove "Getting Started"/"Workstation Installation"
  content/en/_redirects
  content/en/docs/started/workstation/OWNERS
  content/en/docs/started/workstation/_index.md
  content/en/docs/started/workstation/getting-started-linux.md
  content/en/docs/started/workstation/getting-started-macos.md
  content/en/docs/started/workstation/getting-started-windows.md
Labels: approved, cla: yes, lgtm, size/L

#2635 rename getting started to fix broken link
  content/en/docs/started/getting-started.md
Labels: approved, cla: yes, lgtm, size/XS

#2636 Updating naming to fit latest naming convention
  content/en/docs/started/getting-started.md
Labels: approved, cla: yes, lgtm, size/XS

#2638 Remove metadata
  content/en/_redirects
  content/en/docs/components/metadata.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#2640 Add Katib new UI information
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/images/new-ui.png
Labels: approved, cla: yes, lgtm, size/S

#2643 Rename `Getting Started` to `Installing Kubeflow`
  content/en/_redirects
  content/en/docs/started/installing-kubeflow.md
Labels: approved, cla: yes, lgtm, size/XS

#2646 fix broken link
  content/en/docs/reference/tfjob/v1beta2/tensorflow.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2647 Updating documentation for KF 1.3 on Openshift
  content/en/docs/distributions/openshift/OWNERS
  content/en/docs/distributions/openshift/_index.md
  content/en/docs/distributions/openshift/install-kubeflow.md
  content/en/docs/distributions/openshift/uninstall-kubeflow.md
Labels: approved, cla: yes, lgtm, size/M

#2641 Add ekf distro
  content/en/docs/distributions/_index.md
  content/en/docs/distributions/ekf/_index.md
  content/en/docs/distributions/minikf/_index.md
  content/en/docs/started/installing-kubeflow.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2650 add minikf subdir to minikf redirects
  content/en/_redirects
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2652 fix broken link
  content/en/docs/reference/tfjob/v1/tensorflow.md
Labels: approved, cla: yes, lgtm, size/XS

#2654 Headers for increased clarity of install options
  content/en/docs/started/installing-kubeflow.md
Labels: approved, cla: yes, lgtm, size/XS

#2655 change title of page and video to Introduction to Kubeflow
  content/en/docs/about/kubeflow.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2666 Update kf-latest-version.html to v1.3
  layouts/shortcodes/kf-latest-version.html
Labels: approved, cla: yes, lgtm, size/XS

#2667 Update config.toml
  config.toml
Labels: approved, cla: yes, lgtm, size/S

#2670 Kubeflow OWNERS update
  content/en/docs/components/multi-tenancy/OWNERS
  content/en/docs/components/pipelines/OWNERS
  content/en/docs/components/pipelines/sdk/OWNERS.md
  content/en/docs/distributions/azure/OWNERS
  content/en/docs/distributions/gke/OWNERS
  content/en/docs/distributions/ibm/OWNERS
  content/en/docs/distributions/ibm/deploy/OWNERS
  content/en/docs/distributions/microk8s/OWNERS
  content/en/docs/other-guides/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#2642 Update Katib doc for restarting strategies of CMA-ES
  content/en/docs/components/katib/experiment.md
Labels: approved, cla: yes, lgtm, size/XS

#2573 KFP - Updates guide to building components
  content/en/docs/components/pipelines/sdk/component-development.md
Labels: approved, cla: yes, lgtm, size/XL

#2653 KFP - Replaces the guide to building components and pipelines
  content/en/docs/components/pipelines/sdk/build-component.md
  content/en/docs/components/pipelines/sdk/build-pipeline.ipynb
  content/en/docs/components/pipelines/sdk/build-pipeline.md
Labels: approved, cla: yes, lgtm, size/XXL

#2678 Remove "Out of date"
  content/en/docs/components/multi-tenancy/design.md
Labels: approved, cla: yes, lgtm, size/XS

#2680 Fix in-document load balancer HREFs
  content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2672 fix broken link
  content/en/docs/reference/mpijob/v1alpha2/mpi.md
  content/en/docs/reference/pytorchjob/v1/pytorch.md
  content/en/docs/reference/pytorchjob/v1beta2/pytorch.md
Labels: approved, cla: yes, lgtm, size/XS

#2645 add column for version to distro table
  content/en/docs/started/installing-kubeflow.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#2681 add moficodes to ibm docs owners file
  content/en/docs/distributions/ibm/OWNERS
  content/en/docs/distributions/ibm/deploy/OWNERS
Labels: approved, cla: yes, lgtm, size/XS
