Repository kubeflow/website, pull requests merged in 2021-06, with the labels that each got.

#2749 Small fix: clarity to Charmed Operators install
  content/en/docs/distributions/charmed/install-kubeflow.md
Labels: approved, cla: yes, lgtm, size/XS

#2750 Fix broken link, linking to main install page
  content/en/docs/other-guides/kubeflow-on-multinode-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2751 notebook v1 fix links
  content/en/docs/reference/notebook/v1/_index.md
Labels: approved, cla: yes, lgtm, size/M

#2753 PR for #2718: Update Feast related broken links on Kubeflow External Add-ons page
  content/en/docs/external-add-ons/feature-store/getting-started.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#2752 Update component-development.md for which types are treated as parameters instead of artifacts
  content/en/docs/components/pipelines/sdk/v2/component-development.md
Labels: approved, cla: yes, lgtm, size/XS

#2757 Update v2-compatibility.md
  content/en/docs/components/pipelines/sdk/v2/v2-compatibility.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2754 (pipelines) Update MLMD visualization output file approach. Fix #5564
  content/en/docs/components/pipelines/sdk/output-viewer.md
  content/en/docs/images/pipelines/confusion-matrix-task.png
  content/en/docs/images/taxi-tip-prediction-step-output-table.png
Labels: approved, cla: yes, lgtm, size/M

#2761 fix Notebook web app link
  content/en/docs/reference/version-policy.md
Labels: approved, cla: yes, lgtm, size/XS

#2763 update link
  content/en/docs/distributions/gke/deploy/deploy-cli.md
Labels: approved, cla: yes, lgtm, size/XS

#2769 Update v2-compatibility.md on which types are recognized as parameter types.
  content/en/docs/components/pipelines/sdk/v2/v2-compatibility.md
Labels: approved, cla: yes, lgtm, size/XS

#2772 Update url
  content/en/docs/started/kubeflow-overview.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2773 update url
  content/en/docs/components/pipelines/overview/concepts/experiment.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2755 Describe about menu customization
  content/en/docs/components/central-dash/customizing-menu.md
  content/en/docs/images/customize-menu-add-app.png
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#2782 Resolved broken link issue for pipeline sdk
  content/en/docs/components/pipelines/sdk/install-sdk.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2781 fix markdown links
  content/en/docs/examples/blog-posts.md
Labels: approved, cla: yes, lgtm, size/XS

#2785 fix(pipelines): add visualization image back for existing reference
  content/en/docs/images/pipelines/taxi-tip-prediction-step-output-table.png
Labels: approved, cla: yes, lgtm, size/XS

#2791 fix(gke) Add explanation of GKE locations: available zones/regions
  content/en/docs/distributions/gke/deploy/management-setup.md
Labels: approved, cla: yes, lgtm, size/XS

#2786 feat(pipelines) KFP V2 visualization doc
  content/en/docs/components/pipelines/sdk/output-viewer.md
  content/en/docs/components/pipelines/sdk/v2/component-development.md
  content/en/docs/images/pipelines/v2/confusion-matrix.png
  content/en/docs/images/pipelines/v2/roc-curve.png
  content/en/docs/images/pipelines/v2/scalar-metrics.png
Labels: approved, cla: yes, lgtm, size/L

#2794 update hugo version
  README.md
  netlify.toml
Labels: approved, cla: yes, lgtm, size/S

#2798 Update Katib MySQL volume settings
  content/en/docs/components/katib/hyperparameter.md
Labels: approved, cla: yes, lgtm, size/M

#2800 Update Katib settings for FromVolume resume policy
  content/en/docs/components/katib/katib-config.md
  content/en/docs/components/katib/resume-experiment.md
Labels: approved, cla: yes, lgtm, size/M

#2801 fix(pipelines): image reference path correction
  content/en/docs/components/pipelines/sdk/output-viewer.md
Labels: approved, cla: yes, lgtm, size/XS

#2799 Update empty resources in Katib config
  content/en/docs/components/katib/katib-config.md
Labels: approved, cla: yes, lgtm, size/M
