Repository kubeflow/website, pull requests merged in 2021-01, with the labels that each got.

#2430 Small typo in AWS Deploy doc
  content/en/docs/aws/deploy/install-kubeflow.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2423 Update istio documentation to branch 1.2 for Kubeflow v1.2
  layouts/shortcodes/config-file-istio-dex.html
  layouts/shortcodes/config-file-k8s-istio.html
  layouts/shortcodes/config-uri-istio-dex.html
  layouts/shortcodes/config-uri-k8s-istio.html
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2431 Fix outdated blog url in top-level navigation
  config.toml
Labels: approved, cla: yes, lgtm, size/XS

#2438 docs: delete upgrading/_index.md
  content/en/docs/upgrading/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#2443 Update latest-version.html
  layouts/shortcodes/pipelines/latest-version.html
Labels: approved, cla: yes, lgtm, size/XS

#2428 Improve update instruction steps
  content/en/docs/gke/deploy/upgrade.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2441 Add some missing punctuation marks
  content/en/docs/components/training/tftraining.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2439 Fix KF_DIR env. var. description
  content/en/docs/gke/deploy/deploy-cli.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2409 [IBM] Update HTTPS docs with KFServing config steps
  content/en/docs/ibm/deploy/authentication.md
Labels: approved, cla: yes, lgtm, size/L

#2445 Add OWNERS file for training component documentation
  content/en/docs/components/training/OWNERS
Labels: cla: yes, lgtm, size/XS

#2440 Add yq version in docs
  content/en/docs/gke/deploy/deploy-cli.md
  content/en/docs/gke/deploy/management-setup.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2420 Fix Component spec example
  content/en/docs/pipelines/reference/component-spec.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2449 Fix url
  content/en/docs/gke/pipelines/upgrade.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2454 Add build-pipeline.ipynb
  content/en/docs/pipelines/sdk/build-pipeline.ipynb
Labels: approved, cla: yes, lgtm, size/L

#2464 Fix broken urls in KFServing docs
  content/en/docs/components/serving/kfserving.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#2462 Remove a redundant "`"
  content/en/docs/pipelines/installation/localcluster-deployment.md
Labels: approved, cla: yes, lgtm, size/XS

#2337 Update KF on MicroK8s docs
  content/en/docs/started/workstation/kubeflow-on-microk8s.md
Labels: approved, cla: yes, lgtm, size/M
