Repository kubeflow/website, pull requests merged in 2021-10, with the labels that each got.

#2981 rm RFMVasconcelos
  OWNERS
Labels: size/XS, lgtm, approved, cla: yes

#2995 Show v1.3 branch under dropdown
  config.toml
Labels: size/XS, lgtm, approved, cla: yes

#2997 Update master branch text label as `latest`
  config.toml
Labels: size/XS, lgtm, approved, cla: yes

#3009 Update Kubeflow version in Nutanix distribution docs
  content/en/docs/distributions/nutanix/install-kubeflow.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#3018 Katib: Fix links for all examples
  content/en/docs/components/katib/early-stopping.md
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/overview.md
  content/en/docs/components/katib/resume-experiment.md
  content/en/docs/components/katib/trial-template.md
Labels: lgtm, approved, size/L, cla: yes

#3002 Update links for Kubeflow Training Operator
  content/en/_index.html
  content/en/docs/components/training/job-scheduling.md
  content/en/docs/components/training/mpi.md
  content/en/docs/components/training/mxnet.md
  content/en/docs/components/training/pytorch.md
  content/en/docs/components/training/tftraining.md
  content/en/docs/components/training/xgboost.md
  content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
  content/en/docs/reference/images.md
  content/en/docs/reference/version-policy.md
  content/en/docs/started/support.md
Labels: lgtm, approved, size/L, cla: yes

#3005 remove unused images from `Getting Started`
  content/en/docs/started/ConfigInputs.png
  content/en/docs/started/LocalDeployment.png
  content/en/docs/started/kfctl_istio_dex-architecture.svg
Labels: size/XS, lgtm, approved, cla: yes

#2957 gke: Prepare Kubeflow 1.4 deployment guide.
  content/en/docs/components/pipelines/installation/overview.md
  content/en/docs/distributions/gke/deploy/deploy-cli.md
  content/en/docs/distributions/gke/deploy/management-setup.md
  content/en/docs/distributions/gke/deploy/upgrade.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/L, cla: yes

#3011 update Arrikto EKF in distributions table to 1.4
  content/en/docs/started/installing-kubeflow.md
Labels: size/XS, lgtm, approved, cla: yes

#2994 Update kfp version for IKS
  content/en/docs/started/installing-kubeflow.md
Labels: size/XS, lgtm, approved, cla: yes

#3022 pipelines: Follow up on connecting to KFP in multi-user mode.
  content/en/docs/components/pipelines/sdk/connect-api.md
Labels: lgtm, approved, size/M, cla: yes

#3019 Fixing the VPC Id retrieval command
  content/en/docs/distributions/aws/customizing-aws/rds.md
Labels: size/XS, lgtm, approved, needs-ok-to-test, cla: yes

#2986 update version variables for v1.4
  config.toml
  layouts/shortcodes/kf-latest-version.html
Labels: size/XS, lgtm, approved, cla: yes

#3017 Update kubeflow versioning policies table 1.4
  content/en/docs/reference/version-policy.md
Labels: lgtm, approved, size/S, cla: yes

#2977 update favicons
  layouts/partials/favicons.html
  static/favicons/browserconfig.xml
  static/favicons/favicon.ico
  static/favicons/manifest.json
Labels: lgtm, approved, size/S, cla: yes
