Repository kubeflow/website, pull requests merged in 2021-05, with the labels that each got.

#2674 Fix Nuclio link
  content/en/_index.html
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2691 Fixing dead link
  content/en/docs/external-add-ons/feature-store/getting-started.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2688 refactor and refresh aws docs
  content/en/docs/distributions/aws/_index.md
  content/en/docs/distributions/aws/authentication/_index.md
  content/en/docs/distributions/aws/authentication/authentication-oidc.md
  content/en/docs/distributions/aws/authentication/authentication.md
  content/en/docs/distributions/aws/aws-e2e.md
  content/en/docs/distributions/aws/custom-domain.md
  content/en/docs/distributions/aws/customizing-aws.md
  content/en/docs/distributions/aws/customizing-aws/_index.md
  content/en/docs/distributions/aws/customizing-aws/custom-domain.md
  content/en/docs/distributions/aws/customizing-aws/customizing-aws.md
  content/en/docs/distributions/aws/customizing-aws/files/rds.yaml
  content/en/docs/distributions/aws/customizing-aws/logging.md
  content/en/docs/distributions/aws/customizing-aws/private-access.md
  content/en/docs/distributions/aws/customizing-aws/rds.md
  content/en/docs/distributions/aws/customizing-aws/storage.md
  content/en/docs/distributions/aws/deploy/_index.md
  content/en/docs/distributions/aws/deploy/eks-compatibility.md
  content/en/docs/distributions/aws/deploy/features.md
  content/en/docs/distributions/aws/deploy/install-kubeflow.md
  content/en/docs/distributions/aws/deploy/uninstall-kubeflow.md
  content/en/docs/distributions/aws/features.md
  content/en/docs/distributions/aws/iam-for-sa.md
  content/en/docs/distributions/aws/logging.md
  content/en/docs/distributions/aws/notebook-server.md
  content/en/docs/distributions/aws/pipeline.md
  content/en/docs/distributions/aws/private-access.md
  content/en/docs/distributions/aws/rds.md
  content/en/docs/distributions/aws/storage.md
  content/en/docs/distributions/aws/troubleshooting-aws.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XXL

#2692 Patch no longer needed in v1.3
  content/en/docs/distributions/charmed/install-kubeflow.md
Labels: approved, cla: yes, lgtm, size/S

#2685 Update MicroK8s KF version to v1.3
  content/en/docs/started/installing-kubeflow.md
Labels: approved, cla: yes, lgtm, size/XS

#2693 update version-policy.md links
  content/en/docs/reference/version-policy.md
Labels: approved, cla: yes, lgtm, size/S

#2697 Correct links for hands-on kfserving
  content/en/docs/components/kfserving/kfserving.md
Labels: approved, cla: yes, lgtm, size/XS

#2698 Fix un-rendered note
  content/en/docs/distributions/charmed/install-kubeflow.md
Labels: approved, cla: yes, lgtm, size/XS

#2599 Remove duplicate command
  content/en/docs/components/pipelines/installation/localcluster-deployment.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2700 Replaces `xip.io` with `nip.io`
  content/en/docs/distributions/microk8s/kubeflow-on-microk8s.md
Labels: approved, cla: yes, lgtm, size/XS

#2706 KFP - Fixes broken links
  content/en/docs/components/pipelines/sdk/build-pipeline.md
  content/en/docs/components/pipelines/sdk/python-function-components.md
Labels: approved, cla: yes, lgtm, size/S

#2707 fix link
  content/en/docs/components/notebooks/setup.md
Labels: approved, cla: yes, lgtm, size/XS

#2709 delete Usage Reporting (depricated)
  content/en/docs/other-guides/usage-reporting.md
Labels: approved, cla: yes, lgtm, size/L

#2696 (GKE) Update GKE related outdated docs
  content/en/docs/distributions/gke/_index.md
  content/en/docs/distributions/gke/anthos.md
  content/en/docs/distributions/gke/authentication.md
  content/en/docs/distributions/gke/cloud-filestore.md
  content/en/docs/distributions/gke/custom-domain.md
  content/en/docs/distributions/gke/customizing-gke.md
  content/en/docs/distributions/gke/deploy/_index.md
  content/en/docs/distributions/gke/deploy/project-setup.md
  content/en/docs/distributions/gke/gcp-e2e.md
  content/en/docs/distributions/gke/monitoring.md
  content/en/docs/distributions/gke/pipelines/_index.md
  content/en/docs/distributions/gke/pipelines/authentication-pipelines.md
  content/en/docs/distributions/gke/pipelines/authentication-sdk.md
  content/en/docs/distributions/gke/pipelines/preemptible.md
  content/en/docs/distributions/gke/private-clusters.md
  content/en/docs/distributions/gke/troubleshooting-gke.md
Labels: approved, cla: yes, lgtm, size/XL

#2717 FIX: minor link fix for managed project
  content/en/docs/distributions/gke/deploy/management-setup.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2714 fix parameters.md link
  content/en/docs/components/pipelines/sdk/parameters.md
Labels: approved, cla: yes, lgtm, size/XS

#2689 Updates the KFP SDK overview
  content/en/docs/components/pipelines/sdk/sdk-overview.md
Labels: approved, cla: yes, lgtm, size/L

#2719 fix kubeflow-on-multinode-cluster.md link
  content/en/docs/other-guides/kubeflow-on-multinode-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2686 (gke) Full Kubeflow Deployment guide on GKE (revision for Kubeflow 1.3)
  content/en/docs/distributions/gke/deploy/_index.md
  content/en/docs/distributions/gke/deploy/delete-cli.md
  content/en/docs/distributions/gke/deploy/deploy-cli.md
  content/en/docs/distributions/gke/deploy/deploy-ui.md
  content/en/docs/distributions/gke/deploy/management-setup.md
  content/en/docs/distributions/gke/deploy/monitor-iap-setup.md
  content/en/docs/distributions/gke/deploy/oauth-setup.md
  content/en/docs/distributions/gke/deploy/overview.md
  content/en/docs/distributions/gke/deploy/project-setup.md
  content/en/docs/distributions/gke/deploy/reasons.md
  content/en/docs/distributions/gke/deploy/upgrade.md
  content/en/docs/distributions/gke/troubleshooting-gke.md
  content/en/docs/images/gke/full-deployment-structure.png
  content/en/docs/images/gke/full-kf-home.png
  content/en/docs/started/installing-kubeflow.md
Labels: approved, cla: yes, lgtm, size/XL

#2715 KFP: Adds SDK v2 compatibility mode docs
  content/en/docs/components/pipelines/sdk/v2/_index.md
  content/en/docs/components/pipelines/sdk/v2/build-pipeline.ipynb
  content/en/docs/components/pipelines/sdk/v2/build-pipeline.md
  content/en/docs/components/pipelines/sdk/v2/component-development.md
  content/en/docs/components/pipelines/sdk/v2/python-function-components.ipynb
  content/en/docs/components/pipelines/sdk/v2/python-function-components.md
  content/en/docs/components/pipelines/sdk/v2/v2-compatibility.md
Labels: approved, cla: yes, lgtm, size/XXL

#2723 chore: fix getting started button link to not require redirect
  content/en/_index.html
Labels: approved, cla: yes, lgtm, size/XS

#2721 fix(kfp): format fix in v2 compatible mode introduction
  content/en/docs/components/pipelines/sdk/v2/v2-compatibility.md
Labels: approved, cla: yes, lgtm, size/XS

#2725 docs(kfp): Update v2-compatibility.md
  content/en/docs/components/pipelines/sdk/v2/v2-compatibility.md
Labels: approved, cla: yes, lgtm, size/XS

#2724 Make changeable name more obvious
  content/en/docs/distributions/gke/pipelines/authentication-pipelines.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2727 Fix typo: vs ==> v2
  content/en/docs/components/pipelines/sdk/v2/build-pipeline.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2722 Adding Troubleshooting details to MicroK8s add-on
  content/en/docs/distributions/microk8s/kubeflow-on-microk8s.md
Labels: approved, cla: yes, lgtm, size/S

#2730 doc(kfp): introduce v2 compatible mode current caveats and requirements
  content/en/docs/components/pipelines/sdk/v2/v2-compatibility.md
Labels: approved, cla: yes, lgtm, size/S

#2728 update navbar on tablet & mobile
  assets/scss/_styles_project.scss
  layouts/partials/navbar-version-selector.html
  layouts/partials/navbar.html
  resources/_gen/assets/scss/scss/main.scss_4853eb546e7a6c0898ed71feae7357c0.content
  resources/_gen/assets/scss/scss/main.scss_4853eb546e7a6c0898ed71feae7357c0.json
Labels: approved, cla: yes, lgtm, size/M

#2726 Fix some commands in the delete-cli.md
  content/en/docs/distributions/gke/deploy/delete-cli.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2737 Update pipeline.md
  content/en/docs/components/pipelines/overview/concepts/pipeline.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2741 Small fix
  content/en/docs/distributions/charmed/install-kubeflow.md
Labels: approved, cla: yes, lgtm, size/XS

#2729 doc(kfp): connecting KFP SDK client to API generic introduction
  .gitignore
  content/en/docs/components/pipelines/multi-user.md
  content/en/docs/components/pipelines/sdk/build-pipeline.ipynb
  content/en/docs/components/pipelines/sdk/build-pipeline.md
  content/en/docs/components/pipelines/sdk/connect-api.md
  content/en/docs/components/pipelines/sdk/python-based-visualizations.md
  content/en/docs/components/pipelines/sdk/python-function-components.ipynb
  content/en/docs/components/pipelines/sdk/python-function-components.md
  content/en/docs/components/pipelines/sdk/v2/build-pipeline.ipynb
  content/en/docs/components/pipelines/sdk/v2/build-pipeline.md
  content/en/docs/components/pipelines/sdk/v2/python-function-components.ipynb
  content/en/docs/components/pipelines/sdk/v2/python-function-components.md
  content/en/docs/components/pipelines/sdk/v2/v2-compatibility.md
  scripts/kfp_nb_to_md.sh
Labels: approved, cla: yes, lgtm, size/XL

#2733 TFJob Common fix links
  content/en/docs/reference/tfjob/v1beta2/common.md
Labels: approved, cla: yes, lgtm, size/S

#2743 TFJob v1 Common fix links
  content/en/docs/reference/tfjob/v1/common.md
Labels: approved, cla: yes, lgtm, size/S

#2745 Fix broken link
  content/en/docs/components/pipelines/overview/concepts/run-trigger.md
Labels: approved, cla: yes, lgtm, size/XS
