Repository kubeflow/website, pull requests merged in 2022-06, with the labels that each got.

#3269 fix slack invite link
  content/en/docs/about/community.md
Labels: size/XS, lgtm, approved

#3278 release KFP 1.8.2
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved

#3238 Redirect to AWS landing page
  content/en/_redirects
Labels: size/XS, lgtm, approved

#3285 Katib: Population based training algorithm section
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/katib-config.md
Labels: lgtm, approved, size/M, ok-to-test

#3286 pipelines: Update backend API reference doc to the latest
  content/en/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec.html
Labels: size/XXL, lgtm, approved

#3288 pipeline: Add title section to enable navigation in KFP API reference doc
  content/en/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec.html
Labels: size/XS, lgtm, approved
