Repository kubeflow/website, pull requests merged in 2022-03, with the labels that each got.

#3153 fix broken MNIST link
  content/en/docs/started/architecture.md
Labels: size/XS, lgtm, approved

#3167 Update KFP standalone-deployment.md on applying GCP Cloud SQL config
  content/en/docs/components/pipelines/installation/standalone-deployment.md
Labels: size/XS, lgtm, approved

#3169 Minimized AWS Docs for Kubeflow 1.3.1
  content/en/docs/distributions/aws/authentication/_index.md
  content/en/docs/distributions/aws/authentication/authentication-oidc.md
  content/en/docs/distributions/aws/authentication/authentication.md
  content/en/docs/distributions/aws/aws-e2e.md
  content/en/docs/distributions/aws/component-guides/_index.md
  content/en/docs/distributions/aws/component-guides/files/rds.yaml
  content/en/docs/distributions/aws/component-guides/notebook-server.md
  content/en/docs/distributions/aws/component-guides/pipeline.md
  content/en/docs/distributions/aws/customizing-aws/_index.md
  content/en/docs/distributions/aws/customizing-aws/custom-domain.md
  content/en/docs/distributions/aws/customizing-aws/customizing-aws.md
  content/en/docs/distributions/aws/customizing-aws/logging.md
  content/en/docs/distributions/aws/customizing-aws/private-access.md
  content/en/docs/distributions/aws/customizing-aws/rds.md
  content/en/docs/distributions/aws/customizing-aws/storage.md
  content/en/docs/distributions/aws/deploy/_index.md
  content/en/docs/distributions/aws/deploy/eks-compatibility.md
  content/en/docs/distributions/aws/deploy/features.md
  content/en/docs/distributions/aws/deploy/install-kubeflow.md
  content/en/docs/distributions/aws/deploy/uninstall-kubeflow.md
  content/en/docs/distributions/aws/notebook-server.md
  content/en/docs/distributions/aws/pipeline.md
  content/en/docs/distributions/aws/troubleshooting-aws.md
Labels: size/XXL, lgtm, approved, ok-to-test

#3170 update OWNERS for v1.3-branch AWS distro docs
  content/en/docs/distributions/aws/OWNERS
Labels: size/XS, lgtm, approved

#3171 update OWNERS for v1.4-branch AWS distro docs
  content/en/docs/distributions/aws/OWNERS
Labels: size/XS, lgtm, approved

#3168 Adding chensun as an approver
  OWNERS
Labels: size/XS, lgtm, approved

#3176 Fixed changed Kubeflow Pipelines on AWS link
  content/en/docs/components/pipelines/sdk/connect-api.md
Labels: size/XS, lgtm, approved, needs-ok-to-test

#3175 Adding minimized v1.3 AWS docs to 1.4 Kubeflow site branch
  content/en/docs/distributions/aws/OWNERS
  content/en/docs/distributions/aws/_index.md
  content/en/docs/distributions/aws/authentication/_index.md
  content/en/docs/distributions/aws/authentication/authentication-oidc.md
  content/en/docs/distributions/aws/authentication/authentication.md
  content/en/docs/distributions/aws/aws-e2e.md
  content/en/docs/distributions/aws/component-guides/_index.md
  content/en/docs/distributions/aws/component-guides/files/rds.yaml
  content/en/docs/distributions/aws/component-guides/notebook-server.md
  content/en/docs/distributions/aws/component-guides/pipeline.md
  content/en/docs/distributions/aws/customizing-aws/_index.md
  content/en/docs/distributions/aws/customizing-aws/custom-domain.md
  content/en/docs/distributions/aws/customizing-aws/customizing-aws.md
  content/en/docs/distributions/aws/customizing-aws/logging.md
  content/en/docs/distributions/aws/customizing-aws/private-access.md
  content/en/docs/distributions/aws/customizing-aws/rds.md
  content/en/docs/distributions/aws/customizing-aws/storage.md
  content/en/docs/distributions/aws/deploy/_index.md
  content/en/docs/distributions/aws/deploy/eks-compatibility.md
  content/en/docs/distributions/aws/deploy/features.md
  content/en/docs/distributions/aws/deploy/install-kubeflow.md
  content/en/docs/distributions/aws/deploy/uninstall-kubeflow.md
  content/en/docs/distributions/aws/notebook-server.md
  content/en/docs/distributions/aws/pipeline.md
  content/en/docs/distributions/aws/troubleshooting-aws.md
Labels: size/XXL, lgtm, approved, ok-to-test

#3174 Added AWS 1.3 documentation to Kubeflow site (v1.3 branch)
  content/en/docs/distributions/aws/OWNERS
  content/en/docs/distributions/aws/_index.md
  content/en/docs/distributions/aws/authentication/_index.md
  content/en/docs/distributions/aws/authentication/authentication-oidc.md
  content/en/docs/distributions/aws/authentication/authentication.md
  content/en/docs/distributions/aws/aws-e2e.md
  content/en/docs/distributions/aws/component-guides/_index.md
  content/en/docs/distributions/aws/component-guides/files/rds.yaml
  content/en/docs/distributions/aws/component-guides/notebook-server.md
  content/en/docs/distributions/aws/component-guides/pipeline.md
  content/en/docs/distributions/aws/customizing-aws/_index.md
  content/en/docs/distributions/aws/customizing-aws/custom-domain.md
  content/en/docs/distributions/aws/customizing-aws/customizing-aws.md
  content/en/docs/distributions/aws/customizing-aws/logging.md
  content/en/docs/distributions/aws/customizing-aws/private-access.md
  content/en/docs/distributions/aws/customizing-aws/rds.md
  content/en/docs/distributions/aws/customizing-aws/storage.md
  content/en/docs/distributions/aws/deploy/_index.md
  content/en/docs/distributions/aws/deploy/eks-compatibility.md
  content/en/docs/distributions/aws/deploy/features.md
  content/en/docs/distributions/aws/deploy/install-kubeflow.md
  content/en/docs/distributions/aws/deploy/uninstall-kubeflow.md
  content/en/docs/distributions/aws/notebook-server.md
  content/en/docs/distributions/aws/pipeline.md
  content/en/docs/distributions/aws/troubleshooting-aws.md
Labels: size/XXL, lgtm, approved, ok-to-test

#3186 Added missing index page
  content/en/docs/distributions/aws/_index.md
Labels: size/XS, lgtm, approved, needs-ok-to-test

#3187 Added missing index file
  content/en/docs/distributions/aws/_index.md
Labels: size/XS, lgtm, approved, needs-ok-to-test

#3173 Update IKS doc for kubeflow v1.5
  content/en/docs/distributions/ibm/deploy/authentication.md
  content/en/docs/distributions/ibm/deploy/iks-compatibility.md
  content/en/docs/distributions/ibm/deploy/install-kubeflow-on-iks.md
  content/en/docs/distributions/ibm/deploy/uninstall-kubeflow.md
Labels: lgtm, approved, size/M

#3162 Move KFServing to External Addons, Change file names to kserve, modify kserve.md, add migration File
  content/en/_redirects
  content/en/docs/components/kfserving/_index.md
  content/en/docs/components/kfserving/kfserving.md
  content/en/docs/components/kfserving/kfserving.png
  content/en/docs/external-add-ons/kserve/OWNERS
  content/en/docs/external-add-ons/kserve/_index.md
  content/en/docs/external-add-ons/kserve/first_isvc_kserve.ipynb
  content/en/docs/external-add-ons/kserve/first_isvc_kserve.md
  content/en/docs/external-add-ons/kserve/iris-input.json
  content/en/docs/external-add-ons/kserve/kserve.md
  content/en/docs/external-add-ons/kserve/migration.md
  content/en/docs/external-add-ons/kserve/pics/kserve.png
  content/en/docs/external-add-ons/kserve/pics/webapp-list.png
  content/en/docs/external-add-ons/kserve/pics/webapp-metrics.png
  content/en/docs/external-add-ons/kserve/pics/webapp-new.png
  content/en/docs/external-add-ons/kserve/pics/webapp-overview.png
  content/en/docs/external-add-ons/kserve/webapp.md
Labels: lgtm, approved, size/XL

#3179 charmed kubeflow: updates command for creating controller
  content/en/docs/distributions/charmed/install-kubeflow.md
Labels: size/XS, lgtm, approved

#3191 Update AWS distribution version
  content/en/docs/distributions/aws/deploy/eks-compatibility.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/S

#3183 updated path to component-sdk-v2.yaml
  content/en/docs/components/pipelines/sdk-v2/build-pipeline.ipynb
Labels: size/XS, lgtm, approved, ok-to-test

#3193 minikf: Update to v1.4
  content/en/docs/started/installing-kubeflow.md
Labels: size/XS, lgtm, approved

#3194 1.5 release page
  content/en/docs/releases/kubeflow-1.5.md
Labels: lgtm, approved, size/L

#3184 Add 1.5 to version dropdown.
  config.toml
Labels: size/XS, lgtm, approved

#3185 Make 1.5.0 the latest version.
  layouts/shortcodes/kf-latest-version.html
Labels: size/XS, lgtm, approved

#3023 doc: update profile creation defaults to match current manifests
  content/en/docs/components/multi-tenancy/getting-started.md
  content/en/docs/distributions/gke/deploy/deploy-cli.md
Labels: lgtm, approved, size/M, cla: yes

#3196 fix incorrect redirect for pipelines introduction
  content/en/_redirects
Labels: size/XS, lgtm, approved

#3199 Charmed Kubeflow: Remove workaround option for creating controller
  content/en/docs/distributions/charmed/install-kubeflow.md
Labels: size/XS, lgtm, approved

#3188 Fixed broken AWS Pipelines link for 1.3 docs branch
  content/en/docs/components/pipelines/sdk/connect-api.md
Labels: size/XS, lgtm, approved, ok-to-test

#3201 Update Nutanix Karbon supported version to Kubeflow 1.5 release
  content/en/docs/distributions/nutanix/install-kubeflow.md
  content/en/docs/started/installing-kubeflow.md
  layouts/shortcodes/nutanix/OWNERS
  layouts/shortcodes/nutanix/latest-version.html
Labels: lgtm, approved, size/S

#3210 slack: Update slack invite link. Fix #3204
  content/en/docs/about/community.md
Labels: size/XS, lgtm, approved

#3127 Fixed web_downloader_op link
  content/en/docs/components/pipelines/sdk/build-pipeline.md
Labels: size/XS, lgtm, approved, needs-ok-to-test
