Repository kubeflow/website, pull requests merged in 2022-04, with the labels that each got.

#3219 Add documentation on Katib's JSON format logs
  content/en/docs/components/katib/experiment.md
Labels: lgtm, approved, size/S

#3220 Removed configuration with AWS credentials section
  content/en/docs/distributions/aws/component-guides/pipeline.md
Labels: lgtm, approved, needs-ok-to-test, size/M

#3230 slack: Update slack invite link. Fix #3226
  content/en/docs/about/community.md
Labels: size/XS, lgtm, approved

#3233 Generalize Kubeflow on AWS docs
  content/en/docs/distributions/aws/_index.md
  content/en/docs/distributions/aws/component-guides/_index.md
  content/en/docs/distributions/aws/component-guides/files/rds.yaml
  content/en/docs/distributions/aws/component-guides/notebook-server.md
  content/en/docs/distributions/aws/component-guides/pipeline.md
  content/en/docs/distributions/aws/customizing-aws/_index.md
  content/en/docs/distributions/aws/customizing-aws/rds.md
  content/en/docs/distributions/aws/deploy/_index.md
  content/en/docs/distributions/aws/deploy/eks-compatibility.md
  content/en/docs/distributions/aws/deploy/features.md
  content/en/docs/distributions/aws/deploy/install-kubeflow.md
  content/en/docs/distributions/aws/deploy/uninstall-kubeflow.md
  content/en/docs/distributions/aws/troubleshooting-aws.md
Labels: lgtm, approved, needs-ok-to-test, size/XL

#3234 Point to AWS website for v1.4
  content/en/docs/distributions/aws/_index.md
  content/en/docs/distributions/aws/component-guides/_index.md
  content/en/docs/distributions/aws/component-guides/files/rds.yaml
  content/en/docs/distributions/aws/component-guides/notebook-server.md
  content/en/docs/distributions/aws/component-guides/pipeline.md
  content/en/docs/distributions/aws/customizing-aws/_index.md
  content/en/docs/distributions/aws/customizing-aws/rds.md
  content/en/docs/distributions/aws/deploy/_index.md
  content/en/docs/distributions/aws/deploy/eks-compatibility.md
  content/en/docs/distributions/aws/deploy/features.md
  content/en/docs/distributions/aws/deploy/install-kubeflow.md
  content/en/docs/distributions/aws/deploy/uninstall-kubeflow.md
  content/en/docs/distributions/aws/troubleshooting-aws.md
Labels: lgtm, approved, size/XL

#3236 Point to AWS website for v1.5
  content/en/docs/distributions/aws/_index.md
  content/en/docs/distributions/aws/component-guides/_index.md
  content/en/docs/distributions/aws/component-guides/files/rds.yaml
  content/en/docs/distributions/aws/component-guides/notebook-server.md
  content/en/docs/distributions/aws/component-guides/pipeline.md
  content/en/docs/distributions/aws/customizing-aws/_index.md
  content/en/docs/distributions/aws/customizing-aws/rds.md
  content/en/docs/distributions/aws/deploy/_index.md
  content/en/docs/distributions/aws/deploy/eks-compatibility.md
  content/en/docs/distributions/aws/deploy/features.md
  content/en/docs/distributions/aws/deploy/install-kubeflow.md
  content/en/docs/distributions/aws/deploy/uninstall-kubeflow.md
  content/en/docs/distributions/aws/troubleshooting-aws.md
Labels: lgtm, approved, size/XL
