Repository kubeflow/website, pull requests merged in 2022-02, with the labels that each got.

#3139 Add 1.4.1 release
  content/en/docs/releases/kubeflow-1.4.md
Labels: lgtm, approved, size/L

#3141 GKE: Apply 1.4.1 Kubeflow on GCP and added shortcode
  content/en/docs/distributions/gke/deploy/deploy-cli.md
  content/en/docs/distributions/gke/deploy/management-setup.md
  layouts/shortcodes/gke/OWNERS
  layouts/shortcodes/gke/latest-version.html
Labels: lgtm, approved, size/S

#3143 Remove MiniKF on Vagrant installation page
  content/en/docs/distributions/minikf/minikf-vagrant.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/L, ok-to-test

#3148 Update Canonical distro listings
  content/en/docs/distributions/charmed/OWNERS
  content/en/docs/distributions/charmed/_index.md
  content/en/docs/distributions/charmed/install-kubeflow.md
  content/en/docs/distributions/microk8s/OWNERS
  content/en/docs/distributions/microk8s/_index.md
  content/en/docs/distributions/microk8s/kubeflow-on-microk8s.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/L, ok-to-test

#3152 pipelines: Upgrade version to 1.8.0
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved

#3155 pipelines: Update layouts/shortcodes/pipelines/OWNERS
  layouts/shortcodes/pipelines/OWNERS
Labels: lgtm, approved, size/S

#3156 gke: Documentation for Config Controller
  content/en/docs/distributions/gke/deploy/delete-cli.md
  content/en/docs/distributions/gke/deploy/deploy-cli.md
  content/en/docs/distributions/gke/deploy/management-setup.md
  content/en/docs/distributions/gke/deploy/project-setup.md
  content/en/docs/distributions/gke/deploy/upgrade.md
Labels: lgtm, approved, size/L

#3158 gke: upgrade to 1.5.0-rc.0
  layouts/shortcodes/gke/latest-version.html
Labels: size/XS, lgtm, approved

#3154 assorted style/typo fixes
  content/en/docs/components/pipelines/overview/caching-v2.md
  content/en/docs/components/pipelines/overview/caching.md
  content/en/docs/components/pipelines/overview/multi-user.md
  content/en/docs/components/pipelines/overview/pipeline-root.md
  content/en/docs/components/pipelines/sdk/best-practices.md
  content/en/docs/components/pipelines/sdk/component-development.md
  content/en/docs/components/pipelines/sdk/output-viewer.md
  content/en/docs/components/pipelines/sdk/python-function-components.ipynb
  content/en/docs/components/pipelines/sdk/python-function-components.md
  content/en/docs/components/pipelines/sdk/sdk-overview.md
  content/en/docs/components/pipelines/sdk/static-type-checking.md
Labels: lgtm, approved, size/M
