Repository kubeflow/website, pull requests merged in 2022-05, with the labels that each got.

#3240 fix: use canonical v1 link throughout pipelines docs
  content/en/docs/components/pipelines/installation/standalone-deployment.md
  content/en/docs/components/pipelines/introduction.md
  content/en/docs/components/pipelines/overview/quickstart.md
  content/en/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec.html
  content/en/docs/components/pipelines/reference/component-spec.md
  content/en/docs/components/pipelines/sdk-v2/build-pipeline.ipynb
  content/en/docs/components/pipelines/sdk-v2/build-pipeline.md
  content/en/docs/components/pipelines/sdk-v2/component-development.md
  content/en/docs/components/pipelines/sdk-v2/python-function-components.ipynb
  content/en/docs/components/pipelines/sdk-v2/python-function-components.md
  content/en/docs/components/pipelines/sdk-v2/v2-compatibility.md
  content/en/docs/components/pipelines/sdk/build-pipeline.ipynb
  content/en/docs/components/pipelines/sdk/build-pipeline.md
  content/en/docs/components/pipelines/sdk/component-development.md
  content/en/docs/components/pipelines/sdk/connect-api.md
  content/en/docs/components/pipelines/sdk/dsl-recursion.md
  content/en/docs/components/pipelines/sdk/install-sdk.md
  content/en/docs/components/pipelines/sdk/manipulate-resources.md
  content/en/docs/components/pipelines/sdk/output-viewer.md
  content/en/docs/components/pipelines/sdk/pipelines-metrics.md
  content/en/docs/components/pipelines/sdk/python-based-visualizations.md
  content/en/docs/components/pipelines/sdk/sdk-overview.md
  content/en/docs/components/pipelines/sdk/static-type-checking.md
  content/en/docs/components/pipelines/tutorials/api-pipelines.md
  content/en/docs/components/pipelines/tutorials/benchmark-examples.md
  content/en/docs/components/pipelines/tutorials/build-pipeline.md
  content/en/docs/components/pipelines/tutorials/sdk-examples.md
  content/en/docs/distributions/azure/azureMySQL.md
  content/en/docs/distributions/azure/machinelearningcomponent.md
  content/en/docs/distributions/gke/pipelines/authentication-pipelines.md
  content/en/docs/distributions/gke/pipelines/authentication-sdk.md
  content/en/docs/distributions/gke/pipelines/enable-gpu-and-tpu.md
  content/en/docs/distributions/gke/pipelines/preemptible.md
  content/en/docs/distributions/gke/pipelines/upgrade.md
  content/en/docs/external-add-ons/kserve/first_isvc_kserve.ipynb
  content/en/docs/external-add-ons/kserve/first_isvc_kserve.md
Labels: lgtm, approved, size/L

#3247 Updating Arrikto Distributions
  content/en/docs/distributions/kfaas/_index.md
  content/en/docs/distributions/minikf/_index.md
  content/en/docs/distributions/minikf/minikf-aws.md
  content/en/docs/distributions/minikf/minikf-gcp.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/L, ok-to-test

#3256 [IKS] Update cluster creation instructions
  content/en/docs/distributions/ibm/create-cluster.md
Labels: lgtm, approved, size/S

#3257 Fix: fix broken images by using consistent path. Fixes #3250
  content/en/docs/external-add-ons/elyra/_index.md
  content/en/docs/external-add-ons/kserve/kserve.md
  content/en/docs/external-add-ons/kserve/webapp.md
Labels: lgtm, approved, size/S, ok-to-test
