Repository kubeflow/website, pull requests merged in 2022-09, with the labels that each got.

#3343 Bump KFP version to 1.8.5
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved

#3317 add kfp v2 quickstart
  content/en/docs/components/pipelines/quickstart.md
  content/en/docs/images/pipelines/addition_pipeline_ui.png
Labels: lgtm, approved, size/L

#3328 add kfp v2 community and support
  content/en/docs/components/pipelines/community-and-support.md
Labels: lgtm, approved, size/M

#3318 add kfp v2 cli
  content/en/docs/components/pipelines/cli.md
  content/en/docs/components/pipelines/cli/_index.md
Labels: lgtm, approved, size/L

#3320 add kfp v2 authoring/components
  content/en/docs/components/pipelines/author-a-pipeline/components.md
Labels: lgtm, approved, size/L

#3315 add bring your own container doc for kfp sdk
  content/en/docs/components/pipelines/author-a-pipelines/bring_your_own_container.md
Labels: lgtm, approved, size/L, ok-to-test

#3329 add kfp v2 introduction
  content/en/docs/components/pipelines/introduction.md
Labels: lgtm, approved, size/L

#3340 Update the version for IKS
  content/en/docs/started/installing-kubeflow.md
  layouts/shortcodes/iks/OWNERS
  layouts/shortcodes/iks/latest-branch.html
  layouts/shortcodes/iks/latest-version.html
Labels: lgtm, approved, size/S

#3342 Update OpenShift docs for KF 1.6
  content/en/docs/distributions/openshift/_index.md
  content/en/docs/distributions/openshift/install-kubeflow.md
  content/en/docs/distributions/openshift/uninstall-kubeflow.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, needs-ok-to-test, size/M

#3349 Update Charmed Kubeflow Documentation for 1.6
  content/en/docs/distributions/charmed/_index.md
  content/en/docs/distributions/charmed/install-kubeflow.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/L

#3332 Add kubeflow 1.6 release page
  content/en/docs/releases/kubeflow-1.6.md
Labels: lgtm, approved, size/L

#3333 Add 1.6 version dropdown and make it latest version
  config.toml
  layouts/shortcodes/kf-latest-version.html
Labels: lgtm, approved, size/S

#3354 Update docs to v1.6
  content/en/docs/distributions/gke/deploy/deploy-cli.md
  content/en/docs/distributions/gke/deploy/project-setup.md
  content/en/docs/distributions/gke/deploy/upgrade.md
  layouts/shortcodes/gke/latest-version.html
Labels: lgtm, approved, size/S

#3355 Update config to v1.6
  config.toml
Labels: size/XS, lgtm, approved

#3356 Cherry-pick GKE updates
  content/en/docs/distributions/gke/deploy/deploy-cli.md
  content/en/docs/distributions/gke/deploy/project-setup.md
  content/en/docs/distributions/gke/deploy/upgrade.md
  layouts/shortcodes/gke/latest-version.html
Labels: lgtm, approved, size/S

#3353 adding Oracle to Distribution table
  content/en/docs/started/installing-kubeflow.md
Labels: size/XS, lgtm, approved

#3326 add kfp v2 compile a pipeline
  content/en/docs/components/pipelines/compile-a-pipeline.md
  content/en/docs/components/pipelines/compile-a-pipeline/_index.md
Labels: lgtm, approved, size/L

#3327 add kfp v2 run a pipeline
  content/en/docs/components/pipelines/run-a-pipeline.md
  content/en/docs/components/pipelines/run-a-pipeline/_index.md
  content/en/docs/images/pipelines/create-run.png
  content/en/docs/images/pipelines/start-a-run.png
  content/en/docs/images/pipelines/submit-a-pipeline-on-dashboard.png
  content/en/docs/images/pipelines/upload-a-pipeline.png
Labels: lgtm, approved, size/M

#3322 add kfp v2 authoring/tasks
  content/en/docs/components/pipelines/author-a-pipeline/tasks.md
Labels: lgtm, approved, size/L

#3330 add kfp v2 component i/o
  content/en/docs/components/pipelines/author-a-pipeline/inputs-outputs-data-passing.md
Labels: lgtm, approved, size/L

#3350 Integrate CUJ 3 documentation into components.md
  content/en/docs/components/pipelines/author-a-pipeline/components.md
  content/en/docs/components/pipelines/author-a-pipelines/bring_your_own_container.md
Labels: lgtm, approved, size/L

#3334 add kfp v2 authoring/pipelines documentation
  content/en/docs/components/pipelines/author-a-pipeline/pipelines.md
Labels: lgtm, approved, size/L

#3337 [katib] support postgres db
  content/en/docs/components/katib/env-variables.md
Labels: lgtm, approved, size/M

#3359 Restructure and fix links for pipelines docs
  content/en/_redirects
  content/en/docs/components/pipelines/component-registry.md
  content/en/docs/components/pipelines/conformant-platforms.md
  content/en/docs/components/pipelines/reference.md
  content/en/docs/components/pipelines/user-interface/_index.md
  content/en/docs/components/pipelines/v2/_index.md
  content/en/docs/components/pipelines/v2/author-a-pipeline/_index.md
  content/en/docs/components/pipelines/v2/author-a-pipeline/component-io.md
  content/en/docs/components/pipelines/v2/author-a-pipeline/components.md
  content/en/docs/components/pipelines/v2/author-a-pipeline/pipelines.md
  content/en/docs/components/pipelines/v2/author-a-pipeline/tasks.md
  content/en/docs/components/pipelines/v2/cli.md
  content/en/docs/components/pipelines/v2/community-and-support.md
  content/en/docs/components/pipelines/v2/compile-a-pipeline.md
  content/en/docs/components/pipelines/v2/installation.md
  content/en/docs/components/pipelines/v2/introduction.md
  content/en/docs/components/pipelines/v2/quickstart.md
  content/en/docs/components/pipelines/v2/reference.md
  content/en/docs/components/pipelines/v2/run-a-pipeline.md
Labels: size/L

#3363 fix pipelines file location
  content/en/docs/components/pipelines/v1/sdk-v2/run-comparison.md
Labels: size/XS, lgtm, approved

#3344 add kfp v1 importer docs
  content/en/docs/components/pipelines/v1/sdk-v2/importer-component.md
Labels: lgtm, approved, size/M

#3365 update the community information page
  config.toml
  content/en/_index.html
  content/en/docs/about/community.md
  content/en/docs/started/support.md
Labels: lgtm, approved, size/M

#3021 improve docs for connecting Pipelines SDK to Kubeflow
  content/en/docs/components/pipelines/v1/overview/multi-user.md
  content/en/docs/components/pipelines/v1/sdk/connect-api.md
Labels: lgtm, approved, size/XL, cla: yes

#3358 Add link to release video
  content/en/docs/releases/kubeflow-1.6.md
Labels: size/XS, lgtm, approved
