Repository kubeflow/website, pull requests merged in 2022-10, with the labels that each got.

#3366 v2 documentation - review of Introduction and Quick Start topics
  content/en/docs/components/pipelines/v2/installation.md
  content/en/docs/components/pipelines/v2/introduction.md
  content/en/docs/components/pipelines/v2/quickstart.md
Labels: lgtm, approved, size/L, ok-to-test

#3377 Update KF GCP deployment instructions to use the new manifest repo
  content/en/docs/distributions/gke/deploy/deploy-cli.md
  content/en/docs/distributions/gke/deploy/management-setup.md
Labels: lgtm, approved, size/M

#3383 update AWS distro version on 1.6 release branch
  layouts/shortcodes/aws/latest-version.html
Labels: size/XS, lgtm, approved

#3382 Update AWS distribution version to 1.6.1
  layouts/shortcodes/aws/latest-version.html
Labels: size/XS, lgtm, approved

#3384 Bump version to 1.6.1
  layouts/shortcodes/gke/latest-version.html
Labels: size/XS, lgtm, approved

#3373 Add 1.6.1 info
  content/en/docs/releases/kubeflow-1.6.md
Labels: lgtm, approved, size/L
