Repository kubeflow/website, pull requests merged in 2022-12, with the labels that each got.

#3411 Fix typos on GKE deployment page
  content/en/docs/distributions/gke/deploy/deploy-cli.md
Labels: size/XS, lgtm, approved

#3412 Add Netlify deploy status badge
  README.md
Labels: size/XS, lgtm, approved

#3410 Mark MPI-operator as beta
  content/en/docs/components/training/mpi.md
Labels: size/XS, lgtm, approved

#3396 Add Kubeflow on VMware vSphere documentation
  content/en/docs/started/installing-kubeflow.md
Labels: size/XS, lgtm, approved, ok-to-test

#3415 Update component-io.md
  content/en/docs/components/pipelines/v2/author-a-pipeline/component-io.md
Labels: size/XS, lgtm, approved

#3392 Completed initial TW review for topic "Command Line Interface"
  content/en/docs/components/pipelines/v2/cli.md
Labels: lgtm, approved, size/L, ok-to-test

#3393 Completed initial TW review for topic "Compile a pipeline"
  content/en/docs/components/pipelines/v2/compile-a-pipeline.md
Labels: lgtm, approved, size/L, ok-to-test

#3406 update content links
  content/en/docs/about/community.md
  content/en/docs/about/style-guide.md
  content/en/docs/components/central-dash/customizing-menu.md
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/pipelines/v1/reference/component-spec.md
  content/en/docs/components/pipelines/v1/sdk-v2/v2-compatibility.md
  content/en/docs/components/training/tftraining.md
  content/en/docs/distributions/ibm/iks-e2e.md
  content/en/docs/external-add-ons/feature-store/getting-started.md
  content/en/docs/external-add-ons/feature-store/overview.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/M
