Repository kubeflow/website, pull requests merged in 2022-01, with the labels that each got.

#3114 fix netlify build command
  netlify.toml
Labels: size/XS, lgtm, approved

#3108 pipelines: Announce the Emissary Executor being default starting KFP 1.8
  content/en/docs/components/pipelines/installation/choose-executor.md
  content/en/docs/components/pipelines/installation/standalone-deployment.md
Labels: lgtm, approved, size/S

#3112 use hugo 0.91.2
  netlify.toml
  package-lock.json
  package.json
Labels: lgtm, approved, size/S

#3102 fix nav menu on hover
  assets/scss/_styles_project.scss
Labels: size/XS, lgtm, approved

#3118 update hugo
  README.md
  netlify.toml
Labels: lgtm, approved, size/S

#3125 Update AWS distro docs owners
  content/en/docs/distributions/aws/OWNERS
Labels: size/XS, lgtm, approved

#3121 Fixed Deploy RDS Commands Not Working For All Output Formats Preferences
  content/en/docs/distributions/aws/customizing-aws/rds.md
Labels: size/XS, lgtm, approved, ok-to-test

#3123 Update install-kubeflow.md for latest Charmed Kubeflow
  content/en/docs/distributions/charmed/install-kubeflow.md
  content/en/docs/started/installing-kubeflow.md
Labels: size/XS, lgtm, approved
