Repository kubeflow/website, pull requests merged in 2023-04, with the labels that each got.

#3469 update IKS version
  content/en/docs/started/installing-kubeflow.md
  layouts/shortcodes/iks/latest-branch.html
  layouts/shortcodes/iks/latest-version.html
Labels: lgtm, approved, size/S

#3490 Clean up KFP v2 pipeline documentation: compile-a-pipeline
  content/en/docs/components/pipelines/v2/compile-a-pipeline.md
Labels: lgtm, approved, needs-ok-to-test, size/S

#3488 add kfp v2 keywords to pipelines documentation
  content/en/docs/components/pipelines/v1/sdk-v2/_index.md
  content/en/docs/components/pipelines/v1/sdk-v2/component-development.md
  content/en/docs/components/pipelines/v1/sdk-v2/importer-component.md
  content/en/docs/components/pipelines/v1/sdk-v2/v2-compatibility.md
  content/en/docs/components/pipelines/v1/sdk-v2/v2-component-io.md
  content/en/docs/components/pipelines/v2/_index.md
  content/en/docs/components/pipelines/v2/cli.md
  content/en/docs/components/pipelines/v2/community-and-support.md
  content/en/docs/components/pipelines/v2/compile-a-pipeline.md
  content/en/docs/components/pipelines/v2/components/_index.md
  content/en/docs/components/pipelines/v2/components/container-components.md
  content/en/docs/components/pipelines/v2/components/containerized-python-components.md
  content/en/docs/components/pipelines/v2/components/importer-component.md
  content/en/docs/components/pipelines/v2/components/lightweight-python-components.md
  content/en/docs/components/pipelines/v2/data-types/_index.md
  content/en/docs/components/pipelines/v2/data-types/artifacts.md
  content/en/docs/components/pipelines/v2/data-types/parameters.md
  content/en/docs/components/pipelines/v2/hello-world.md
  content/en/docs/components/pipelines/v2/installation/_index.md
  content/en/docs/components/pipelines/v2/installation/quickstart.md
  content/en/docs/components/pipelines/v2/introduction.md
  content/en/docs/components/pipelines/v2/load-and-share-components.md
  content/en/docs/components/pipelines/v2/migration.md
  content/en/docs/components/pipelines/v2/pipelines/_index.md
  content/en/docs/components/pipelines/v2/pipelines/control-flow.md
  content/en/docs/components/pipelines/v2/pipelines/pipeline-basics.md
  content/en/docs/components/pipelines/v2/run-a-pipeline.md
  layouts/shortcodes/kfp-v2-keywords.html
  layouts/shortcodes/no-index.html
Labels: lgtm, approved, size/M

#3489 add note on setting component env in KFP SDK v2 migration docs
  content/en/docs/components/pipelines/v2/migration.md
Labels: size/XS, lgtm, approved

#3492 re-add placeholder and special input value content to v2 KFP docs
  content/en/docs/components/pipelines/v2/components/container-components.md
  content/en/docs/components/pipelines/v2/pipelines/pipeline-basics.md
Labels: lgtm, approved, size/M

#3476 Add Kubeflow 1.7 Release Page
  content/en/docs/releases/kubeflow-1.7.md
Labels: lgtm, approved, size/L

#3493 Update pipelines v2 API reference doc
  content/en/docs/components/pipelines/v2/reference/api/kubeflow-pipeline-api-spec.html
Labels: size/XXL, lgtm, approved

#3474 docs: bump Charmed Kubeflow supported version 1.6.1->1.7.0
  content/en/docs/started/installing-kubeflow.md
Labels: size/XS, lgtm, approved

#3477 Add 1.7 version dropdown and make it latest version
  config.toml
  layouts/shortcodes/kf-latest-version.html
Labels: size/XS, lgtm, approved

#3453 MPI-Operator: Add docs for the schedulingPolicy
  content/en/docs/components/training/job-scheduling.md
  content/en/docs/components/training/mpi.md
Labels: lgtm, approved, size/L

#3497 Update artifacts.md
  content/en/docs/components/pipelines/v2/data-types/artifacts.md
Labels: lgtm, approved, size/S

#3496 add platform-specific features docs
  content/en/docs/components/pipelines/v2/platform-specific-features.md
Labels: lgtm, approved, size/L

#3503 Update AWS Kubeflow distribution latest version to 1.7.0 in website
  layouts/shortcodes/aws/latest-version.html
Labels: size/XS, lgtm, approved

#3504 [Cherry-pick] Update AWS Kubeflow distribution latest version to 1.7.0 in website
  layouts/shortcodes/aws/latest-version.html
Labels: size/XS, lgtm, approved
