Repository kubeflow/website, pull requests merged in 2023-10, with the labels that each got.

#3553 remove kubeflow fairing docs (project is archived)
  content/en/docs/external-add-ons/fairing/_index.md
  content/en/docs/external-add-ons/fairing/azure/_index.md
  content/en/docs/external-add-ons/fairing/configure-fairing.md
  content/en/docs/external-add-ons/fairing/fairing-overview.md
  content/en/docs/external-add-ons/fairing/gcp/_index.md
  content/en/docs/external-add-ons/fairing/gcp/configure-gcp.md
  content/en/docs/external-add-ons/fairing/gcp/tutorials/_index.md
  content/en/docs/external-add-ons/fairing/gcp/tutorials/gcp-kubeflow-notebook.md
  content/en/docs/external-add-ons/fairing/gcp/tutorials/gcp-local-notebook.md
  content/en/docs/external-add-ons/fairing/install-fairing.md
  content/en/docs/external-add-ons/fairing/reference/_index.md
  content/en/docs/external-add-ons/fairing/reference/sdk.md
  content/en/docs/external-add-ons/fairing/tutorials/_index.md
  content/en/docs/external-add-ons/fairing/tutorials/other-tutorials.md
Labels: size/XXL, lgtm, approved

#3572 redirect distribution-specific docs to external websites
  content/en/_redirects
  content/en/docs/distributions/OWNERS
  content/en/docs/distributions/_index.md
  content/en/docs/distributions/aws/OWNERS
  content/en/docs/distributions/aws/_index.md
  content/en/docs/distributions/azure/_index.md
  content/en/docs/distributions/charmed/OWNERS
  content/en/docs/distributions/charmed/_index.md
  content/en/docs/distributions/ekf/_index.md
  content/en/docs/distributions/gke/OWNERS
  content/en/docs/distributions/gke/_index.md
  content/en/docs/distributions/ibm/OWNERS
  content/en/docs/distributions/ibm/_index.md
  content/en/docs/distributions/list.md
  content/en/docs/distributions/nutanix/OWNERS
  content/en/docs/distributions/nutanix/_index.md
Labels: lgtm, approved, size/L

#3595 Fixing small typo in my name for KF summit 2023
  content/en/events/kubeflow-summit-2023.md
Labels: size/XS, lgtm, approved, ok-to-test

#3599 update kubeflow summit agenda & speakers
  content/en/events/kubeflow-summit-2023.md
Labels: lgtm, approved, size/M

#3604 sdk: update KFP SDK v2 migration guide
  content/en/docs/components/pipelines/v2/migration.md
Labels: lgtm, approved, size/M

#3606 Release KFP 2.0.2
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved

#3586 sdk: add kfp sdk pythonic artifact authoring documentation
  content/en/docs/components/pipelines/v2/data-types/artifacts.md
Labels: lgtm, approved, size/L

#3605 sdk: add dsl.OneOf docs
  content/en/docs/components/pipelines/v2/pipelines/control-flow.md
Labels: lgtm, approved, size/M

#3612 release KFP 2.0.3
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved
