Repository kubeflow/website, pull requests merged in 2023-02, with the labels that each got.

#3422 Add link to awesome-kubeflow repo
  content/en/docs/about/community.md
Labels: size/XS, lgtm, approved

#3446 replace .set_gpu_limit with .set_accelerator_limit in KFP SDK docs
  content/en/docs/components/pipelines/v2/author-a-pipeline/tasks.md
Labels: size/XS, lgtm, approved

#3440 improve installing kubeflow page
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/L

#3455 fix v1 docs links
  content/en/docs/components/pipelines/v1/overview/caching-v2.md
  content/en/docs/components/pipelines/v1/overview/pipeline-root.md
  content/en/docs/components/pipelines/v1/sdk-v2/build-pipeline.md
  content/en/docs/components/pipelines/v1/sdk-v2/component-development.md
  content/en/docs/components/pipelines/v1/sdk-v2/python-function-components.md
  content/en/docs/components/pipelines/v1/sdk-v2/v2-compatibility.md
  content/en/docs/components/pipelines/v1/sdk/build-pipeline.md
  content/en/docs/components/pipelines/v1/sdk/component-development.md
  content/en/docs/components/pipelines/v1/sdk/python-function-components.md
Labels: lgtm, approved, size/M

#3447 add docs for ignore_upstream_failure
  content/en/docs/components/pipelines/v2/author-a-pipeline/pipelines.md
  content/en/docs/components/pipelines/v2/author-a-pipeline/tasks.md
Labels: lgtm, approved, size/S
