Repository kubeflow/website, pull requests merged in 2023-06, with the labels that each got.

#3522 Add Linchin to pipelines approver
  content/en/docs/components/pipelines/OWNERS
Labels: size/XS, lgtm, approved

#3523 update KFP v2 migration guide to include typecasting breaking change
  content/en/docs/components/pipelines/v2/migration.md
Labels: lgtm, approved, size/M

#3525 kfp: Update choose-executor.md
  content/en/docs/components/pipelines/v1/installation/choose-executor.md
Labels: lgtm, approved, size/M

#3531 Release KFP 2.0.0
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved

#3526 update KFP website for KFP SDK v2 GA
  content/en/docs/components/pipelines/v1/sdk-v2/build-pipeline.md
  content/en/docs/components/pipelines/v1/sdk-v2/component-development.md
  content/en/docs/components/pipelines/v1/sdk-v2/python-function-components.md
  content/en/docs/components/pipelines/v1/sdk-v2/v2-compatibility.md
  content/en/docs/components/pipelines/v1/sdk/component-development.md
  content/en/docs/components/pipelines/v1/sdk/install-sdk.md
  content/en/docs/components/pipelines/v1/sdk/python-function-components.md
  content/en/docs/components/pipelines/v2/_index.md
  content/en/docs/components/pipelines/v2/cli.md
  content/en/docs/components/pipelines/v2/components/additional-functionality.md
  content/en/docs/components/pipelines/v2/components/containerized-python-components.md
  content/en/docs/components/pipelines/v2/components/lightweight-python-components.md
  content/en/docs/components/pipelines/v2/data-types/parameters.md
  content/en/docs/components/pipelines/v2/hello-world.md
  content/en/docs/components/pipelines/v2/installation/quickstart.md
  content/en/docs/components/pipelines/v2/introduction.md
  content/en/docs/components/pipelines/v2/migration.md
  content/en/docs/components/pipelines/v2/pipelines/pipeline-basics.md
  content/en/docs/components/pipelines/v2/platform-specific-features.md
  content/en/docs/components/pipelines/v2/reference/sdk.md
  content/en/docs/components/pipelines/v2/run-a-pipeline.md
  docs/components/pipelines/v2/components/containerized-python-components
Labels: lgtm, approved, size/L

#3532 chore(kfp): remove the outdated content
  content/en/docs/components/pipelines/v2/_index.md
Labels: size/XS, lgtm, approved

#3533 kfp: Add version compatibility matrix doc
  content/en/docs/components/pipelines/v2/version-compatibility.md
Labels: lgtm, approved, size/M

#3534 kfp: improve the doc on pipeline as component use case
  content/en/docs/components/pipelines/v2/load-and-share-components.md
  content/en/docs/components/pipelines/v2/pipelines/pipeline-basics.md
Labels: lgtm, approved, size/M

#3529 fix: typo
  content/en/docs/external-add-ons/elyra/_index.md
Labels: size/XS, lgtm, approved, ok-to-test

#3491 update content folder link
  content/en/docs/components/pipelines/v2/components/lightweight-python-components.md
Labels: size/XS, lgtm, approved

#3426 Fix broken links
  content/en/docs/components/pipelines/v1/sdk/build-pipeline.md
Labels: size/XS, lgtm, approved, ok-to-test

#3371 Typo fix: Replace OICD to OIDC
  content/en/docs/distributions/azure/deploy/install-kubeflow.md
Labels: size/XS, lgtm, approved, ok-to-test

#3433 Correct code in page
  content/en/docs/components/pipelines/v2/run-a-pipeline.md
Labels: size/XS, lgtm, approved, ok-to-test

#3429 Minor updates
  content/en/docs/components/pipelines/v2/run-a-pipeline.md
Labels: size/XS, lgtm, approved, ok-to-test

#3307 Fix ContainerNodePool resource
  content/en/docs/distributions/gke/pipelines/preemptible.md
Labels: size/XS, lgtm, approved, ok-to-test

#3537 Bump version to 1.7.1
  layouts/shortcodes/gke/latest-version.html
Labels: size/XS, lgtm, approved

#3265 fix broken link for kfp-tekton
  content/en/docs/components/pipelines/v1/sdk/pipelines-with-tekton.md
Labels: size/XS, lgtm, approved
