Repository kubeflow/website, pull requests merged in 2023-12, with the labels that each got.

#3642 Updated link to Kubeflow 1.8 Release Overview video
  content/en/docs/releases/kubeflow-1.8.md
Labels: size/XS, lgtm, approved

#3591 remove reference to now-deprecated "Python based visualizations"
  content/en/docs/components/pipelines/v1/sdk/output-viewer.md
Labels: lgtm, approved, size/S, ok-to-test

#3648 release KFP 2.0.5
  layouts/shortcodes/pipelines/latest-version.html
Labels: lgtm, approved

#3652 Remove KFP v2-compatible docs
  content/en/docs/components/pipelines/v1/overview/caching-v2.md
  content/en/docs/components/pipelines/v1/sdk-v2/_index.md
  content/en/docs/components/pipelines/v1/sdk-v2/build-pipeline.ipynb
  content/en/docs/components/pipelines/v1/sdk-v2/build-pipeline.md
  content/en/docs/components/pipelines/v1/sdk-v2/component-development.md
  content/en/docs/components/pipelines/v1/sdk-v2/importer-component.md
  content/en/docs/components/pipelines/v1/sdk-v2/python-function-components.ipynb
  content/en/docs/components/pipelines/v1/sdk-v2/python-function-components.md
  content/en/docs/components/pipelines/v1/sdk-v2/run-comparison.md
  content/en/docs/components/pipelines/v1/sdk-v2/v2-compatibility.md
  content/en/docs/components/pipelines/v1/sdk-v2/v2-component-io.md
Labels: size/XXL, lgtm, approved

#3646 fix typo for platform-specific-features.md
  content/en/docs/components/pipelines/v2/platform-specific-features.md
Labels: size/XS, lgtm, approved, ok-to-test
