Repository kubeflow/website, pull requests merged in 2023-01, with the labels that each got.

#3419 Migrate GKE docs
  config.toml
  content/en/_redirects
  content/en/docs/distributions/gke/_index.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/S

#3418 [Katib] Update documentation for suggestion algorithms
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/katib-config.md
Labels: lgtm, approved, size/M

#3408 update bentoml guide in external serving section
  content/en/docs/external-add-ons/serving/bentoml.md
Labels: lgtm, approved, size/L, ok-to-test

#3432 [Training] Add the guide on how to use Scheduler Plugins with coscheduling
  content/en/docs/components/training/job-scheduling.md
Labels: lgtm, approved, size/M

#3435 [Katib] Change the Default Resume Policy
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/resume-experiment.md
  content/en/docs/components/katib/trial-template.md
Labels: lgtm, approved, size/M

#3436 [Katib] Limit verbs when use a new CRD in Trials
  content/en/docs/components/katib/trial-template.md
Labels: size/XS, lgtm, approved
