Repository kubeflow/website, pull requests merged in 2023-09, with the labels that each got.

#3574 move "Arrikto Enterprise Kubeflow" to legacy distributions
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/M

#3568 fix: update KFP SDK doc links throughout pipelines docs. fix #3569
  content/en/docs/components/pipelines/v1/overview/caching-v2.md
  content/en/docs/components/pipelines/v1/overview/multi-user.md
  content/en/docs/components/pipelines/v1/overview/pipeline-root.md
  content/en/docs/components/pipelines/v1/sdk-v2/build-pipeline.ipynb
  content/en/docs/components/pipelines/v1/sdk-v2/build-pipeline.md
  content/en/docs/components/pipelines/v1/sdk-v2/component-development.md
  content/en/docs/components/pipelines/v1/sdk-v2/python-function-components.ipynb
  content/en/docs/components/pipelines/v1/sdk-v2/python-function-components.md
  content/en/docs/components/pipelines/v1/sdk-v2/v2-compatibility.md
  content/en/docs/components/pipelines/v1/sdk/build-pipeline.ipynb
  content/en/docs/components/pipelines/v1/sdk/build-pipeline.md
  content/en/docs/components/pipelines/v1/sdk/component-development.md
  content/en/docs/components/pipelines/v1/sdk/enviroment_variables.md
  content/en/docs/components/pipelines/v1/sdk/manipulate-resources.md
  content/en/docs/components/pipelines/v1/sdk/parameters.md
  content/en/docs/components/pipelines/v1/sdk/python-function-components.ipynb
  content/en/docs/components/pipelines/v1/sdk/python-function-components.md
  content/en/docs/components/pipelines/v1/sdk/sdk-overview.md
Labels: lgtm, approved, size/L, ok-to-test

#3561 add KFP SDK dsl.If/Elif/Else docs
  content/en/docs/components/pipelines/v2/pipelines/control-flow.md
Labels: lgtm, approved, size/S

#3573 reword "All Conformant Kubernetes" to "All Certified Kubernetes Distributions"
  content/en/docs/started/installing-kubeflow.md
Labels: size/XS, lgtm, approved

#3588 Remove AutoML Calendar
  content/en/docs/about/community.md
Labels: size/XS, lgtm, approved

#3589 update slack channel links
  content/en/docs/about/community.md
Labels: size/XS, lgtm, approved

#3592 add kubeflow summit 2023
  assets/scss/_styles_project.scss
  config.toml
  content/en/docs/about/events.md
  content/en/events/OWNERS
  content/en/events/_index.md
  content/en/events/kubeflow-summit-2023.md
Labels: lgtm, approved, size/L

#3593 fix kubeflow summit agenda
  content/en/events/kubeflow-summit-2023.md
Labels: lgtm, approved, size/M

#3555 move istio docs from `external-addons` to `multi-tenancy` component
  content/en/_redirects
  content/en/docs/components/multi-tenancy/istio.md
  content/en/docs/external-add-ons/istio/OWNERS
  content/en/docs/external-add-ons/istio/_index.md
Labels: lgtm, approved, size/S
