Repository kubeflow/website, pull requests merged in 2024-02, with the labels that each got.

#3667 GSOC 2024 proposal
  content/en/events/gsoc-2024.md
Labels: lgtm, approved, size/L, ok-to-test

#3665 Katib: Update Katib Config Guide with the new APIs
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/katib-config.md
Labels: lgtm, approved, size/XL

#3669 Adding link to events page from top nav
  config.toml
Labels: lgtm, approved, size/S, ok-to-test

#3675 Change time slot for GSoC 2024 projects
  content/en/events/gsoc-2024.md
Labels: size/S

#3676 Fix GSoC 2024 time slots
  content/en/events/gsoc-2024.md
Labels: size/S

#3678 Training: Add Distributed Training Diagrams
  content/en/docs/components/training/images/distributed-pytorchjob.drawio.svg
  content/en/docs/components/training/images/distributed-tfjob.drawio.svg
  content/en/docs/components/training/overview.md
Labels: lgtm, approved, size/M

#3681 Fixed typos in server-config.md
  content/en/docs/components/pipelines/v2/administration/server-config.md
Labels: size/XS, lgtm, approved, ok-to-test

#3659 Fix broken link container-images.md
  content/en/docs/components/notebooks/container-images.md
Labels: size/XS, lgtm, approved, ok-to-test

#3668 Making the components cards clickable on main page
  content/en/_index.html
Labels: lgtm, approved, size/M, ok-to-test

#3670 Adding social networking websites to the community page
  content/en/docs/about/community.md
Labels: lgtm, approved, size/S, ok-to-test

#3671 local pipeline execution docs
  content/en/docs/components/pipelines/v2/local-execution.md
Labels: lgtm, approved, size/M

#3686 Updated CRs documentation to include comment about istio annotation
  content/en/docs/components/training/mpi.md
  content/en/docs/components/training/mxnet.md
  content/en/docs/components/training/paddlepaddle.md
  content/en/docs/components/training/pytorch.md
  content/en/docs/components/training/xgboost.md
Labels: lgtm, approved, size/S, ok-to-test

#3660 fix buttons for v1 Pipelines SDK
  content/en/docs/components/pipelines/v1/sdk/build-pipeline.md
  content/en/docs/components/pipelines/v1/sdk/python-function-components.md
Labels: lgtm, approved, size/S, ok-to-test

#3689 Add Yuan (Terry) Tang to GSoC Mentors
  content/en/events/gsoc-2024.md
Labels: lgtm, approved, size/M

#3688 Katib: Add Hyperparameter Tuning Architecture
  content/en/docs/components/katib/images/katib-architecture.drawio.svg
  content/en/docs/components/katib/overview.md
Labels: lgtm, approved, size/L

#3691 Add KSC members to approvers in OWNERS
  OWNERS
Labels: lgtm, approved, size/S

#3690 updates to GSoC Page after selection into the program
  content/en/events/gsoc-2024.md
Labels: lgtm, approved, size/M
