Repository kubeflow/website, pull requests merged in 2024-05, with the labels that each got.

#3657 Updated contributors table link
  content/en/docs/about/contributing.md
Labels: size/XS, lgtm, approved, ok-to-test

#3723 Katib: Reorganized Katib Docs
  content/en/_redirects
  content/en/docs/components/katib/early-stopping.md
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/getting-started.md
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/images/deploy-yaml.png
  content/en/docs/components/katib/images/experiment-list.png
  content/en/docs/components/katib/images/getting-started-example.png
  content/en/docs/components/katib/images/home-page-kubeflow-ui.png
  content/en/docs/components/katib/images/home-page-standalone.png
  content/en/docs/components/katib/images/menu.png
  content/en/docs/components/katib/images/ml-lifecycle-katib.drawio.svg
  content/en/docs/components/katib/images/nas-example.png
  content/en/docs/components/katib/images/nas-parameters.png
  content/en/docs/components/katib/installation.md
  content/en/docs/components/katib/overview.md
  content/en/docs/components/katib/reference/_index.md
  content/en/docs/components/katib/reference/architecture.md
  content/en/docs/components/katib/reference/nas-algorithms.md
  content/en/docs/components/katib/resume-experiment.md
  content/en/docs/components/katib/trial-template.md
  content/en/docs/components/katib/user-guides/_index.md
  content/en/docs/components/katib/user-guides/early-stopping.md
  content/en/docs/components/katib/user-guides/env-variables.md
  content/en/docs/components/katib/user-guides/hp-tuning/_index.md
  content/en/docs/components/katib/user-guides/hp-tuning/configure-algorithm.md
  content/en/docs/components/katib/user-guides/hp-tuning/configure-experiment.md
  content/en/docs/components/katib/user-guides/installation-options.md
  content/en/docs/components/katib/user-guides/katib-config.md
  content/en/docs/components/katib/user-guides/katib-ui.md
  content/en/docs/components/katib/user-guides/metrics-collector.md
  content/en/docs/components/katib/user-guides/nas/_index.md
  content/en/docs/components/katib/user-guides/nas/configure-algorithm.md
  content/en/docs/components/katib/user-guides/nas/configure-experiment.md
  content/en/docs/components/katib/user-guides/resume-experiment.md
  content/en/docs/components/katib/user-guides/trial-template.md
  content/en/docs/components/training/getting-started.md
  content/en/docs/components/training/installation.md
Labels: size/XXL, lgtm, approved

#3733 Katib: Fix getting started redirect
  content/en/_redirects
Labels: size/XS, lgtm, approved

#3731 feat: Add Francisco as OWNER for Feature Store documentation
  content/en/docs/external-add-ons/feature-store/OWNERS
Labels: size/XS, lgtm, approved, ok-to-test

#3735 configure-experiment.md - missing annotation value in yaml example
  content/en/docs/components/katib/user-guides/hp-tuning/configure-experiment.md
Labels: size/XS, lgtm, approved, ok-to-test

#3718 Training: Add Fine-Tune API Docs
  content/en/_index.html
  content/en/docs/components/training/explanation/_index.md
  content/en/docs/components/training/explanation/fine-tuning.md
  content/en/docs/components/training/images/fine-tune-llm-api.drawio.svg
  content/en/docs/components/training/reference/fine-tuning.md
  content/en/docs/components/training/user-guides/fine-tuning.md
Labels: lgtm, approved, size/L

#3698 add Model Registry doc to website
  content/en/docs/components/model-registry/_index.md
  content/en/docs/components/model-registry/getting-started.md
  content/en/docs/components/model-registry/images/MLloopinnerouter.png
  content/en/docs/components/model-registry/installation.md
  content/en/docs/components/model-registry/overview.md
  content/en/docs/components/model-registry/reference/_index.md
  content/en/docs/components/model-registry/reference/architecture.md
  content/en/docs/components/model-registry/reference/images/model-registry-overview.jpg
Labels: lgtm, approved, size/L

#3734 doc: Update the document of Feast feature store.
  content/en/docs/external-add-ons/feature-store/getting-started.md
Labels: lgtm, approved, size/S, ok-to-test

#3738 Update banner to link to upcoming colocated event at KubeCon
  config.toml
Labels: size/XS, lgtm, approved

#3743 Removed reference to non existing path
  content/en/docs/components/pipelines/v1/installation/localcluster-deployment.md
Labels: size/XS, lgtm, approved, ok-to-test

#3739 Update Slack channels to new CNCF Slack channels
  content/en/docs/about/community.md
Labels: lgtm, approved, size/M

#3724 Update Kubeflow Installation with Standalone Mode
  content/en/docs/started/installing-kubeflow.md
  content/en/docs/started/introduction.md
Labels: lgtm, approved, size/L

#3746 Update deployKF version to 1.8
  content/en/docs/started/installing-kubeflow.md
  layouts/shortcodes/deploykf/latest-version.html
Labels: size/XS, lgtm, approved
