Repository kubeflow/website, pull requests merged in 2024-03, with the labels that each got.

#3682 Updated legal info due to migration from CLA to DCO
  content/en/docs/about/contributing.md
Labels: lgtm, approved, size/S, ok-to-test

#3696 Katib: Add KATIB_POSTGRESQL_SSL_MODE variable of Katib DB Manager
  content/en/docs/components/katib/env-variables.md
Labels: size/XS, lgtm, approved, ok-to-test

#3697 update slack inviter link
  content/en/docs/about/community.md
Labels: size/XS, lgtm, approved

#3693 Change Kubeflow Distributions Table
  assets/scss/_styles_project.scss
  content/en/docs/started/installing-kubeflow.md
  layouts/shortcodes/azure/latest-version.html
  layouts/shortcodes/canonical/OWNERS
  layouts/shortcodes/canonical/latest-version.html
  layouts/shortcodes/deploykf/OWNERS
  layouts/shortcodes/deploykf/latest-version.html
  layouts/shortcodes/iks/latest-branch.html
  layouts/shortcodes/oracle/latest-version.html
  layouts/shortcodes/redhat/OWNERS
  layouts/shortcodes/redhat/latest-version.html
  layouts/shortcodes/vmware/OWNERS
  layouts/shortcodes/vmware/latest-version.html
Labels: lgtm, approved, size/L

#3702 release KFP 2.1.0
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved

#3694 fix: Updated description for pipeline_version_id in Runs and Recurring Runs API docs
  content/en/docs/components/pipelines/v2/reference/api/kubeflow-pipeline-api-spec.html
Labels: size/XS, lgtm, approved, ok-to-test

#3701 Katib: fix the source code reference about mxnet
  content/en/docs/components/katib/early-stopping.md
  content/en/docs/components/katib/hyperparameter.md
Labels: size/XS, lgtm, approved

#3672 add qbo to list of distributions
  content/en/docs/started/installing-kubeflow.md
  layouts/shortcodes/qbo/latest-version.html
Labels: lgtm, approved, size/S, ok-to-test
