Repository kubeflow/website, pull requests merged in 2024-07, with the labels that each got.

#3783 Added @rimolive as approver for Pipelines
  content/en/docs/components/pipelines/OWNERS
Labels: size/XS, lgtm, approved

#3775 Added outdated warning to all pipelines v1 pages
  content/en/docs/components/pipelines/legacy-v1/_index.md
  content/en/docs/components/pipelines/legacy-v1/installation/_index.md
  content/en/docs/components/pipelines/legacy-v1/installation/choose-executor.md
  content/en/docs/components/pipelines/legacy-v1/installation/compatibility-matrix.md
  content/en/docs/components/pipelines/legacy-v1/installation/localcluster-deployment.md
  content/en/docs/components/pipelines/legacy-v1/installation/overview.md
  content/en/docs/components/pipelines/legacy-v1/installation/standalone-deployment.md
  content/en/docs/components/pipelines/legacy-v1/installation/upgrade.md
  content/en/docs/components/pipelines/legacy-v1/introduction.md
  content/en/docs/components/pipelines/legacy-v1/overview/_index.md
  content/en/docs/components/pipelines/legacy-v1/overview/caching.md
  content/en/docs/components/pipelines/legacy-v1/overview/multi-user.md
  content/en/docs/components/pipelines/legacy-v1/overview/quickstart.md
  content/en/docs/components/pipelines/legacy-v1/reference/_index.md
  content/en/docs/components/pipelines/legacy-v1/reference/sdk.md
  content/en/docs/components/pipelines/legacy-v1/sdk/_index.md
  content/en/docs/components/pipelines/legacy-v1/sdk/best-practices.md
  content/en/docs/components/pipelines/legacy-v1/sdk/build-pipeline.md
  content/en/docs/components/pipelines/legacy-v1/sdk/component-development.md
  content/en/docs/components/pipelines/legacy-v1/sdk/dsl-recursion.md
  content/en/docs/components/pipelines/legacy-v1/sdk/enviroment_variables.md
  content/en/docs/components/pipelines/legacy-v1/sdk/gcp.md
  content/en/docs/components/pipelines/legacy-v1/sdk/install-sdk.md
  content/en/docs/components/pipelines/legacy-v1/sdk/manipulate-resources.md
  content/en/docs/components/pipelines/legacy-v1/sdk/output-viewer.md
  content/en/docs/components/pipelines/legacy-v1/sdk/parameters.md
  content/en/docs/components/pipelines/legacy-v1/sdk/pipelines-with-tekton.md
  content/en/docs/components/pipelines/legacy-v1/sdk/python-based-visualizations.md
  content/en/docs/components/pipelines/legacy-v1/sdk/python-function-components.md
  content/en/docs/components/pipelines/legacy-v1/sdk/sdk-overview.md
  content/en/docs/components/pipelines/legacy-v1/sdk/static-type-checking.md
  content/en/docs/components/pipelines/legacy-v1/troubleshooting.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/_index.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/api-pipelines.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/benchmark-examples.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/build-pipeline.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/cloud-tutorials.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/sdk-examples.md
Labels: lgtm, approved, size/L

#3777 Fixed sdk-v2 links in pipelines
  content/en/docs/components/pipelines/concepts/pipeline-root.md
  content/en/docs/components/pipelines/legacy-v1/sdk/output-viewer.md
Labels: size/XS, lgtm, approved

#3784 Removed obsolete warning from Pipelines artifacts.md
  content/en/docs/components/pipelines/user-guides/data-handling/artifacts.md
Labels: size/XS, lgtm, approved

#3785 Fixed links in Pipelines > user guides > data handling > artifacts
  content/en/docs/components/pipelines/user-guides/data-handling/artifacts.md
Labels: size/XS, lgtm, approved

#3789 Pipelines - @hbelmiro promoted to approver and removed old members
  content/en/docs/components/pipelines/OWNERS
Labels: size/XS, lgtm, approved

#3792 Update Kubeflow Pipelines Legacy V1 warning text
  content/en/docs/components/pipelines/legacy-v1/_index.md
  content/en/docs/components/pipelines/legacy-v1/installation/_index.md
  content/en/docs/components/pipelines/legacy-v1/installation/choose-executor.md
  content/en/docs/components/pipelines/legacy-v1/installation/compatibility-matrix.md
  content/en/docs/components/pipelines/legacy-v1/installation/localcluster-deployment.md
  content/en/docs/components/pipelines/legacy-v1/installation/overview.md
  content/en/docs/components/pipelines/legacy-v1/installation/standalone-deployment.md
  content/en/docs/components/pipelines/legacy-v1/installation/upgrade.md
  content/en/docs/components/pipelines/legacy-v1/introduction.md
  content/en/docs/components/pipelines/legacy-v1/overview/_index.md
  content/en/docs/components/pipelines/legacy-v1/overview/caching.md
  content/en/docs/components/pipelines/legacy-v1/overview/multi-user.md
  content/en/docs/components/pipelines/legacy-v1/overview/quickstart.md
  content/en/docs/components/pipelines/legacy-v1/reference/_index.md
  content/en/docs/components/pipelines/legacy-v1/reference/sdk.md
  content/en/docs/components/pipelines/legacy-v1/sdk/_index.md
  content/en/docs/components/pipelines/legacy-v1/sdk/best-practices.md
  content/en/docs/components/pipelines/legacy-v1/sdk/build-pipeline.md
  content/en/docs/components/pipelines/legacy-v1/sdk/component-development.md
  content/en/docs/components/pipelines/legacy-v1/sdk/dsl-recursion.md
  content/en/docs/components/pipelines/legacy-v1/sdk/enviroment_variables.md
  content/en/docs/components/pipelines/legacy-v1/sdk/gcp.md
  content/en/docs/components/pipelines/legacy-v1/sdk/install-sdk.md
  content/en/docs/components/pipelines/legacy-v1/sdk/manipulate-resources.md
  content/en/docs/components/pipelines/legacy-v1/sdk/output-viewer.md
  content/en/docs/components/pipelines/legacy-v1/sdk/parameters.md
  content/en/docs/components/pipelines/legacy-v1/sdk/pipelines-with-tekton.md
  content/en/docs/components/pipelines/legacy-v1/sdk/python-based-visualizations.md
  content/en/docs/components/pipelines/legacy-v1/sdk/python-function-components.md
  content/en/docs/components/pipelines/legacy-v1/sdk/sdk-overview.md
  content/en/docs/components/pipelines/legacy-v1/sdk/static-type-checking.md
  content/en/docs/components/pipelines/legacy-v1/troubleshooting.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/_index.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/api-pipelines.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/benchmark-examples.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/build-pipeline.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/cloud-tutorials.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/sdk-examples.md
Labels: lgtm, approved, size/L

#3794 Partial Revert of #3787
  content/en/docs/components/pipelines/getting-started.md
Labels: lgtm, approved, size/S

#3779 fix(pipelines): Add missing kfp-kubernetes import
  content/en/docs/components/pipelines/user-guides/core-functions/platform-specific-features.md
Labels: size/XS, lgtm, approved

#3800 fix: broken github url in component-spec.md
  content/en/docs/components/pipelines/reference/component-spec.md
Labels: size/XS, lgtm, approved, ok-to-test

#3793 Added instructions for installing Pipelines.
  content/en/docs/components/pipelines/concepts/pipeline-root.md
  content/en/docs/components/pipelines/operator-guides/installation/_index.md
  content/en/docs/components/pipelines/user-guides/core-functions/connect-api.md
Labels: lgtm, approved, size/S

#3801 MR: update getting started
  content/en/docs/components/model-registry/getting-started.md
  content/en/docs/components/model-registry/installation.md
Labels: lgtm, approved, size/L, ok-to-test

#3796 Added page for kfp-kubernetes
  content/en/docs/components/pipelines/reference/kfp-kubernetes.md
Labels: size/XS, lgtm, approved

#3763 Enabled the Checklinks Netlify plugin
  netlify.toml
  package-lock.json
  package.json
Labels: size/XXL, lgtm, approved

#3805 Add port-forward to ml-pipeline-ui service
  content/en/docs/components/pipelines/operator-guides/installation/_index.md
Labels: size/XS, lgtm, approved

#3806 Update Central Dashboard docs for 1.9.0
  content/en/docs/components/central-dash/customize.md
  content/en/docs/components/central-dash/overview.md
  content/en/docs/components/central-dash/profiles.md
  content/en/docs/images/add-contributors.png
  content/en/docs/images/central-ui.png
  content/en/docs/images/dashboard/auto-profile-step-1.png
  content/en/docs/images/dashboard/auto-profile-step-2.png
  content/en/docs/images/dashboard/custom-menu-item.png
  content/en/docs/images/dashboard/homepage-manage-contributors.png
  content/en/docs/images/dashboard/homepage-profile-selector.png
  content/en/docs/images/dashboard/homepage.png
  content/en/docs/images/dashboard/manage-contributors.png
  content/en/docs/images/dashboard/pipelines-runs.png
  content/en/docs/images/manage-contributors.png
  content/en/docs/images/multi-user-contributors.png
  content/en/docs/images/select-profile.png
  content/en/docs/started/architecture.md
Labels: lgtm, approved, size/L

#3798 Add Kubeflow 1.8.1 release page
  content/en/docs/releases/kubeflow-1.8.md
Labels: lgtm, approved, size/L

#3817 Fix favicons not showing Kubeflow logo
  layouts/partials/favicons.html
  static/android-chrome-192x192.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/browserconfig.xml
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
  static/favicons/android-icon-144x144.png
  static/favicons/android-icon-192x192.png
  static/favicons/android-icon-36x36.png
  static/favicons/android-icon-48x48.png
  static/favicons/android-icon-72x72.png
  static/favicons/android-icon-96x96.png
  static/favicons/apple-icon-114x114.png
  static/favicons/apple-icon-120x120.png
  static/favicons/apple-icon-144x144.png
  static/favicons/apple-icon-152x152.png
  static/favicons/apple-icon-180x180.png
  static/favicons/apple-icon-57x57.png
  static/favicons/apple-icon-60x60.png
  static/favicons/apple-icon-72x72.png
  static/favicons/apple-icon-76x76.png
  static/favicons/apple-icon-precomposed.png
  static/favicons/apple-icon.png
  static/favicons/browserconfig.xml
  static/favicons/favicon-16x16.png
  static/favicons/favicon-32x32.png
  static/favicons/favicon-96x96.png
  static/favicons/favicon.ico
  static/favicons/manifest.json
  static/favicons/ms-icon-144x144.png
  static/favicons/ms-icon-150x150.png
  static/favicons/ms-icon-310x310.png
  static/favicons/ms-icon-70x70.png
  static/mstile-144x144.png
  static/mstile-150x150.png
  static/mstile-310x150.png
  static/mstile-310x310.png
  static/mstile-70x70.png
  static/safari-pinned-tab.svg
  static/site.webmanifest
Labels: lgtm, approved, size/L

#3818 Generate social embed images for all pages
  assets/fonts/Inter-Medium.ttf
  assets/social/social_base.png
  assets/social/social_home.png
  layouts/_internal/opengraph.html
  layouts/_internal/twitter_cards.html
  layouts/partials/head.html
  layouts/partials/social_image_generator.html
Labels: lgtm, approved, size/L

#3799 Add Kubeflow 1.9 Release page
  content/en/docs/releases/kubeflow-1.9.md
  layouts/shortcodes/kf-latest-version.html
Labels: lgtm, approved, size/L

#3821 Fix baseURL in Netlify deployments (needed to fix `twitter:image`)
  config.toml
  layouts/partials/head.html
  layouts/partials/seo_schema.html
  layouts/partials/social_image_generator.html
  netlify.toml
Labels: lgtm, approved, size/L

#3820 update localcluster deployment doc to use Docker desktop for local deployment Resolves issue #3819
  content/en/docs/components/pipelines/legacy-v1/installation/localcluster-deployment.md
Labels: lgtm, approved, size/M, ok-to-test

#3826 Remove dead link to kubeflow community slack
  content/en/docs/about/contributing.md
Labels: size/XS, lgtm, approved, needs-ok-to-test

#3822 Training: Fix SDK install for LLMs Fine-Tuning API
  content/en/docs/components/training/installation.md
Labels: size/XS, lgtm, approved

#3755 Update Kubeflow Index Page
  content/en/_index.html
  content/en/docs/started/introduction.md
Labels: lgtm, approved, size/S

#3807 Fix broken links in Pipelines
  README.md
  content/en/_redirects
  content/en/docs/about/style-guide.md
  content/en/docs/components/pipelines/interfaces.md
  content/en/docs/components/pipelines/legacy-v1/installation/choose-executor.md
  content/en/docs/components/pipelines/legacy-v1/installation/localcluster-deployment.md
  content/en/docs/components/pipelines/legacy-v1/installation/overview.md
  content/en/docs/components/pipelines/legacy-v1/installation/standalone-deployment.md
  content/en/docs/components/pipelines/legacy-v1/installation/upgrade.md
  content/en/docs/components/pipelines/legacy-v1/overview/multi-user.md
  content/en/docs/components/pipelines/legacy-v1/sdk/build-pipeline.ipynb
  content/en/docs/components/pipelines/legacy-v1/sdk/build-pipeline.md
  content/en/docs/components/pipelines/legacy-v1/sdk/component-development.md
  content/en/docs/components/pipelines/legacy-v1/sdk/enviroment_variables.md
  content/en/docs/components/pipelines/legacy-v1/sdk/gcp.md
  content/en/docs/components/pipelines/legacy-v1/sdk/manipulate-resources.md
  content/en/docs/components/pipelines/legacy-v1/sdk/python-function-components.ipynb
  content/en/docs/components/pipelines/legacy-v1/sdk/python-function-components.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/build-pipeline.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/cloud-tutorials.md
  content/en/docs/components/pipelines/operator-guides/installation/_index.md
  content/en/docs/external-add-ons/serving/tfserving_new.md
  content/en/docs/started/installing-kubeflow.md
  netlify.toml
Labels: lgtm, approved, size/M
