Repository kubeflow/website, pull requests merged in 2024-04, with the labels that each got.

#3705 Document caching in kfp v2
  content/en/docs/components/pipelines/v2/caching.md
Labels: lgtm, approved, size/M, ok-to-test

#3710 Katib: Update the minimal requirements
  content/en/docs/components/katib/hyperparameter.md
Labels: size/XS, lgtm, approved

#3713 Training: Add MXJob deprecation notice
  content/en/docs/components/training/mxnet.md
Labels: size/XS, lgtm, approved

#3680 updating architecture diagram
  content/en/docs/started/architecture.md
  content/en/docs/started/images/kubeflow-architecture.drawio.svg
Labels: lgtm, approved, size/S

#3719 Training: Reorganized Training Operator Docs
  content/en/_redirects
  content/en/docs/components/katib/experiment.md
  content/en/docs/components/katib/hyperparameter.md
  content/en/docs/components/katib/overview.md
  content/en/docs/components/katib/trial-template.md
  content/en/docs/components/training/getting-started.md
  content/en/docs/components/training/images/ml-lifecycle-training-operator.drawio.svg
  content/en/docs/components/training/installation.md
  content/en/docs/components/training/overview.md
  content/en/docs/components/training/pytorch.md
  content/en/docs/components/training/reference/_index.md
  content/en/docs/components/training/reference/distributed-training.md
  content/en/docs/components/training/user-guides/_index.md
  content/en/docs/components/training/user-guides/job-scheduling.md
  content/en/docs/components/training/user-guides/mpi.md
  content/en/docs/components/training/user-guides/mxnet.md
  content/en/docs/components/training/user-guides/paddle.md
  content/en/docs/components/training/user-guides/pytorch.md
  content/en/docs/components/training/user-guides/tensorflow.md
  content/en/docs/components/training/user-guides/xgboost.md
Labels: size/XXL, lgtm, approved

#3722 Remove Fairing section
  content/en/docs/started/architecture.md
Labels: size/XS, lgtm, approved, ok-to-test

#3725 Fix Local Builds + Update: Hugo, MathJax, Mermaid
  README.md
  config.toml
  content/en/docs/components/katib/hyperparameter.md
  layouts/_default/_markup/render-codeblock-mermaid.html
  layouts/partials/head.html
  layouts/partials/math.html
  layouts/partials/mathjax.html
  layouts/partials/mermaid.html
  layouts/partials/scripts.html
  netlify.toml
Labels: lgtm, approved, size/L

#3727 chore: release KFP 2.2.0
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved
