Repository kubeflow/website, pull requests merged in 2024-08, with the labels that each got.

#3828 model registry: update MLOps diagrams
  content/en/docs/components/model-registry/images/MLloopinnerouter.png
  content/en/docs/components/model-registry/images/ml-lifecycle-kubeflow-modelregistry.drawio.svg
  content/en/docs/components/model-registry/overview.md
Labels: lgtm, approved, size/S

#3816 Improve sidebar style for deeply nested pages
  assets/scss/_styles_project.scss
  assets/scss/_variables_project.scss
  config.toml
  content/en/_index.html
  content/en/docs/about/community.md
  content/en/docs/about/events.md
  content/en/docs/components/pipelines/legacy-v1/reference/api/kubeflow-pipeline-api-spec.html
  content/en/docs/components/pipelines/legacy-v1/reference/api/kubeflow-pipeline-api-spec.md
  content/en/docs/components/pipelines/legacy-v1/reference/sdk.md
  content/en/docs/components/pipelines/legacy-v1/sdk/OWNERS.md
  content/en/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec.html
  content/en/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec.md
  content/en/docs/distributions/list.md
  content/en/events/docs.md
  content/en/events/gsoc-2024.md
  i18n/en.toml
  layouts/_default/content.html
  layouts/docs/baseof.html
  layouts/docs/list.html
  layouts/partials/feedback.html
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/navbar.html
  layouts/partials/page-meta-links.html
  layouts/partials/sidebar-tree.html
  layouts/partials/swaggerui.html
  layouts/shortcodes/swaggerui-inline.html
Labels: size/XXL, lgtm, approved

#3786 Moved multi-user to KFP v2 docs
  content/en/_redirects
  content/en/docs/components/pipelines/operator-guides/multi-user.md
Labels: lgtm, approved, size/S

#3840 Fix Kubeflow 1.9 release date
  content/en/docs/releases/kubeflow-1.9.md
Labels: size/XS, lgtm, approved

#3836 Refactor external add-ons section
  content/en/_index.html
  content/en/_redirects
  content/en/docs/components/katib/user-guides/installation-options.md
  content/en/docs/components/katib/user-guides/katib-config.md
  content/en/docs/external-add-ons/_index.md
  content/en/docs/external-add-ons/elyra/_index.md
  content/en/docs/external-add-ons/elyra/github.md
  content/en/docs/external-add-ons/elyra/images/elyra-pipeline-screenshot.png
  content/en/docs/external-add-ons/elyra/introduction.md
  content/en/docs/external-add-ons/elyra/website.md
  content/en/docs/external-add-ons/feast/_index.md
  content/en/docs/external-add-ons/feast/github.md
  content/en/docs/external-add-ons/feast/images/feast-architecture.png
  content/en/docs/external-add-ons/feast/introduction.md
  content/en/docs/external-add-ons/feast/website.md
  content/en/docs/external-add-ons/feature-store/OWNERS
  content/en/docs/external-add-ons/feature-store/_index.md
  content/en/docs/external-add-ons/feature-store/getting-started.md
  content/en/docs/external-add-ons/feature-store/overview.md
  content/en/docs/external-add-ons/kserve/OWNERS
  content/en/docs/external-add-ons/kserve/_index.md
  content/en/docs/external-add-ons/kserve/first_isvc_kserve.ipynb
  content/en/docs/external-add-ons/kserve/first_isvc_kserve.md
  content/en/docs/external-add-ons/kserve/github.md
  content/en/docs/external-add-ons/kserve/introduction.md
  content/en/docs/external-add-ons/kserve/iris-input.json
  content/en/docs/external-add-ons/kserve/kserve.md
  content/en/docs/external-add-ons/kserve/migration.md
  content/en/docs/external-add-ons/kserve/pics/kserve-architecture.png
  content/en/docs/external-add-ons/kserve/pics/kserve.png
  content/en/docs/external-add-ons/kserve/webapp.md
  content/en/docs/external-add-ons/kserve/website.md
  content/en/docs/external-add-ons/serving/OWNERS
  content/en/docs/external-add-ons/serving/_index.md
  content/en/docs/external-add-ons/serving/bentoml.md
  content/en/docs/external-add-ons/serving/istio-dashboard.png
  content/en/docs/external-add-ons/serving/mlrun.md
  content/en/docs/external-add-ons/serving/overview.md
  content/en/docs/external-add-ons/serving/seldon.md
  content/en/docs/external-add-ons/serving/tfbatchpredict.md
  content/en/docs/external-add-ons/serving/tfserving_new.md
  content/en/docs/external-add-ons/serving/tritoninferenceserver.md
Labels: size/XXL, lgtm, approved

#3837 chore: add links to kubeflow 1.9 manifests
  content/en/docs/started/installing-kubeflow.md
Labels: size/XS, lgtm, approved, ok-to-test

#3795 Improve the KFP / User Guides / Core Functions docs
  content/en/docs/components/katib/user-guides/katib-config.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/api-pipelines.md
  content/en/docs/components/pipelines/operator-guides/multi-user.md
  content/en/docs/components/pipelines/user-guides/components/_index.md
  content/en/docs/components/pipelines/user-guides/core-functions/_index.md
  content/en/docs/components/pipelines/user-guides/core-functions/build-advanced-pipeline.md
  content/en/docs/components/pipelines/user-guides/core-functions/caching.md
  content/en/docs/components/pipelines/user-guides/core-functions/cli.md
  content/en/docs/components/pipelines/user-guides/core-functions/compile-a-pipeline.md
  content/en/docs/components/pipelines/user-guides/core-functions/connect-api.md
  content/en/docs/components/pipelines/user-guides/core-functions/control-flow.md
  content/en/docs/components/pipelines/user-guides/core-functions/execute-kfp-pipelines-locally.md
  content/en/docs/components/pipelines/user-guides/core-functions/platform-specific-features.md
  content/en/docs/components/pipelines/user-guides/core-functions/run-a-pipeline.md
  content/en/docs/components/pipelines/user-guides/data-handling/_index.md
  content/en/docs/components/pipelines/user-guides/data-handling/artifacts.md
  content/en/docs/components/pipelines/user-guides/migration.md
Labels: size/XXL, lgtm, approved

#3834 Updating Training Operator documentation and fixing fragmented links
  content/en/docs/components/katib/user-guides/installation-options.md
  content/en/docs/components/training/explanation/fine-tuning.md
  content/en/docs/components/training/getting-started.md
  content/en/docs/components/training/images/ml-lifecycle-training-operator.drawio.svg
  content/en/docs/components/training/images/training-operator-overview.drawio.png
  content/en/docs/components/training/images/training-operator-v1-architecture.drawio.svg
  content/en/docs/components/training/installation.md
  content/en/docs/components/training/overview.md
  content/en/docs/components/training/reference/_index.md
  content/en/docs/components/training/reference/architecture.md
  content/en/docs/components/training/reference/distributed-training.md
  content/en/docs/components/training/user-guides/fine-tuning.md
  content/en/docs/components/training/user-guides/job-scheduling.md
  content/en/docs/components/training/user-guides/mpi.md
  content/en/docs/components/training/user-guides/mxnet.md
  content/en/docs/components/training/user-guides/paddle.md
  content/en/docs/components/training/user-guides/pytorch.md
  content/en/docs/components/training/user-guides/tensorflow.md
  content/en/docs/components/training/user-guides/xgboost.md
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/XL
