Repository kubeflow/website, pull requests merged in 2024-09, with the labels that each got.

#3848 Block web crawlers on `v0.2-branch`
  netlify.toml
  themes/kf/layouts/_default/baseof.html
Labels: size/XS, lgtm, approved

#3847 Block web crawlers on `v0.3-branch`
  netlify.toml
  themes/kf/layouts/_default/baseof.html
Labels: size/XS, lgtm, approved

#3849 Block web crawlers on `v0.4-branch`
  config.toml
  layouts/partials/navbar-version-selector.html
  netlify.toml
  package.json
  themes/docsy/layouts/partials/head.html
Labels: lgtm, approved

#3865 Update `v0.3-branch` Hugo (fix deploy)
  netlify.toml
Labels: size/XS, lgtm, approved

#3864 Update `v0.2-branch` Hugo (fix deploy)
  netlify.toml
Labels: size/XS, lgtm

#3835 KF 1.9 release: fix date and link to video
  content/en/docs/releases/kubeflow-1.9.md
Labels: size/XS, lgtm, approved

#3870 chore: release KFP 2.3.0
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved

#3869 Improve `archived_version` banner for `v0.2-branch`
  OWNERS
  themes/kf/layouts/partials/version-banner.html
Labels: approved, size/M

#3868 Improve `archived_version` banner for `v0.3-branch`
  OWNERS
  themes/kf/layouts/partials/version-banner.html
Labels: lgtm, size/M

#3851 Block web crawlers on `v0.6-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/navbar-version-selector.html
  layouts/partials/version-banner.html
  netlify.toml
  package.json
Labels: size/L

#3852 Block web crawlers on `v0.7-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
  netlify.toml
  package.json
  themes/docsy/layouts/shortcodes/blocks/cover.html
Labels: size/L

#3853 Block web crawlers on `v1.0-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
  netlify.toml
  package.json
Labels: size/L

#3854 Block web crawlers on `v1.1-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
  netlify.toml
  package.json
Labels: size/L

#3839 add unsupported notice for PipelineTaskFinalStatus
  content/en/docs/components/pipelines/user-guides/core-functions/control-flow.md
Labels: size/XS, lgtm, approved

#3856 Block web crawlers on `v1.3-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
  netlify.toml
  package-lock.json
  package.json
Labels: size/XXL

#3855 Block web crawlers on `v1.2-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
  netlify.toml
  package.json
Labels: lgtm, size/L

#3857 Block web crawlers on `v1.4-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
  netlify.toml
  package-lock.json
  package.json
Labels: size/XXL

#3858 Block web crawlers on `v1.5-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
Labels: size/M

#3859 Block web crawlers on `v1.6-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
Labels: size/M

#3860 Block web crawlers on `v1.7-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
Labels: size/M

#3861 Block web crawlers on `v1.8-branch`
  OWNERS
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
Labels: size/M

#3833 add docs around pipelines obj store configurations
  content/en/docs/components/pipelines/concepts/pipeline-root.md
  content/en/docs/components/pipelines/operator-guides/configure-object-store.md
  content/en/docs/components/pipelines/operator-guides/images/kfp-obj-store-configurations.png
Labels: lgtm, approved, size/L

#3874 Add KSC info to the community page
  content/en/docs/about/community.md
Labels: size/XS, lgtm, approved

#3875 Change social networking to social media
  content/en/docs/about/community.md
Labels: size/XS, lgtm, approved

#3873 Fix: Update containerized-python-components.md. fixes #3871
  content/en/docs/components/pipelines/user-guides/components/containerized-python-components.md
Labels: lgtm, approved, size/S, ok-to-test

#3872 Add page for Spark operator/Yunikorn integration
  content/en/docs/components/spark-operator/user-guide/yunikorn-integration.md
Labels: lgtm, approved, size/M

#3830 Fixed broken link in central dashboard
  content/en/docs/components/central-dash/overview.md
  netlify.toml
Labels: size/XS, lgtm, approved

#3880 [Pipelines] Add doc on disabling default caching flag and env var
  content/en/docs/components/pipelines/user-guides/core-functions/caching.md
Labels: lgtm, approved, size/M

#3881 [Pipelines] Specify KFP SDK version where new caching flag will be available
  content/en/docs/components/pipelines/user-guides/core-functions/caching.md
Labels: size/XS, lgtm, approved, ok-to-test

#3878 Fixed broken links in Notebooks
  content/en/docs/components/katib/user-guides/installation-options.md
  content/en/docs/components/notebooks/jupyter-tensorflow-examples.md
  content/en/docs/components/pipelines/legacy-v1/tutorials/build-pipeline.md
  netlify.toml
Labels: size/XS, lgtm, approved, ok-to-test

#3883 Update spark operator owners
  content/en/docs/components/spark-operator/OWNERS
Labels: size/XS, lgtm, approved

#3882 Update spark-operator developer guide
  content/en/docs/components/spark-operator/developer-guide.md
Labels: lgtm, approved, size/L

#3884 Update the user guide to run multiple Spark operator instances
  content/en/docs/components/spark-operator/user-guide/running-multiple-instances-of-the-operator.md
Labels: lgtm, approved, size/M

#3888 Update katib-config.md
  content/en/docs/components/katib/reference/architecture.md
  content/en/docs/components/katib/user-guides/katib-config.md
  netlify.toml
Labels: lgtm, approved, size/S, ok-to-test

#3827 Make basic community membership guidelines clearer
  README.md
  content/en/docs/about/community.md
  content/en/docs/about/contributing.md
  content/en/docs/about/membership.md
  layouts/shortcodes/note.html
Labels: lgtm, approved, size/L, ok-to-test
