Repository kubeflow/website, pull requests merged in 2024-12, with the labels that each got.

#3662 add history on KF logo
  content/en/docs/started/introduction.md
Labels: size/XS, lgtm, approved, ok-to-test

#3879 [KFTO-SDK] Add doc on customising base images for Train API
  content/en/docs/components/training/user-guides/fine-tuning.md
Labels: lgtm, approved, size/S, ok-to-test

#3844 doc(katib): update push-based metrics collector.
  content/en/docs/components/katib/user-guides/metrics-collector.md
Labels: lgtm, approved, size/M

#3941 Add Emeritus Approvers Info to the Kubeflow Membership
  content/en/docs/about/contributing.md
  content/en/docs/about/membership.md
Labels: lgtm, approved, size/M

#3753 Fix links to machine types and kustomize configuration
  content/en/docs/components/pipelines/legacy-v1/installation/standalone-deployment.md
Labels: size/XS, lgtm, approved, ok-to-test

#3944 update local execution limitations
  content/en/docs/components/pipelines/user-guides/core-functions/execute-kfp-pipelines-locally.md
Labels: size/XS, lgtm, approved

#3947 Fixed sparkctl links
  content/en/docs/components/spark-operator/overview/_index.md
  content/en/docs/components/spark-operator/user-guide/working-with-sparkapplication.md
Labels: size/XS, lgtm, approved
