Repository kubeflow/website, pull requests merged in 2024-06, with the labels that each got.

#3608 Link to RStudio
  content/en/docs/components/notebooks/overview.md
Labels: size/XS, lgtm, approved, ok-to-test

#3754 Add Slack channel for MPI Operator
  content/en/docs/about/community.md
Labels: size/XS, lgtm, approved

#3758 Fix links to packaged distributions section
  content/en/docs/components/central-dash/access.md
  content/en/docs/distributions/list.md
Labels: size/XS, lgtm, approved

#3759 fix a minor typo
  content/en/docs/components/training/user-guides/fine-tuning.md
Labels: size/XS, lgtm, approved, ok-to-test

#3740 model registry: pin tag and standalone instructions
  content/en/docs/components/model-registry/OWNERS
  content/en/docs/components/model-registry/installation.md
Labels: lgtm, approved, size/M

#3765 Katib: Update namespace in getting started guide
  content/en/docs/components/katib/getting-started.md
Labels: lgtm, approved, size/S

#3768 Fix invalid labels and broken links on PyTorch Training page
  content/en/docs/components/training/user-guides/pytorch.md
Labels: size/XS, lgtm, approved, ok-to-test

#3770 Katib: Fix getting started example
  content/en/docs/components/katib/getting-started.md
  content/en/docs/components/katib/installation.md
  content/en/docs/components/training/installation.md
Labels: lgtm, approved, size/S

#3771 Delete docs directory
  docs/components/pipelines/v2/components/containerized-python-components
Labels: size/XS, lgtm, approved

#3178 Fix typo on metadata docs
  content/en/docs/components/pipelines/concepts/metadata.md
Labels: size/XS, lgtm, approved, ok-to-test, lifecycle/stale

#3767 Add docs for spark-operator
  content/en/docs/components/spark-operator/OWNERS
  content/en/docs/components/spark-operator/_index.md
  content/en/docs/components/spark-operator/developer-guide.md
  content/en/docs/components/spark-operator/getting-started.md
  content/en/docs/components/spark-operator/overview/_index.md
  content/en/docs/components/spark-operator/overview/architecture-diagram.png
  content/en/docs/components/spark-operator/reference/_index.md
  content/en/docs/components/spark-operator/reference/api-docs.md
  content/en/docs/components/spark-operator/user-guide/_index.md
  content/en/docs/components/spark-operator/user-guide/customizing-spark-operator.md
  content/en/docs/components/spark-operator/user-guide/gcp.md
  content/en/docs/components/spark-operator/user-guide/leader-election.md
  content/en/docs/components/spark-operator/user-guide/resource-quota-enforcement.md
  content/en/docs/components/spark-operator/user-guide/running-multiple-instances-of-the-operator.md
  content/en/docs/components/spark-operator/user-guide/running-sparkapplication-on-schedule.md
  content/en/docs/components/spark-operator/user-guide/using-sparkapplication.md
  content/en/docs/components/spark-operator/user-guide/volcano-integration.md
  content/en/docs/components/spark-operator/user-guide/working-with-sparkapplication.md
  content/en/docs/components/spark-operator/user-guide/writing-sparkapplication.md
  content/en/docs/started/installing-kubeflow.md
Labels: size/XXL, lgtm, approved

#3772 Update to pipelines OWNERS
  content/en/docs/components/pipelines/OWNERS
Labels: size/XS, lgtm, approved

#3748 Update manifests warning
  content/en/docs/started/installing-kubeflow.md
Labels: lgtm, approved, size/S

#3780 Update Kubeflow diagrams with Spark Operator and Model Registry
  content/en/docs/started/images/kubeflow-architecture.drawio.svg
  content/en/docs/started/images/kubeflow-intro-diagram.drawio.svg
Labels: size/XS, lgtm, approved
