Repository kubeflow/website, pull requests merged in 2024-10, with the labels that each got.

#3887 Update spark-operator getting-started
  content/en/docs/components/spark-operator/getting-started.md
Labels: size/XS, lgtm, approved, ok-to-test

#3899 Fix broken links in Training Operator #3812
  content/en/docs/components/katib/user-guides/trial-template.md
  content/en/docs/components/training/user-guides/mpi.md
  content/en/docs/components/training/user-guides/tensorflow.md
  netlify.toml
Labels: lgtm, approved, size/S, ok-to-test

#3901 fix link in section Efficient Neural Architecture Search (ENAS)
  content/en/docs/components/katib/reference/nas-algorithms.md
Labels: size/XS, lgtm, approved, ok-to-test

#3906 docs: add diagram to reference
  content/en/docs/components/katib/images/katib-workflow.png
  content/en/docs/components/katib/reference/experiment-cr.md
Labels: lgtm, approved, size/M, ok-to-test, hacktoberfest

#3912 Update Documentation reference to the same version of Kubernetes API 1.29
  content/en/docs/components/notebooks/api-reference/notebook-v1.md
  content/en/docs/components/pipelines/reference/component-spec.md
  content/en/docs/components/spark-operator/user-guide/writing-sparkapplication.md
Labels: lgtm, approved, size/M

#3894 Add documentation for Prometheus metrics in Training Operator
  content/en/docs/components/training/user-guides/prometheus.md
Labels: lgtm, approved, size/M, ok-to-test

#3896 Training: Update example to run PyTorchJob with torchrun
  content/en/docs/components/katib/installation.md
  content/en/docs/components/training/getting-started.md
  content/en/docs/components/training/installation.md
Labels: lgtm, approved, size/M

#3877 Add documentation for JAXJob
  content/en/docs/components/training/images/training-operator-overview.drawio.png
  content/en/docs/components/training/images/training-operator-overview.drawio.svg
  content/en/docs/components/training/overview.md
  content/en/docs/components/training/user-guides/jax.md
  content/en/docs/components/training/user-guides/job-scheduling.md
  content/en/docs/components/training/user-guides/mpi.md
Labels: lgtm, approved, size/L, ok-to-test, area/gsoc

#3891 chore: add references to Intel Gaudi container images
  content/en/docs/components/notebooks/container-images.md
Labels: size/XS, lgtm, approved, ok-to-test
