Repository kubeflow/website, pull requests merged in 2025-03, with the labels that each got.

#4021 Update of the support page
  content/en/docs/started/support.md
Labels: lgtm, approved, size/L

#4027 chore: Bump kfp latest version to 2.4.0
  layouts/shortcodes/pipelines/latest-version.html
Labels: size/XS, lgtm, approved

#4028 clarify installation options
  content/en/docs/started/installing-kubeflow/index.md
Labels: lgtm, approved, size/S

#4013 Add model registry UI installation instructions
  content/en/docs/components/model-registry/getting-started.md
  content/en/docs/components/model-registry/images/model-registry-ui-main.png
  content/en/docs/components/model-registry/installation.md
Labels: lgtm, approved, size/M

#4026 website: Update GSoC projects with LLM-powered docs
  content/en/events/upcoming-events/gsoc-2025.md
Labels: lgtm, approved, size/L, area/gsoc

#4031 fix: SeaweedFS PoC link in GSoC project
  content/en/events/upcoming-events/gsoc-2025.md
Labels: size/XS, lgtm, approved, needs-ok-to-test

#4018 website: Issue4002 GitHub action to check pr title
  .github/workflows/pr_title_check.yaml
Labels: lgtm, approved, size/S

#4033 Fix Scheduling Policy doc for MPIJob
  content/en/docs/components/trainer/legacy-v1/user-guides/mpi.md
Labels: size/XS, lgtm, approved, ok-to-test, area/website, area/trainer

#4030 feat: Kubeflow Spark Operator Benchmarks Docs
  content/en/docs/components/spark-operator/performance/_index.md
  content/en/docs/components/spark-operator/performance/benchmarking.md
  content/en/docs/components/spark-operator/performance/job-start-latency.jpg
  content/en/docs/components/spark-operator/performance/kubernetes-metrics.jpg
  content/en/docs/components/spark-operator/performance/kubernetes-metrics1.jpg
  content/en/docs/components/spark-operator/performance/kubernetes-metrics3.jpg
  content/en/docs/components/spark-operator/performance/p90-apiserver-latency.jpg
  content/en/docs/components/spark-operator/performance/p90-apiserver-latency1.jpg
  content/en/docs/components/spark-operator/performance/spark-application-metrics.jpg
  content/en/docs/components/spark-operator/performance/spark-application-metrics1.jpg
  content/en/docs/components/spark-operator/performance/spark-application-metrics3.jpg
  content/en/docs/components/spark-operator/performance/spark-job-submission-rate.png
  content/en/docs/components/spark-operator/performance/spark-operator-pod-metrics.jpg
  content/en/docs/components/spark-operator/performance/spark-operator-pod-metrics1.jpg
  content/en/docs/components/spark-operator/performance/spark-operator-pod-metrics3.jpg
Labels: lgtm, approved, size/L, area/spark-operator

#4041 trainer: update get-started example of trainer.
  content/en/docs/components/trainer/getting-started.md
Labels: size/XS, lgtm, approved, area/trainer

#4046 model-registry: bump version to v0.2.15
  layouts/shortcodes/model-registry/latest-version.html
Labels: size/XS, lgtm, approved

#4040 spark-operator: customize spark operator
  content/en/docs/components/spark-operator/user-guide/customizing-spark-operator.md
Labels: lgtm, approved, size/S, area/spark-operator

#4042 model-registry: update the installation guide
  content/en/docs/components/model-registry/installation.md
Labels: lgtm, approved, size/M, ok-to-test, area/model-registry

#4058 trainer: update getting-started.md to reflect API changes
  content/en/docs/components/trainer/getting-started.md
Labels: lgtm, approved, size/S, ok-to-test, area/website, area/trainer

#3952 katib: [USERGUIDE] LLM Hyperparameter Optimization API
  content/en/docs/components/katib/user-guides/llm-hp-optimization.md
Labels: lgtm, approved, size/L, ok-to-test

#4057 pipelines: Improvements to the KFP overview doc
  content/en/docs/components/pipelines/overview.md
Labels: lgtm, approved, size/S

#4059 trainer: Update Slack channel
  content/en/docs/about/community.md
  content/en/docs/components/katib/user-guides/llm-hp-optimization.md
Labels: lgtm, approved, size/L

#4070 gsoc: add proposal guide to 2025 page
  content/en/events/upcoming-events/gsoc-2025.md
Labels: size/XS, lgtm, approved, area/gsoc
