Repository kubeflow/website, pull requests merged in 2025-01, with the labels that each got.

#3949 nit: fix typo add_node_selector_constraint to set_accelerator_type
  content/en/docs/components/pipelines/user-guides/migration.md
Labels: size/XS, lgtm, approved

#3953 Update run-trigger.md
  content/en/docs/components/pipelines/concepts/run-trigger.md
Labels: size/XS, lgtm, approved, ok-to-test

#3957 Update metadata.md
  content/en/docs/components/pipelines/concepts/metadata.md
Labels: size/XS, lgtm, approved, ok-to-test

#3955 Fix outdated 'url' key to 'link' in ConfigMap example
  content/en/docs/components/central-dash/customize.md
Labels: size/XS, lgtm, approved, ok-to-test

#3972 fix: inconsistent deploy documentation pns references
  content/en/docs/components/pipelines/legacy-v1/installation/localcluster-deployment.md
Labels: size/XS, lgtm, approved, ok-to-test

#3975 Typo in pipelines user guides data handling parameters
  content/en/docs/components/pipelines/user-guides/data-handling/parameters.md
Labels: size/XS, lgtm, approved, ok-to-test

#3976 Update user guide for namespace label in Katib Python SDK example
  content/en/docs/components/katib/getting-started.md
  content/en/docs/components/katib/user-guides/metrics-collector.md
Labels: lgtm, approved, size/S

#3963 Fixing build broken links for netlify build (remove from todoPatterns)
  content/en/docs/components/pipelines/concepts/pipeline-root.md
  content/en/docs/components/pipelines/legacy-v1/installation/standalone-deployment.md
  content/en/docs/components/pipelines/legacy-v1/installation/upgrade.md
  content/en/docs/components/training/user-guides/mpi.md
  content/en/docs/started/support.md
  netlify.toml
Labels: lgtm, approved, size/M, ok-to-test
