Repository kubeflow/website, pull requests merged in 2025-05, with the labels that each got.

#4099 trainer: update fine-tune example to use `eval_strategy`
  content/en/docs/components/trainer/legacy-v1/user-guides/fine-tuning.md
Labels: size/XS, lgtm, approved

#4106 website: update the link from training-operator to trainer
  content/en/docs/started/installing-kubeflow/index.md
Labels: size/XS, lgtm, approved, ok-to-test

#4048 model-registry: add YAML manifest example for creating InferenceService
  content/en/docs/components/model-registry/getting-started.md
Labels: lgtm, approved, size/S, ok-to-test, area/model-registry

#4097 pipelines: Add KFP documentation for importing modelcars
  content/en/docs/components/pipelines/user-guides/components/importer-component.md
Labels: lgtm, approved, size/S, area/pipelines

#4108 website: fix Alpha, Beta tooltip box (missing space)
  layouts/shortcodes/alpha-status.html
  layouts/shortcodes/beta-status.html
Labels: size/XS, lgtm, approved, area/website

#4110 website: Adding Governance page
  content/en/docs/about/community.md
  content/en/docs/about/governance.md
Labels: lgtm, approved, size/M

#4107 model-registry: better link to issue selector screen
  content/en/docs/components/model-registry/getting-started.md
  content/en/docs/components/model-registry/overview.md
Labels: size/XS, lgtm, approved, area/model-registry

#4114 model-registry: bump version to 0.2.18
  content/en/docs/components/model-registry/installation.md
  layouts/shortcodes/model-registry/latest-version.html
Labels: size/XS, lgtm, approved

#3885 add a new s3.forcePathStyle configuration parameter to the samples.
  content/en/docs/components/pipelines/operator-guides/configure-object-store.md
Labels: size/XS, lgtm, approved, ok-to-test, lifecycle/stale
