Repository kubeflow/website, pull requests merged in 2025-06, with the labels that each got.

#4124 model-registry: add Al-Pragliola in approvers
  content/en/docs/components/model-registry/OWNERS
  layouts/shortcodes/model-registry/OWNERS
Labels: size/XS, lgtm, approved

#4119 website: update main branch archive banner
  config.toml
  layouts/partials/version-banner.html
Labels: lgtm, approved, size/M, area/website

#4125 website: Adding GenAI focused page
  content/en/docs/genai/_index.md
  content/en/docs/genai/use-cases.md
Labels: lgtm, approved, size/L

#4089 spark-operator: Remove docs associated with sparkctl
  content/en/docs/components/spark-operator/developer-guide.md
  content/en/docs/components/spark-operator/overview/_index.md
  content/en/docs/components/spark-operator/user-guide/using-sparkapplication.md
  content/en/docs/components/spark-operator/user-guide/working-with-sparkapplication.md
Labels: lgtm, approved, size/M, area/spark-operator

#4120 website: add archive banner for 1.9 branch
  config.toml
  layouts/partials/head.html
  layouts/partials/version-banner.html
Labels: lgtm, approved, size/M, area/website

#4121 website: update (but not set) archive banner for 1.10 branch
  config.toml
  layouts/partials/version-banner.html
Labels: lgtm, approved, size/M, area/website

#4126 trainer: Update SDK source repo
  content/en/docs/components/trainer/getting-started.md
  content/en/docs/started/architecture.md
Labels: size/XS, lgtm, approved, ok-to-test, area/trainer

#4130 website: add ModelRegistry card in landing page
  assets/scss/_styles_project.scss
  content/en/_index.html
  content/en/docs/images/logos/ModelRegistry.png
Labels: lgtm, approved, size/S

#4133 website: Defining what is kubeflow
  content/en/_index.html
Labels: size/XS, lgtm, approved

#4095 gsoc: Update GSoC 2025 status to Application Closed
  config.toml
Labels: size/XS, lgtm, approved, ok-to-test, area/website, area/gsoc

#4049 pipelines: fix link in `Migrate to Kubeflow Pipelines v2`
  content/en/docs/components/pipelines/user-guides/migration.md
Labels: size/XS, lgtm, approved, ok-to-test, area/pipelines

#4051 website: added logic to the pr_title_check.yaml to put error message as a comment
  .github/pull_request_template.md
  .github/workflows/pr_title_check.yaml
Labels: lgtm, approved, size/S, area/website

#4067 katib: Update LLM HP tuning guide to clarify tunable fields and fix resource section
  content/en/docs/components/katib/user-guides/llm-hp-optimization.md
  content/en/docs/components/trainer/legacy-v1/user-guides/fine-tuning.md
Labels: lgtm, approved, size/L, area/katib, ok-to-test

#4136 website: Add Kubeflow Summit NA 2025 CFP to Top Menu and Update GSoC Status
  assets/scss/_styles_project.scss
  config.toml
Labels: lgtm, approved, size/M, ok-to-test, area/website, area/gsoc, area/community

#4137 website: fix header and announcements
  assets/scss/_styles_project.scss
  config.toml
Labels: lgtm, approved, size/S, area/website
